//@version=6
indicator("Universal GEX History (Bar Replay)", overlay=true, max_lines_count=500, max_labels_count=500)

// --- Generated 2026-01-11 ---
// Smart Rebuild: Forced

var string current_ticker = syminfo.ticker
var float plot_c_wall = na
var float plot_p_wall = na
var float plot_flip   = na
var float plot_c_gex  = na
var float plot_p_gex  = na
var float plot_c_dex  = na
var float plot_p_dex  = na
var float[] cur_strikes = array.new_float()
var int[]   cur_lengths = array.new_int()
var int[]   cur_signs   = array.new_int()
var string[] cur_labels = array.new_string()

// ===== AMZU FUNCTION =====
f_symbol_AMZU() =>
    var float plot_c_wall = na
    var float plot_p_wall = na
    var float plot_flip   = na
    var float[] cur_strikes = array.new_float()
    var int[]   cur_lengths = array.new_int()
    var int[]   cur_signs   = array.new_int()
    var string[] cur_labels = array.new_string()
    if year == 2026 and month == 1 and dayofmonth == 2
        plot_c_wall := 38.8
        plot_p_wall := 33.8
        plot_flip   := 29.9
        cur_strikes := array.from(38.8, 36.8, 40.0, 39.8, 35.0, 37.8, 31.8, 32.8, 34.8, 38.0, 36.0, 35.8, 37.0, 33.8, 30.8, 30.0, 29.8, 32.0, 39.0, 34.0, 33.0, 31.0)
        cur_lengths := array.from(40, 32, 28, 21, 10, 6, 6, 4, 4, 4, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, -1, 1, -1, -1, 1, 1, 1, 1, -1, -1, -1, 1, -1, -1, 1, -1, -1, -1)
        cur_labels  := array.from('$503K', '$405K', '$353K', '$271K', '$-136K', '$83K', '$-79K', '$-60K', '$60K', '$54K', '$49K', '$47K', '$-37K', '$-35K', '$-35K', '$34K', '$-24K', '$-22K', '$18K', '$-15K', '$-3K', '$-2K')
    if year == 2026 and month == 1 and dayofmonth == 3
        plot_c_wall := 36.8
        plot_p_wall := 33.8
        plot_flip   := 36.4
        cur_strikes := array.from(36.8, 35.0, 37.8, 31.8, 32.8, 34.8, 38.0, 36.0, 35.8, 37.0, 33.8, 30.8, 30.0, 29.8, 32.0, 28.8, 34.0, 33.0, 31.0, 29.0)
        cur_lengths := array.from(40, 13, 8, 7, 5, 5, 5, 4, 4, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, -1, 1, -1, -1, 1, 1, 1, 1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1)
        cur_labels  := array.from('$388K', '$-131K', '$80K', '$-75K', '$-58K', '$57K', '$52K', '$47K', '$45K', '$-36K', '$-34K', '$-33K', '$32K', '$-23K', '$-21K', '$-17K', '$-14K', '$-3K', '$-2K', '$-2K')
    if year == 2026 and month == 1 and dayofmonth == 4
        plot_c_wall := 36.8
        plot_p_wall := 35.0
        plot_flip   := na
        cur_strikes := array.from(35.0, 36.8, 33.8, 31.8, 32.8, 34.8, 30.8, 38.0, 34.0, 37.8, 37.0, 32.0, 29.8, 36.0, 28.8, 33.0, 35.8, 30.0, 31.0, 29.0)
        cur_lengths := array.from(40, 35, 16, 13, 8, 7, 7, 6, 6, 6, 5, 4, 4, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, 1, -1, -1, -1, 1, -1, 1, -1, 1, -1, -1, -1, 1, -1, -1, 1, 1, -1, -1)
        cur_labels  := array.from('$-353K', '$311K', '$-142K', '$-116K', '$-73K', '$66K', '$-65K', '$54K', '$-54K', '$53K', '$-51K', '$-39K', '$-39K', '$24K', '$-24K', '$-20K', '$18K', '$15K', '$-7K', '$-4K')
    if year == 2026 and month == 1 and dayofmonth == 5
        plot_c_wall := 36.8
        plot_p_wall := 35.0
        plot_flip   := na
        cur_strikes := array.from(35.0, 36.8, 33.8, 31.8, 32.8, 34.8, 30.8, 38.0, 34.0, 37.8, 37.0, 32.0, 29.8, 36.0, 28.8, 33.0, 35.8, 30.0, 31.0, 29.0)
        cur_lengths := array.from(40, 35, 16, 13, 8, 7, 7, 6, 6, 6, 5, 4, 4, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, 1, -1, -1, -1, 1, -1, 1, -1, 1, -1, -1, -1, 1, -1, -1, 1, 1, -1, -1)
        cur_labels  := array.from('$-353K', '$311K', '$-143K', '$-116K', '$-73K', '$66K', '$-65K', '$54K', '$-54K', '$53K', '$-51K', '$-40K', '$-39K', '$25K', '$-25K', '$-20K', '$18K', '$15K', '$-7K', '$-4K')
    if year == 2026 and month == 1 and dayofmonth == 6
        plot_c_wall := 36.8
        plot_p_wall := 35.0
        plot_flip   := 39.4
        cur_strikes := array.from(35.0, 40.0, 38.8, 36.8, 39.8, 33.8, 31.8, 40.8, 32.8, 38.0, 34.8, 30.8, 37.8, 34.0, 32.0, 37.0, 39.0, 36.0, 33.0, 35.8, 31.0)
        cur_lengths := array.from(40, 38, 38, 36, 19, 16, 13, 11, 8, 7, 7, 7, 6, 6, 5, 5, 3, 3, 2, 2, 2)
        cur_signs   := array.from(-1, 1, 1, 1, 1, -1, -1, 1, -1, 1, 1, -1, 1, -1, -1, -1, 1, 1, -1, 1, -1)
        cur_labels  := array.from('$-365K', '$355K', '$347K', '$329K', '$180K', '$-151K', '$-122K', '$103K', '$-77K', '$72K', '$69K', '$-69K', '$56K', '$-56K', '$-49K', '$-46K', '$29K', '$28K', '$-25K', '$19K', '$-13K')
    if year == 2026 and month == 1 and dayofmonth == 7
        plot_c_wall := 38.8
        plot_p_wall := 33.8
        plot_flip   := 36.4
        cur_strikes := array.from(38.8, 36.8, 40.0, 39.8, 33.8, 40.8, 37.8, 38.0, 35.0, 32.8, 36.0, 42.0, 41.0, 34.8, 35.8, 39.0, 42.8, 37.0, 43.0, 41.8, 34.0, 33.0)
        cur_lengths := array.from(40, 31, 29, 17, 10, 8, 6, 5, 5, 4, 4, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, -1, 1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, -1, -1)
        cur_labels  := array.from('$603K', '$481K', '$447K', '$264K', '$-159K', '$132K', '$100K', '$82K', '$-79K', '$-72K', '$66K', '$52K', '$51K', '$47K', '$41K', '$31K', '$20K', '$-18K', '$9K', '$8K', '$-5K', '$-3K')
    if year == 2026 and month == 1 and dayofmonth == 8
        plot_c_wall := 38.8
        plot_p_wall := 35.0
        plot_flip   := 36.9
        cur_strikes := array.from(38.8, 40.0, 39.8, 40.8, 36.8, 35.0, 36.0, 37.8, 38.0, 32.8, 42.0, 37.0, 41.0, 33.8, 39.0, 35.8, 43.8, 34.8, 34.0, 42.8, 33.0, 43.0, 41.8)
        cur_lengths := array.from(40, 29, 23, 13, 9, 8, 6, 6, 6, 5, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1, -1, 1, 1, 1, -1, 1, 1, 1, -1, 1, 1, 1, 1, -1, 1, -1, 1, 1)
        cur_labels  := array.from('$940K', '$701K', '$551K', '$315K', '$213K', '$-211K', '$155K', '$150K', '$146K', '$-141K', '$86K', '$79K', '$78K', '$-68K', '$52K', '$43K', '$43K', '$38K', '$-35K', '$33K', '$-27K', '$16K', '$14K')
    if year == 2026 and month == 1 and dayofmonth == 9
        plot_c_wall := 38.8
        plot_p_wall := 35.0
        plot_flip   := 36.4
        cur_strikes := array.from(38.8, 40.0, 39.8, 40.8, 42.0, 35.0, 36.8, 36.0, 38.0, 37.8, 45.0, 37.0, 41.0, 33.8, 39.0, 43.8, 42.8, 34.0, 34.8, 44.0, 43.0, 41.8, 44.8, 35.8)
        cur_lengths := array.from(40, 28, 22, 13, 9, 8, 8, 6, 6, 5, 4, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, -1, 1, 1, 1, 1, 1, 1)
        cur_labels  := array.from('$1.06M', '$758K', '$584K', '$359K', '$240K', '$-220K', '$214K', '$174K', '$164K', '$135K', '$121K', '$86K', '$84K', '$-77K', '$73K', '$60K', '$37K', '$-34K', '$31K', '$29K', '$24K', '$22K', '$15K', '$12K')
    if year == 2026 and month == 1 and dayofmonth == 10
        plot_c_wall := 40.0
        plot_p_wall := 35.0
        plot_flip   := 37.4
        cur_strikes := array.from(40.0, 38.8, 39.8, 40.8, 42.0, 35.0, 45.0, 36.8, 37.8, 41.0, 39.0, 42.8, 43.8, 44.0, 43.0, 41.8, 34.0, 38.0, 34.8, 44.8, 37.0, 35.8, 36.0)
        cur_lengths := array.from(40, 31, 26, 17, 9, 5, 5, 5, 4, 4, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, -1, 1, -1)
        cur_labels  := array.from('$1.16M', '$918K', '$761K', '$515K', '$280K', '$-174K', '$156K', '$149K', '$142K', '$118K', '$108K', '$62K', '$60K', '$37K', '$37K', '$35K', '$-28K', '$25K', '$20K', '$19K', '$-16K', '$10K', '$-259')
    [plot_c_wall, plot_p_wall, plot_flip, cur_strikes, cur_lengths, cur_signs, cur_labels]

// ===== BBAI FUNCTION =====
f_symbol_BBAI() =>
    var float plot_c_wall = na
    var float plot_p_wall = na
    var float plot_flip   = na
    var float[] cur_strikes = array.new_float()
    var int[]   cur_lengths = array.new_int()
    var int[]   cur_signs   = array.new_int()
    var string[] cur_labels = array.new_string()
    if year == 2025 and month == 12 and dayofmonth == 23
        plot_c_wall := 7.0
        plot_p_wall := 6.0
        plot_flip   := 2.25
        cur_strikes := array.from(7.0, 8.0, 10.0, 9.0, 4.0, 12.0, 5.0, 11.0, 15.0, 17.0, 3.5, 6.0, 13.0, 5.5, 16.0, 3.0, 4.5, 14.0, 8.5, 1.5, 2.5, 6.5, 2.0, 1.0, 9.5, 7.5, 10.5, 0.5)
        cur_lengths := array.from(40, 33, 20, 7, 4, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, -1, 1, 1, 1, -1, 1, -1, 1, -1)
        cur_labels  := array.from('$4.66M', '$3.86M', '$2.39M', '$894K', '$534K', '$488K', '$484K', '$294K', '$291K', '$261K', '$227K', '$134K', '$78K', '$-68K', '$62K', '$62K', '$55K', '$51K', '$27K', '$-22K', '$22K', '$12K', '$8K', '$-5K', '$2K', '$-562', '$43', '$-27')
    if year == 2025 and month == 12 and dayofmonth == 23
        plot_c_wall := 7.0
        plot_p_wall := 6.0
        plot_flip   := 2.25
        cur_strikes := array.from(7.0, 8.0, 10.0, 9.0, 4.0, 12.0, 5.0, 11.0, 15.0, 17.0, 3.5, 6.0, 13.0, 5.5, 16.0, 3.0, 4.5, 14.0, 8.5, 1.5, 2.5, 6.5, 2.0, 1.0, 9.5, 7.5, 10.5, 0.5)
        cur_lengths := array.from(40, 33, 20, 7, 4, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, -1, 1, 1, 1, -1, 1, -1, 1, -1)
        cur_labels  := array.from('$4.66M', '$3.86M', '$2.39M', '$894K', '$534K', '$488K', '$484K', '$294K', '$291K', '$261K', '$227K', '$134K', '$78K', '$-68K', '$62K', '$62K', '$55K', '$51K', '$27K', '$-22K', '$22K', '$12K', '$8K', '$-5K', '$2K', '$-562', '$43', '$-27')
    if year == 2025 and month == 12 and dayofmonth == 24
        plot_c_wall := 7.0
        plot_p_wall := 6.0
        plot_flip   := 2.25
        cur_strikes := array.from(7.0, 8.0, 10.0, 9.0, 4.0, 12.0, 5.0, 11.0, 15.0, 17.0, 3.5, 6.0, 13.0, 5.5, 16.0, 3.0, 4.5, 14.0, 8.5, 1.5, 2.5, 6.5, 2.0, 1.0, 9.5, 7.5, 10.5, 0.5)
        cur_lengths := array.from(40, 33, 20, 7, 4, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, -1, 1, 1, 1, -1, 1, -1, 1, -1)
        cur_labels  := array.from('$4.66M', '$3.86M', '$2.39M', '$894K', '$534K', '$488K', '$484K', '$294K', '$291K', '$261K', '$227K', '$134K', '$78K', '$-68K', '$62K', '$62K', '$55K', '$51K', '$27K', '$-22K', '$22K', '$12K', '$8K', '$-5K', '$2K', '$-562', '$43', '$-27')
    if year == 2025 and month == 10 and dayofmonth == 13
        plot_c_wall := 9.0
        plot_p_wall := 9.0
        plot_flip   := na
        cur_strikes := array.from(9.0, 8.5, 9.5, 8.0, 10.0, 7.5, 10.5)
        cur_lengths := array.from(40, 5, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1, 1, 1)
        cur_labels  := array.from('$11.59M', '$1.62M', '$2K', '$56', '$0', '$0', '$0')
    if year == 2025 and month == 10 and dayofmonth == 14
        plot_c_wall := 9.0
        plot_p_wall := 9.0
        plot_flip   := 7.75
        cur_strikes := array.from(9.0, 8.5, 9.5, 8.0, 10.0, 10.5, 7.5)
        cur_lengths := array.from(40, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1, 1, -1)
        cur_labels  := array.from('$22.49M', '$380K', '$8K', '$0', '$0', '$0', '$-0')
    if year == 2025 and month == 10 and dayofmonth == 15
        plot_c_wall := 8.5
        plot_p_wall := 8.5
        plot_flip   := 7.25
        cur_strikes := array.from(8.5, 9.0, 8.0, 9.5, 7.5, 10.0, 7.0)
        cur_lengths := array.from(40, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, -1, 1, 1)
        cur_labels  := array.from('$26.87M', '$7K', '$389', '$0', '$-0', '$0', '$0')
    if year == 2025 and month == 10 and dayofmonth == 16
        plot_c_wall := 7.5
        plot_p_wall := 7.5
        plot_flip   := 6.75
        cur_strikes := array.from(7.5, 8.0, 7.0, 8.5, 9.0, 6.5)
        cur_lengths := array.from(40, 4, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1, -1)
        cur_labels  := array.from('$113K', '$12K', '$0', '$0', '$0', '$-0')
    if year == 2025 and month == 10 and dayofmonth == 20
        plot_c_wall := 8.0
        plot_p_wall := 8.0
        plot_flip   := 6.5
        cur_strikes := array.from(8.0, 7.0, 6.0)
        cur_lengths := array.from(40, 28, 2)
        cur_signs   := array.from(1, 1, -1)
        cur_labels  := array.from('$1.89M', '$1.36M', '$-578')
    if year == 2025 and month == 10 and dayofmonth == 21
        plot_c_wall := 7.0
        plot_p_wall := 7.0
        plot_flip   := 6.75
        cur_strikes := array.from(7.0, 8.0, 7.5, 6.0, 6.5)
        cur_lengths := array.from(40, 4, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, -1, -1)
        cur_labels  := array.from('$3.01M', '$324K', '$23K', '$-19K', '$-18K')
    if year == 2025 and month == 10 and dayofmonth == 22
        plot_c_wall := 7.0
        plot_p_wall := 7.0
        plot_flip   := na
        cur_strikes := array.from(6.5, 7.0, 6.0, 7.5, 5.5)
        cur_lengths := array.from(40, 37, 33, 2, 2)
        cur_signs   := array.from(-1, 1, -1, 1, -1)
        cur_labels  := array.from('$-872K', '$821K', '$-730K', '$5K', '$-200')
    if year == 2025 and month == 10 and dayofmonth == 23
        plot_c_wall := 7.0
        plot_p_wall := 7.0
        plot_flip   := 6.75
        cur_strikes := array.from(7.0, 6.5, 6.0, 8.0, 7.5, 5.5)
        cur_lengths := array.from(40, 19, 6, 2, 2, 2)
        cur_signs   := array.from(1, -1, -1, 1, 1, -1)
        cur_labels  := array.from('$1.38M', '$-661K', '$-238K', '$27K', '$16K', '$-52')
    if year == 2025 and month == 10 and dayofmonth == 24
        plot_c_wall := 7.0
        plot_p_wall := 7.0
        plot_flip   := 6.75
        cur_strikes := array.from(7.0, 6.5, 8.0, 7.5, 6.0)
        cur_lengths := array.from(40, 5, 4, 2, 2)
        cur_signs   := array.from(1, -1, 1, 1, -1)
        cur_labels  := array.from('$1.79M', '$-235K', '$212K', '$70K', '$-22K')
    if year == 2025 and month == 10 and dayofmonth == 27
        plot_c_wall := 7.0
        plot_p_wall := 7.0
        plot_flip   := 6.75
        cur_strikes := array.from(7.0, 8.0, 6.5, 7.5, 6.0, 8.5)
        cur_lengths := array.from(40, 5, 3, 3, 2, 2)
        cur_signs   := array.from(1, 1, -1, 1, -1, 1)
        cur_labels  := array.from('$1.82M', '$241K', '$-163K', '$158K', '$-7K', '$326')
    if year == 2025 and month == 10 and dayofmonth == 28
        plot_c_wall := 7.0
        plot_p_wall := 7.0
        plot_flip   := 6.75
        cur_strikes := array.from(7.0, 6.5, 6.0, 7.5, 8.0, 5.5)
        cur_lengths := array.from(40, 16, 3, 2, 2, 2)
        cur_signs   := array.from(1, -1, -1, 1, 1, -1)
        cur_labels  := array.from('$1.80M', '$-723K', '$-146K', '$29K', '$12K', '$-13')
    if year == 2025 and month == 10 and dayofmonth == 29
        plot_c_wall := 7.0
        plot_p_wall := 7.0
        plot_flip   := 6.75
        cur_strikes := array.from(7.0, 6.5, 7.5, 8.0, 6.0)
        cur_lengths := array.from(40, 6, 5, 2, 2)
        cur_signs   := array.from(1, -1, 1, 1, -1)
        cur_labels  := array.from('$2.66M', '$-462K', '$359K', '$40K', '$-39K')
    if year == 2025 and month == 10 and dayofmonth == 30
        plot_c_wall := 7.0
        plot_p_wall := 7.0
        plot_flip   := 6.75
        cur_strikes := array.from(7.0, 6.5, 7.5, 6.0, 8.0, 5.5)
        cur_lengths := array.from(40, 15, 11, 2, 2, 2)
        cur_signs   := array.from(1, -1, 1, -1, 1, -1)
        cur_labels  := array.from('$2.34M', '$-904K', '$653K', '$-158K', '$5K', '$-12')
    if year == 2025 and month == 10 and dayofmonth == 31
        plot_c_wall := 7.0
        plot_p_wall := 7.0
        plot_flip   := 6.75
        cur_strikes := array.from(7.0, 7.5, 6.5, 8.0, 6.0)
        cur_lengths := array.from(40, 27, 5, 2, 2)
        cur_signs   := array.from(1, 1, -1, 1, -1)
        cur_labels  := array.from('$3.30M', '$2.31M', '$-462K', '$32K', '$-21K')
    if year == 2025 and month == 11 and dayofmonth == 3
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(6.0, 6.5, 7.0, 5.5, 7.5)
        cur_lengths := array.from(40, 15, 2, 2, 2)
        cur_signs   := array.from(-1, -1, 1, -1, 1)
        cur_labels  := array.from('$-3.05M', '$-1.19M', '$144K', '$-2K', '$1K')
    if year == 2025 and month == 11 and dayofmonth == 4
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(6.0, 5.5, 5.0, 6.5)
        cur_lengths := array.from(40, 5, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1)
        cur_labels  := array.from('$-4.03M', '$-568K', '$-8K', '$-7K')
    if year == 2025 and month == 11 and dayofmonth == 5
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(6.0, 6.5, 5.5, 7.0, 5.0)
        cur_lengths := array.from(40, 4, 2, 2, 2)
        cur_signs   := array.from(-1, 1, -1, 1, -1)
        cur_labels  := array.from('$-6.68M', '$670K', '$-28K', '$23K', '$-2')
    if year == 2025 and month == 11 and dayofmonth == 6
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(6.0, 5.5, 5.0, 6.5)
        cur_lengths := array.from(40, 25, 2, 2)
        cur_signs   := array.from(-1, -1, -1, 1)
        cur_labels  := array.from('$-2.51M', '$-1.59M', '$-13K', '$2K')
    if year == 2025 and month == 11 and dayofmonth == 7
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(6.0, 5.5, 5.0, 6.5)
        cur_lengths := array.from(40, 24, 2, 2)
        cur_signs   := array.from(-1, -1, -1, 1)
        cur_labels  := array.from('$-2.67M', '$-1.64M', '$-6K', '$2K')
    if year == 2025 and month == 11 and dayofmonth == 10
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(5.5, 6.0, 5.0, 6.5)
        cur_lengths := array.from(40, 23, 2, 2)
        cur_signs   := array.from(-1, -1, -1, 1)
        cur_labels  := array.from('$-3.24M', '$-1.91M', '$-616', '$342')
    if year == 2025 and month == 11 and dayofmonth == 11
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(6.0, 6.5, 5.5, 7.0, 5.0)
        cur_lengths := array.from(40, 2, 2, 2, 2)
        cur_signs   := array.from(-1, 1, -1, 1, -1)
        cur_labels  := array.from('$-3.69M', '$199K', '$-32K', '$141', '$-0')
    if year == 2025 and month == 11 and dayofmonth == 12
        plot_c_wall := 7.0
        plot_p_wall := 7.0
        plot_flip   := 6.25
        cur_strikes := array.from(7.0, 7.5, 8.0, 6.5, 8.5, 6.0)
        cur_lengths := array.from(40, 13, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1, -1)
        cur_labels  := array.from('$10.64M', '$3.71M', '$7K', '$6K', '$0', '$-0')
    if year == 2025 and month == 11 and dayofmonth == 13
        plot_c_wall := 6.5
        plot_p_wall := 6.5
        plot_flip   := na
        cur_strikes := array.from(6.0, 6.5, 7.0, 5.5, 7.5)
        cur_lengths := array.from(40, 16, 2, 2, 2)
        cur_signs   := array.from(-1, 1, 1, -1, 1)
        cur_labels  := array.from('$-697K', '$289K', '$15K', '$-4', '$0')
    if year == 2025 and month == 11 and dayofmonth == 14
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(6.0, 6.5, 5.5, 7.0, 5.0)
        cur_lengths := array.from(40, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, 1, -1)
        cur_labels  := array.from('$-7.91M', '$-6K', '$-4K', '$1', '$-0')
    if year == 2025 and month == 11 and dayofmonth == 17
        plot_c_wall := 5.5
        plot_p_wall := 5.5
        plot_flip   := na
        cur_strikes := array.from(5.5, 6.0, 5.0, 6.5, 4.5)
        cur_lengths := array.from(40, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, 1, -1)
        cur_labels  := array.from('$-9.41M', '$-6K', '$-1', '$0', '$-0')
    if year == 2025 and month == 11 and dayofmonth == 18
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := 5.75
        cur_strikes := array.from(6.0, 6.5, 5.5, 7.0, 5.0)
        cur_lengths := array.from(40, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, -1, 1, -1)
        cur_labels  := array.from('$1.50M', '$37', '$-27', '$0', '$-0')
    if year == 2025 and month == 11 and dayofmonth == 19
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := 5.75
        cur_strikes := array.from(6.0, 5.5, 6.5, 5.0, 7.0)
        cur_lengths := array.from(40, 2, 2, 2, 2)
        cur_signs   := array.from(1, -1, 1, -1, 1)
        cur_labels  := array.from('$575K', '$-731', '$0', '$-0', '$0')
    if year == 2025 and month == 11 and dayofmonth == 20
        plot_c_wall := 5.5
        plot_p_wall := 5.5
        plot_flip   := na
        cur_strikes := array.from(5.5, 6.0, 5.0, 6.5, 4.5)
        cur_lengths := array.from(40, 2, 2, 2, 2)
        cur_signs   := array.from(-1, 1, -1, 1, -1)
        cur_labels  := array.from('$-30.17M', '$0', '$-0', '$0', '$-0')
    if year == 2025 and month == 11 and dayofmonth == 24
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(7.0, 6.0, 5.5)
        cur_lengths := array.from(40, 8, 2)
        cur_signs   := array.from(1, 1, 1)
        cur_labels  := array.from('$990K', '$218K', '$28K')
    if year == 2025 and month == 11 and dayofmonth == 25
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := 5.25
        cur_strikes := array.from(6.5, 7.0, 6.0, 5.5, 5.0)
        cur_lengths := array.from(40, 32, 20, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, -1)
        cur_labels  := array.from('$614K', '$492K', '$310K', '$40K', '$-51')
    if year == 2025 and month == 11 and dayofmonth == 26
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := 5.25
        cur_strikes := array.from(6.0, 6.5, 5.5, 7.0, 5.0)
        cur_lengths := array.from(40, 36, 17, 8, 2)
        cur_signs   := array.from(1, 1, 1, 1, -1)
        cur_labels  := array.from('$329K', '$300K', '$141K', '$71K', '$-535')
    if year == 2025 and month == 11 and dayofmonth == 28
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(7.0, 6.5, 6.0, 5.5, 7.5)
        cur_lengths := array.from(40, 29, 3, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1)
        cur_labels  := array.from('$1.30M', '$972K', '$118K', '$4K', '$743')
    if year == 2025 and month == 12 and dayofmonth == 1
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := 5.25
        cur_strikes := array.from(6.5, 6.0, 5.5, 7.0, 5.0)
        cur_lengths := array.from(40, 8, 6, 3, 2)
        cur_signs   := array.from(1, 1, 1, 1, -1)
        cur_labels  := array.from('$336K', '$73K', '$51K', '$29K', '$-33')
    if year == 2025 and month == 12 and dayofmonth == 2
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := 5.25
        cur_strikes := array.from(6.0, 5.5, 6.5, 5.0)
        cur_lengths := array.from(40, 36, 3, 2)
        cur_signs   := array.from(-1, 1, 1, -1)
        cur_labels  := array.from('$-232K', '$214K', '$21K', '$-3K')
    if year == 2025 and month == 12 and dayofmonth == 3
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := 5.25
        cur_strikes := array.from(6.5, 7.0, 6.0, 5.5, 5.0)
        cur_lengths := array.from(40, 3, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, -1)
        cur_labels  := array.from('$392K', '$30K', '$16K', '$4K', '$-3')
    if year == 2025 and month == 12 and dayofmonth == 4
        plot_c_wall := 7.0
        plot_p_wall := 7.0
        plot_flip   := 6.25
        cur_strikes := array.from(7.0, 7.5, 6.5, 8.0, 6.0)
        cur_lengths := array.from(40, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, -1)
        cur_labels  := array.from('$19.33M', '$525K', '$173K', '$26K', '$-2')
    if year == 2025 and month == 12 and dayofmonth == 5
        plot_c_wall := 7.0
        plot_p_wall := 7.0
        plot_flip   := 5.75
        cur_strikes := array.from(7.0, 6.5, 7.5, 6.0, 8.0, 5.5)
        cur_lengths := array.from(40, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, -1, 1, 1)
        cur_labels  := array.from('$16.21M', '$682K', '$130K', '$-831', '$713', '$0')
    if year == 2025 and month == 12 and dayofmonth == 8
        plot_c_wall := 7.0
        plot_p_wall := 6.5
        plot_flip   := 6.25
        cur_strikes := array.from(7.0, 6.5, 6.0, 7.5, 5.5)
        cur_lengths := array.from(40, 29, 2, 2, 2)
        cur_signs   := array.from(1, 1, -1, 1, -1)
        cur_labels  := array.from('$2.92M', '$2.13M', '$-15K', '$688', '$-0')
    if year == 2025 and month == 12 and dayofmonth == 9
        plot_c_wall := 7.0
        plot_p_wall := 7.0
        plot_flip   := 6.25
        cur_strikes := array.from(7.0, 6.5, 7.5, 6.0, 8.0, 5.5)
        cur_lengths := array.from(40, 4, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, -1, 1, -1)
        cur_labels  := array.from('$9.58M', '$972K', '$7K', '$-1K', '$1', '$-0')
    if year == 2025 and month == 12 and dayofmonth == 10
        plot_c_wall := 7.0
        plot_p_wall := 6.5
        plot_flip   := 6.25
        cur_strikes := array.from(7.0, 6.5, 6.0, 7.5, 5.5)
        cur_lengths := array.from(40, 15, 2, 2, 2)
        cur_signs   := array.from(1, 1, -1, 1, -1)
        cur_labels  := array.from('$3.79M', '$1.48M', '$-6K', '$477', '$-0')
    if year == 2025 and month == 12 and dayofmonth == 11
        plot_c_wall := 7.0
        plot_p_wall := 7.0
        plot_flip   := 5.75
        cur_strikes := array.from(7.0, 6.5, 7.5, 6.0, 8.0, 5.5)
        cur_lengths := array.from(40, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, -1, 1, 1)
        cur_labels  := array.from('$11.04M', '$432K', '$4K', '$-151', '$0', '$0')
    if year == 2025 and month == 12 and dayofmonth == 12
        plot_c_wall := 6.5
        plot_p_wall := 6.5
        plot_flip   := 5.75
        cur_strikes := array.from(6.5, 6.0, 7.0, 7.5, 5.5)
        cur_lengths := array.from(40, 12, 3, 2, 2)
        cur_signs   := array.from(1, -1, 1, 1, 1)
        cur_labels  := array.from('$450K', '$-137K', '$36K', '$0', '$0')
    if year == 2025 and month == 12 and dayofmonth == 15
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(6.0, 6.5, 5.5, 7.0, 5.0)
        cur_lengths := array.from(40, 2, 2, 2, 2)
        cur_signs   := array.from(-1, 1, -1, 1, -1)
        cur_labels  := array.from('$-5.93M', '$43', '$-7', '$0', '$-0')
    if year == 2025 and month == 12 and dayofmonth == 16
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(6.0, 5.5, 6.5, 5.0, 7.0)
        cur_lengths := array.from(40, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, 1, -1, 1)
        cur_labels  := array.from('$-2.06M', '$-4K', '$0', '$-0', '$0')
    if year == 2025 and month == 12 and dayofmonth == 17
        plot_c_wall := 5.5
        plot_p_wall := 5.5
        plot_flip   := na
        cur_strikes := array.from(5.5, 5.0, 6.0, 6.5, 4.5)
        cur_lengths := array.from(40, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, 1, -1)
        cur_labels  := array.from('$-7.18M', '$-0', '$-0', '$0', '$-0')
    if year == 2025 and month == 12 and dayofmonth == 18
        plot_c_wall := 5.5
        plot_p_wall := 5.5
        plot_flip   := na
        cur_strikes := array.from(5.5, 6.0, 5.0, 6.5)
        cur_lengths := array.from(40, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, 1)
        cur_labels  := array.from('$-635K', '$-0', '$-0', '$0')
    if year == 2025 and month == 12 and dayofmonth == 22
        plot_c_wall := 7.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(7.0, 6.0, 5.5)
        cur_lengths := array.from(40, 13, 2)
        cur_signs   := array.from(1, 1, 1)
        cur_labels  := array.from('$4.94M', '$1.72M', '$5K')
    if year == 2025 and month == 12 and dayofmonth == 23
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(6.0, 7.0, 5.5, 6.5, 5.0)
        cur_lengths := array.from(40, 5, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1)
        cur_labels  := array.from('$3.68M', '$530K', '$60K', '$38K', '$256')
    if year == 2025 and month == 12 and dayofmonth == 24
        plot_c_wall := 7.0
        plot_p_wall := 6.0
        plot_flip   := 6.25
        cur_strikes := array.from(7.0, 6.5, 6.0, 5.5)
        cur_lengths := array.from(40, 21, 4, 3)
        cur_signs   := array.from(1, 1, -1, -1)
        cur_labels  := array.from('$9.50M', '$5.03M', '$-1.14M', '$-869K')
    if year == 2025 and month == 12 and dayofmonth == 25
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := 6.25
        cur_strikes := array.from(6.5, 5.5, 6.0)
        cur_lengths := array.from(40, 6, 5)
        cur_signs   := array.from(1, -1, 1)
        cur_labels  := array.from('$3.31M', '$-499K', '$478K')
    if year == 2025 and month == 12 and dayofmonth == 26
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := 6.25
        cur_strikes := array.from(6.5, 5.5, 6.0)
        cur_lengths := array.from(40, 6, 5)
        cur_signs   := array.from(1, -1, 1)
        cur_labels  := array.from('$3.31M', '$-499K', '$478K')
    if year == 2025 and month == 12 and dayofmonth == 27
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := 5.25
        cur_strikes := array.from(6.5, 6.0, 5.5, 5.0)
        cur_lengths := array.from(40, 32, 21, 14)
        cur_signs   := array.from(1, 1, -1, 1)
        cur_labels  := array.from('$1.23M', '$1.01M', '$-653K', '$446K')
    if year == 2025 and month == 12 and dayofmonth == 28
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := 5.25
        cur_strikes := array.from(6.5, 6.0, 5.5, 5.0)
        cur_lengths := array.from(40, 32, 21, 14)
        cur_signs   := array.from(1, 1, -1, 1)
        cur_labels  := array.from('$1.23M', '$1.01M', '$-653K', '$446K')
    if year == 2025 and month == 12 and dayofmonth == 29
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := 5.25
        cur_strikes := array.from(6.5, 6.0, 5.5, 5.0)
        cur_lengths := array.from(40, 32, 21, 14)
        cur_signs   := array.from(1, 1, -1, 1)
        cur_labels  := array.from('$1.23M', '$1.01M', '$-653K', '$446K')
    if year == 2025 and month == 12 and dayofmonth == 30
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := 5.25
        cur_strikes := array.from(6.0, 5.5, 6.5, 5.0)
        cur_lengths := array.from(40, 35, 31, 19)
        cur_signs   := array.from(1, -1, 1, 1)
        cur_labels  := array.from('$1.09M', '$-967K', '$853K', '$542K')
    if year == 2025 and month == 12 and dayofmonth == 31
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := 5.25
        cur_strikes := array.from(6.0, 5.5, 5.0)
        cur_lengths := array.from(40, 28, 7)
        cur_signs   := array.from(1, -1, 1)
        cur_labels  := array.from('$2.26M', '$-1.64M', '$404K')
    if year == 2026 and month == 1 and dayofmonth == 1
        plot_c_wall := 6.0
        plot_p_wall := 5.5
        plot_flip   := 5.75
        cur_strikes := array.from(6.0, 5.5, 5.0)
        cur_lengths := array.from(40, 31, 6)
        cur_signs   := array.from(1, -1, -1)
        cur_labels  := array.from('$3.44M', '$-2.71M', '$-518K')
    if year == 2026 and month == 1 and dayofmonth == 2
        plot_c_wall := 6.0
        plot_p_wall := 5.5
        plot_flip   := na
        cur_strikes := array.from(6.0, 5.0, 5.5)
        cur_lengths := array.from(40, 6, 5)
        cur_signs   := array.from(1, 1, 1)
        cur_labels  := array.from('$4.30M', '$694K', '$580K')
    if year == 2026 and month == 1 and dayofmonth == 3
        plot_c_wall := 6.0
        plot_p_wall := 5.5
        plot_flip   := na
        cur_strikes := array.from(6.0, 5.0, 6.5, 5.5)
        cur_lengths := array.from(40, 18, 11, 2)
        cur_signs   := array.from(1, 1, 1, -1)
        cur_labels  := array.from('$3.35M', '$1.55M', '$961K', '$-27K')
    if year == 2026 and month == 1 and dayofmonth == 4
        plot_c_wall := 6.0
        plot_p_wall := 5.5
        plot_flip   := 5.75
        cur_strikes := array.from(6.0, 6.5, 5.5, 5.0)
        cur_lengths := array.from(40, 35, 17, 10)
        cur_signs   := array.from(1, 1, -1, -1)
        cur_labels  := array.from('$1.28M', '$1.15M', '$-553K', '$-322K')
    if year == 2026 and month == 1 and dayofmonth == 5
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(5.5, 6.5, 5.0, 6.0)
        cur_lengths := array.from(40, 22, 16, 4)
        cur_signs   := array.from(-1, 1, -1, 1)
        cur_labels  := array.from('$-2.61M', '$1.47M', '$-1.11M', '$319K')
    if year == 2026 and month == 1 and dayofmonth == 6
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(5.5, 6.5, 5.0, 6.0)
        cur_lengths := array.from(40, 22, 21, 9)
        cur_signs   := array.from(-1, 1, -1, 1)
        cur_labels  := array.from('$-2.63M', '$1.48M', '$-1.44M', '$643K')
    if year == 2026 and month == 1 and dayofmonth == 7
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := 5.75
        cur_strikes := array.from(7.0, 6.0, 6.5, 5.5)
        cur_lengths := array.from(40, 25, 10, 5)
        cur_signs   := array.from(1, 1, 1, -1)
        cur_labels  := array.from('$6.72M', '$4.22M', '$1.82M', '$-878K')
    if year == 2026 and month == 1 and dayofmonth == 8
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := 5.75
        cur_strikes := array.from(6.0, 6.5, 5.5)
        cur_lengths := array.from(40, 30, 2)
        cur_signs   := array.from(1, 1, -1)
        cur_labels  := array.from('$7.15M', '$5.49M', '$-281K')
    if year == 2026 and month == 1 and dayofmonth == 9
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := 5.75
        cur_strikes := array.from(7.0, 6.5, 6.0, 5.5)
        cur_lengths := array.from(40, 34, 32, 4)
        cur_signs   := array.from(1, 1, 1, -1)
        cur_labels  := array.from('$9.85M', '$8.56M', '$7.95M', '$-1.00M')
    if year == 2026 and month == 1 and dayofmonth == 10
        plot_c_wall := 7.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(7.0, 6.5, 6.0, 5.5)
        cur_lengths := array.from(40, 18, 7, 2)
        cur_signs   := array.from(1, 1, 1, 1)
        cur_labels  := array.from('$9.44M', '$4.28M', '$1.83M', '$137K')
    [plot_c_wall, plot_p_wall, plot_flip, cur_strikes, cur_lengths, cur_signs, cur_labels]

// ===== BITO FUNCTION =====
f_symbol_BITO() =>
    var float plot_c_wall = na
    var float plot_p_wall = na
    var float plot_flip   = na
    var float[] cur_strikes = array.new_float()
    var int[]   cur_lengths = array.new_int()
    var int[]   cur_signs   = array.new_int()
    var string[] cur_labels = array.new_string()
    if year == 2025 and month == 12 and dayofmonth == 23
        plot_c_wall := 14.0
        plot_p_wall := 12.0
        plot_flip   := 17.5
        cur_strikes := array.from(14.0, 12.0, 10.0, 18.0, 20.0, 19.0, 50.0, 11.0, 16.0, 30.0, 25.0, 24.0, 17.0, 22.0, 15.0, 13.0, 28.0, 38.0, 27.0, 5.0, 3.0, 35.0, 40.0, 9.0, 21.0, 45.0, 23.0, 31.0, 36.0, 26.0, 49.0, 32.0, 42.0, 34.0, 33.0, 37.0, 7.0, 29.0, 43.0, 8.0)
        cur_lengths := array.from(40, 32, 24, 22, 17, 8, 5, 5, 5, 5, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, -1, -1, 1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, 1, 1, -1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, -1, -1, 1, 1, -1)
        cur_labels  := array.from('$998K', '$-817K', '$-601K', '$567K', '$438K', '$207K', '$-139K', '$-132K', '$130K', '$127K', '$94K', '$78K', '$70K', '$65K', '$61K', '$58K', '$50K', '$45K', '$32K', '$-32K', '$-28K', '$24K', '$20K', '$-19K', '$17K', '$14K', '$13K', '$12K', '$12K', '$10K', '$-10K', '$10K', '$9K', '$8K', '$8K', '$-7K', '$-7K', '$6K', '$5K', '$-4K')
    if year == 2025 and month == 12 and dayofmonth == 23
        plot_c_wall := 14.0
        plot_p_wall := 12.0
        plot_flip   := 17.5
        cur_strikes := array.from(14.0, 12.0, 10.0, 18.0, 20.0, 19.0, 50.0, 11.0, 16.0, 30.0, 25.0, 24.0, 17.0, 22.0, 15.0, 13.0, 28.0, 38.0, 27.0, 5.0, 3.0, 35.0, 40.0, 9.0, 21.0, 45.0, 23.0, 31.0, 36.0, 26.0, 49.0, 32.0, 42.0, 34.0, 33.0, 37.0, 7.0, 29.0, 43.0, 8.0)
        cur_lengths := array.from(40, 32, 24, 22, 17, 8, 5, 5, 5, 5, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, -1, -1, 1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, 1, 1, -1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, -1, -1, 1, 1, -1)
        cur_labels  := array.from('$998K', '$-817K', '$-601K', '$567K', '$438K', '$207K', '$-139K', '$-132K', '$130K', '$127K', '$94K', '$78K', '$70K', '$65K', '$61K', '$58K', '$50K', '$45K', '$32K', '$-32K', '$-28K', '$24K', '$20K', '$-19K', '$17K', '$14K', '$13K', '$12K', '$12K', '$10K', '$-10K', '$10K', '$9K', '$8K', '$8K', '$-7K', '$-7K', '$6K', '$5K', '$-4K')
    if year == 2025 and month == 12 and dayofmonth == 24
        plot_c_wall := 14.0
        plot_p_wall := 12.0
        plot_flip   := 17.5
        cur_strikes := array.from(14.0, 12.0, 10.0, 18.0, 20.0, 19.0, 50.0, 11.0, 16.0, 30.0, 25.0, 24.0, 17.0, 22.0, 15.0, 13.0, 28.0, 38.0, 27.0, 5.0, 3.0, 35.0, 40.0, 9.0, 21.0, 45.0, 23.0, 31.0, 36.0, 26.0, 49.0, 32.0, 42.0, 34.0, 33.0, 37.0, 7.0, 29.0, 43.0, 8.0)
        cur_lengths := array.from(40, 32, 24, 22, 17, 8, 5, 5, 5, 5, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, -1, -1, 1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, 1, 1, -1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, -1, -1, 1, 1, -1)
        cur_labels  := array.from('$998K', '$-817K', '$-601K', '$567K', '$438K', '$207K', '$-139K', '$-132K', '$130K', '$127K', '$94K', '$78K', '$70K', '$65K', '$61K', '$58K', '$50K', '$45K', '$32K', '$-32K', '$-28K', '$24K', '$20K', '$-19K', '$17K', '$14K', '$13K', '$12K', '$12K', '$10K', '$-10K', '$10K', '$9K', '$8K', '$8K', '$-7K', '$-7K', '$6K', '$5K', '$-4K')
    if year == 2025 and month == 12 and dayofmonth == 24
        plot_c_wall := 13.0
        plot_p_wall := 12.0
        plot_flip   := 12.75
        cur_strikes := array.from(13.0, 12.0, 14.0, 13.5, 12.5, 11.0, 14.5, 11.5)
        cur_lengths := array.from(40, 21, 21, 11, 6, 2, 2, 2)
        cur_signs   := array.from(1, -1, 1, 1, -1, -1, 1, -1)
        cur_labels  := array.from('$4.05M', '$-2.18M', '$2.14M', '$1.13M', '$-682K', '$-271K', '$91K', '$-89K')
    if year == 2025 and month == 12 and dayofmonth == 25
        plot_c_wall := 13.0
        plot_p_wall := 12.5
        plot_flip   := 12.75
        cur_strikes := array.from(13.0, 12.0, 13.5, 12.5, 11.5, 11.0, 10.5)
        cur_lengths := array.from(40, 7, 6, 5, 2, 2, 2)
        cur_signs   := array.from(1, -1, 1, -1, -1, -1, -1)
        cur_labels  := array.from('$4.79M', '$-871K', '$805K', '$-615K', '$-73K', '$-8K', '$-5K')
    if year == 2025 and month == 12 and dayofmonth == 26
        plot_c_wall := 13.0
        plot_p_wall := 12.5
        plot_flip   := 12.75
        cur_strikes := array.from(13.0, 12.0, 13.5, 12.5, 11.5, 11.0, 10.5)
        cur_lengths := array.from(40, 7, 6, 5, 2, 2, 2)
        cur_signs   := array.from(1, -1, 1, -1, -1, -1, -1)
        cur_labels  := array.from('$4.79M', '$-871K', '$805K', '$-615K', '$-73K', '$-8K', '$-5K')
    if year == 2025 and month == 12 and dayofmonth == 27
        plot_c_wall := 13.0
        plot_p_wall := 12.0
        plot_flip   := na
        cur_strikes := array.from(12.0, 13.0, 13.5, 11.0, 12.5, 11.5, 10.5)
        cur_lengths := array.from(40, 12, 5, 3, 2, 2, 2)
        cur_signs   := array.from(-1, 1, 1, -1, 1, -1, -1)
        cur_labels  := array.from('$-5.88M', '$1.83M', '$784K', '$-517K', '$79K', '$-53K', '$-9K')
    if year == 2025 and month == 12 and dayofmonth == 28
        plot_c_wall := 13.0
        plot_p_wall := 12.0
        plot_flip   := na
        cur_strikes := array.from(12.0, 13.0, 13.5, 11.0, 12.5, 11.5, 10.5)
        cur_lengths := array.from(40, 12, 5, 3, 2, 2, 2)
        cur_signs   := array.from(-1, 1, 1, -1, 1, -1, -1)
        cur_labels  := array.from('$-5.88M', '$1.83M', '$784K', '$-517K', '$79K', '$-53K', '$-9K')
    if year == 2025 and month == 12 and dayofmonth == 29
        plot_c_wall := 13.0
        plot_p_wall := 12.0
        plot_flip   := na
        cur_strikes := array.from(12.0, 13.0, 13.5, 11.0, 12.5, 11.5, 10.5)
        cur_lengths := array.from(40, 12, 5, 3, 2, 2, 2)
        cur_signs   := array.from(-1, 1, 1, -1, 1, -1, -1)
        cur_labels  := array.from('$-5.88M', '$1.83M', '$784K', '$-517K', '$79K', '$-53K', '$-9K')
    if year == 2025 and month == 12 and dayofmonth == 30
        plot_c_wall := 13.0
        plot_p_wall := 12.0
        plot_flip   := 10.75
        cur_strikes := array.from(12.0, 13.0, 13.5, 11.0, 12.5, 11.5, 10.5)
        cur_lengths := array.from(40, 18, 6, 3, 2, 2, 2)
        cur_signs   := array.from(-1, 1, 1, -1, 1, -1, 1)
        cur_labels  := array.from('$-4.76M', '$2.18M', '$797K', '$-420K', '$171K', '$-71K', '$9K')
    if year == 2025 and month == 12 and dayofmonth == 31
        plot_c_wall := 13.0
        plot_p_wall := 12.0
        plot_flip   := na
        cur_strikes := array.from(12.0, 13.0, 13.5, 11.0, 11.5, 12.5, 10.5)
        cur_lengths := array.from(40, 16, 6, 3, 2, 2, 2)
        cur_signs   := array.from(-1, 1, 1, -1, -1, 1, -1)
        cur_labels  := array.from('$-4.58M', '$1.88M', '$707K', '$-450K', '$-111K', '$24K', '$-1K')
    if year == 2026 and month == 1 and dayofmonth == 1
        plot_c_wall := 13.0
        plot_p_wall := 12.0
        plot_flip   := 13.25
        cur_strikes := array.from(12.0, 13.0, 12.5, 13.5, 11.5, 11.0, 10.5)
        cur_lengths := array.from(40, 27, 13, 9, 4, 3, 2)
        cur_signs   := array.from(-1, 1, 1, 1, -1, -1, -1)
        cur_labels  := array.from('$-3.67M', '$2.48M', '$1.25M', '$864K', '$-378K', '$-298K', '$-14K')
    if year == 2026 and month == 1 and dayofmonth == 2
        plot_c_wall := 13.0
        plot_p_wall := 12.0
        plot_flip   := na
        cur_strikes := array.from(12.0, 13.0, 12.5, 13.5, 11.5, 11.0, 10.5)
        cur_lengths := array.from(40, 23, 10, 8, 7, 3, 2)
        cur_signs   := array.from(-1, 1, 1, 1, -1, -1, -1)
        cur_labels  := array.from('$-3.95M', '$2.27M', '$994K', '$837K', '$-696K', '$-372K', '$-355')
    if year == 2026 and month == 1 and dayofmonth == 3
        plot_c_wall := 13.0
        plot_p_wall := 12.0
        plot_flip   := na
        cur_strikes := array.from(12.0, 13.0, 14.0, 13.5, 11.5, 11.0, 12.5)
        cur_lengths := array.from(40, 20, 11, 7, 5, 3, 3)
        cur_signs   := array.from(-1, 1, 1, 1, -1, -1, 1)
        cur_labels  := array.from('$-3.51M', '$1.83M', '$1.04M', '$668K', '$-477K', '$-343K', '$285K')
    if year == 2026 and month == 1 and dayofmonth == 4
        plot_c_wall := 13.0
        plot_p_wall := 12.0
        plot_flip   := 13.25
        cur_strikes := array.from(12.0, 13.0, 14.0, 13.5, 11.5, 11.0, 12.5)
        cur_lengths := array.from(40, 33, 17, 15, 5, 3, 2)
        cur_signs   := array.from(-1, 1, 1, 1, -1, -1, 1)
        cur_labels  := array.from('$-2.92M', '$2.42M', '$1.24M', '$1.12M', '$-379K', '$-221K', '$213K')
    if year == 2026 and month == 1 and dayofmonth == 5
        plot_c_wall := 13.0
        plot_p_wall := 12.0
        plot_flip   := 13.25
        cur_strikes := array.from(12.0, 13.0, 14.0, 13.5, 11.5, 11.0, 12.5)
        cur_lengths := array.from(40, 33, 17, 15, 5, 3, 2)
        cur_signs   := array.from(-1, 1, 1, 1, -1, -1, 1)
        cur_labels  := array.from('$-2.91M', '$2.42M', '$1.24M', '$1.12M', '$-378K', '$-221K', '$213K')
    if year == 2026 and month == 1 and dayofmonth == 6
        plot_c_wall := 13.0
        plot_p_wall := 12.0
        plot_flip   := 13.25
        cur_strikes := array.from(12.0, 13.0, 14.0, 13.5, 15.0, 11.5, 12.5, 14.5)
        cur_lengths := array.from(40, 34, 17, 15, 6, 5, 2, 2)
        cur_signs   := array.from(-1, 1, 1, 1, 1, -1, 1, 1)
        cur_labels  := array.from('$-3.05M', '$2.60M', '$1.34M', '$1.17M', '$523K', '$-397K', '$223K', '$16K')
    if year == 2026 and month == 1 and dayofmonth == 7
        plot_c_wall := 13.0
        plot_p_wall := 13.0
        plot_flip   := 13.25
        cur_strikes := array.from(14.0, 13.5, 12.0, 13.0, 11.5, 12.5, 11.0, 14.5)
        cur_lengths := array.from(40, 38, 24, 3, 3, 3, 2, 2)
        cur_signs   := array.from(1, 1, -1, -1, -1, 1, -1, 1)
        cur_labels  := array.from('$2.28M', '$2.20M', '$-1.41M', '$-189K', '$-182K', '$179K', '$-94K', '$23K')
    if year == 2026 and month == 1 and dayofmonth == 8
        plot_c_wall := 13.0
        plot_p_wall := 12.0
        plot_flip   := 13.25
        cur_strikes := array.from(12.0, 13.0, 13.5, 14.0, 12.5, 11.5, 11.0, 14.5)
        cur_lengths := array.from(40, 39, 38, 34, 9, 3, 2, 2)
        cur_signs   := array.from(-1, 1, 1, 1, -1, -1, -1, 1)
        cur_labels  := array.from('$-2.61M', '$2.60M', '$2.48M', '$2.24M', '$-648K', '$-202K', '$-142K', '$56K')
    if year == 2026 and month == 1 and dayofmonth == 9
        plot_c_wall := 13.0
        plot_p_wall := 12.0
        plot_flip   := 13.25
        cur_strikes := array.from(13.0, 12.0, 13.5, 14.0, 12.5, 11.5, 11.0, 14.5)
        cur_lengths := array.from(40, 30, 23, 22, 11, 2, 2, 2)
        cur_signs   := array.from(1, -1, 1, 1, -1, -1, -1, 1)
        cur_labels  := array.from('$3.69M', '$-2.82M', '$2.18M', '$2.06M', '$-1.05M', '$-235K', '$-192K', '$53K')
    if year == 2026 and month == 1 and dayofmonth == 10
        plot_c_wall := 13.0
        plot_p_wall := 12.0
        plot_flip   := 13.75
        cur_strikes := array.from(12.0, 13.0, 14.0, 13.5, 12.5, 11.0, 11.5)
        cur_lengths := array.from(40, 34, 25, 15, 5, 2, 2)
        cur_signs   := array.from(-1, 1, 1, 1, -1, -1, -1)
        cur_labels  := array.from('$-3.05M', '$2.61M', '$1.93M', '$1.19M', '$-441K', '$-217K', '$-216K')
    [plot_c_wall, plot_p_wall, plot_flip, cur_strikes, cur_lengths, cur_signs, cur_labels]

// ===== BMNU FUNCTION =====
f_symbol_BMNU() =>
    var float plot_c_wall = na
    var float plot_p_wall = na
    var float plot_flip   = na
    var float[] cur_strikes = array.new_float()
    var int[]   cur_lengths = array.new_int()
    var int[]   cur_signs   = array.new_int()
    var string[] cur_labels = array.new_string()
    if year == 2025 and month == 12 and dayofmonth == 23
        plot_c_wall := 11.0
        plot_p_wall := 8.0
        plot_flip   := 2.5
        cur_strikes := array.from(11.0, 13.0, 9.0, 10.0, 12.0, 7.0, 15.0, 6.0, 4.0, 8.0, 3.0, 5.0, 23.0, 21.0, 22.0, 20.0, 16.0, 14.0, 18.0, 17.0, 19.0, 24.0, 2.0)
        cur_lengths := array.from(40, 12, 12, 11, 10, 10, 4, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, 1, -1, 1, -1, -1, 1)
        cur_labels  := array.from('$466K', '$141K', '$140K', '$135K', '$125K', '$117K', '$47K', '$-38K', '$-6K', '$-4K', '$-3K', '$-2K', '$-914', '$-853', '$528', '$-365', '$-299', '$128', '$-121', '$99', '$-88', '$-85', '$0')
    if year == 2025 and month == 12 and dayofmonth == 23
        plot_c_wall := 11.0
        plot_p_wall := 8.0
        plot_flip   := 2.5
        cur_strikes := array.from(11.0, 13.0, 9.0, 10.0, 12.0, 7.0, 15.0, 6.0, 4.0, 8.0, 3.0, 5.0, 23.0, 21.0, 22.0, 20.0, 16.0, 14.0, 18.0, 17.0, 19.0, 24.0, 2.0)
        cur_lengths := array.from(40, 12, 12, 11, 10, 10, 4, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, 1, -1, 1, -1, -1, 1)
        cur_labels  := array.from('$466K', '$141K', '$140K', '$135K', '$125K', '$117K', '$47K', '$-38K', '$-6K', '$-4K', '$-3K', '$-2K', '$-914', '$-853', '$528', '$-365', '$-299', '$128', '$-121', '$99', '$-88', '$-85', '$0')
    if year == 2025 and month == 12 and dayofmonth == 24
        plot_c_wall := 11.0
        plot_p_wall := 8.0
        plot_flip   := 2.5
        cur_strikes := array.from(11.0, 13.0, 9.0, 10.0, 12.0, 7.0, 15.0, 6.0, 4.0, 8.0, 3.0, 5.0, 23.0, 21.0, 22.0, 20.0, 16.0, 14.0, 18.0, 17.0, 19.0, 24.0, 2.0)
        cur_lengths := array.from(40, 12, 12, 11, 10, 10, 4, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, 1, -1, 1, -1, -1, 1)
        cur_labels  := array.from('$466K', '$141K', '$140K', '$135K', '$125K', '$117K', '$47K', '$-38K', '$-6K', '$-4K', '$-3K', '$-2K', '$-914', '$-853', '$528', '$-365', '$-299', '$128', '$-121', '$99', '$-88', '$-85', '$0')
    if year == 2025 and month == 10 and dayofmonth == 13
        plot_c_wall := 31.0
        plot_p_wall := 30.0
        plot_flip   := na
        cur_strikes := array.from(30.0, 31.0, 29.0, 32.0, 28.0, 33.0, 34.0, 27.0, 35.0, 26.0, 36.0, 25.0)
        cur_lengths := array.from(40, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1, -1, -1, -1, -1, 1, -1, 1, -1)
        cur_labels  := array.from('$-609K', '$-85K', '$-25K', '$-11K', '$-29', '$-23', '$-0', '$-0', '$0', '$-0', '$0', '$-0')
    if year == 2025 and month == 10 and dayofmonth == 14
        plot_c_wall := 27.0
        plot_p_wall := 26.0
        plot_flip   := na
        cur_strikes := array.from(26.0, 27.0, 28.0, 25.0, 29.0, 24.0, 30.0, 23.0, 31.0, 22.0)
        cur_lengths := array.from(40, 13, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1, -1, -1, -1, -1, -1, -1)
        cur_labels  := array.from('$-151K', '$-50K', '$-780', '$-518', '$-0', '$-0', '$-0', '$-0', '$-0', '$-0')
    if year == 2025 and month == 10 and dayofmonth == 15
        plot_c_wall := 27.0
        plot_p_wall := 27.0
        plot_flip   := na
        cur_strikes := array.from(27.0, 28.0, 26.0, 29.0, 25.0, 30.0, 24.0, 31.0, 32.0, 23.0, 22.0)
        cur_lengths := array.from(40, 16, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1)
        cur_labels  := array.from('$-167K', '$-70K', '$-1K', '$-5', '$-0', '$-0', '$-0', '$-0', '$0', '$-0', '$-0')
    if year == 2025 and month == 10 and dayofmonth == 16
        plot_c_wall := 25.0
        plot_p_wall := 25.0
        plot_flip   := na
        cur_strikes := array.from(25.0, 24.0, 26.0, 23.0, 27.0, 28.0, 22.0, 29.0, 21.0, 20.0)
        cur_lengths := array.from(40, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1, -1, -1, -1, -1, -1, -1)
        cur_labels  := array.from('$-418K', '$-455', '$-6', '$-0', '$-0', '$-0', '$-0', '$-0', '$-0', '$-0')
    if year == 2025 and month == 10 and dayofmonth == 20
        plot_c_wall := 27.0
        plot_p_wall := 28.0
        plot_flip   := na
        cur_strikes := array.from(28.0, 25.0, 26.0, 30.0, 29.0, 24.0, 31.0, 23.0, 32.0, 22.0, 27.0)
        cur_lengths := array.from(40, 32, 25, 13, 13, 3, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1)
        cur_labels  := array.from('$-74K', '$-61K', '$-48K', '$-24K', '$-24K', '$-6K', '$-2K', '$-282', '$-168', '$-53', '$0')
    if year == 2025 and month == 10 and dayofmonth == 21
        plot_c_wall := 27.0
        plot_p_wall := 25.0
        plot_flip   := na
        cur_strikes := array.from(25.0, 26.0, 24.0, 27.0, 29.0, 28.0, 23.0, 22.0, 21.0, 30.0)
        cur_lengths := array.from(40, 13, 11, 4, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, 1, 1, 1, -1, -1, -1, 1)
        cur_labels  := array.from('$-183K', '$-60K', '$-52K', '$21K', '$10K', '$10K', '$-7K', '$-3K', '$-217', '$46')
    if year == 2025 and month == 10 and dayofmonth == 22
        plot_c_wall := 20.0
        plot_p_wall := 22.0
        plot_flip   := na
        cur_strikes := array.from(22.0, 21.0, 20.0, 23.0, 24.0, 25.0, 19.0, 18.0)
        cur_lengths := array.from(40, 31, 21, 5, 3, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1, -1, -1, -1, -1)
        cur_labels  := array.from('$-154K', '$-121K', '$-83K', '$-22K', '$-13K', '$-3K', '$-3K', '$-25')
    if year == 2025 and month == 10 and dayofmonth == 23
        plot_c_wall := 23.0
        plot_p_wall := 22.0
        plot_flip   := na
        cur_strikes := array.from(22.0, 21.0, 23.0, 24.0, 20.0, 25.0, 26.0, 19.0, 18.0)
        cur_lengths := array.from(40, 10, 7, 7, 4, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1, -1, -1, -1, -1, -1)
        cur_labels  := array.from('$-255K', '$-66K', '$-49K', '$-48K', '$-28K', '$-16K', '$-765', '$-586', '$-8')
    if year == 2025 and month == 10 and dayofmonth == 24
        plot_c_wall := 25.0
        plot_p_wall := 25.0
        plot_flip   := na
        cur_strikes := array.from(22.0, 24.0, 25.0, 23.0, 21.0, 26.0, 20.0, 27.0, 19.0)
        cur_lengths := array.from(40, 37, 25, 17, 4, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1, -1, -1, -1, 1, -1)
        cur_labels  := array.from('$-121K', '$-114K', '$-76K', '$-53K', '$-13K', '$-7K', '$-2K', '$1K', '$-15')
    if year == 2025 and month == 10 and dayofmonth == 27
        plot_c_wall := 27.0
        plot_p_wall := 25.0
        plot_flip   := 27.5
        cur_strikes := array.from(27.0, 25.0, 26.0, 29.0, 28.0, 24.0, 30.0, 23.0, 22.0, 31.0)
        cur_lengths := array.from(40, 23, 16, 14, 12, 3, 2, 2, 2, 2)
        cur_signs   := array.from(1, -1, -1, 1, 1, -1, 1, -1, -1, -1)
        cur_labels  := array.from('$159K', '$-94K', '$-66K', '$57K', '$49K', '$-14K', '$5K', '$-730', '$-159', '$-13')
    if year == 2025 and month == 10 and dayofmonth == 28
        plot_c_wall := 25.0
        plot_p_wall := 25.0
        plot_flip   := na
        cur_strikes := array.from(25.0, 27.0, 26.0, 24.0, 28.0, 23.0, 29.0, 22.0, 30.0, 21.0)
        cur_lengths := array.from(40, 13, 13, 9, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, 1, -1, -1, 1, -1, 1, -1, 1, -1)
        cur_labels  := array.from('$-189K', '$65K', '$-62K', '$-45K', '$10K', '$-9K', '$6K', '$-3K', '$237', '$-55')
    if year == 2025 and month == 10 and dayofmonth == 29
        plot_c_wall := 23.0
        plot_p_wall := 22.0
        plot_flip   := na
        cur_strikes := array.from(22.0, 23.0, 21.0, 24.0, 25.0, 20.0, 26.0, 27.0, 19.0)
        cur_lengths := array.from(40, 14, 8, 5, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1, -1, -1, -1, 1, -1)
        cur_labels  := array.from('$-252K', '$-89K', '$-52K', '$-37K', '$-17K', '$-8K', '$-620', '$78', '$-67')
    if year == 2025 and month == 10 and dayofmonth == 30
        plot_c_wall := 20.0
        plot_p_wall := 18.0
        plot_flip   := 15.5
        cur_strikes := array.from(18.0, 19.0, 17.0, 20.0, 16.0, 21.0, 15.0)
        cur_lengths := array.from(40, 26, 17, 10, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1, 1, -1, -1)
        cur_labels  := array.from('$-90K', '$-59K', '$-40K', '$-25K', '$1K', '$-495', '$-12')
    if year == 2025 and month == 10 and dayofmonth == 31
        plot_c_wall := 20.0
        plot_p_wall := 20.0
        plot_flip   := 16.5
        cur_strikes := array.from(20.0, 19.0, 21.0, 18.0, 22.0, 17.0, 23.0, 16.0)
        cur_lengths := array.from(40, 18, 8, 3, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1, -1, -1, -1, 1)
        cur_labels  := array.from('$-294K', '$-136K', '$-61K', '$-28K', '$-6K', '$-3K', '$-80', '$1')
    if year == 2025 and month == 11 and dayofmonth == 3
        plot_c_wall := 16.0
        plot_p_wall := 17.0
        plot_flip   := 15.5
        cur_strikes := array.from(17.0, 16.0, 15.0, 18.0, 19.0)
        cur_lengths := array.from(40, 4, 3, 2, 2)
        cur_signs   := array.from(-1, 1, -1, -1, -1)
        cur_labels  := array.from('$-266K', '$27K', '$-21K', '$-11K', '$-191')
    if year == 2025 and month == 11 and dayofmonth == 4
        plot_c_wall := 15.0
        plot_p_wall := 15.0
        plot_flip   := na
        cur_strikes := array.from(15.0, 16.0)
        cur_lengths := array.from(40, 2)
        cur_signs   := array.from(-1, -1)
        cur_labels  := array.from('$-18K', '$-16')
    if year == 2025 and month == 11 and dayofmonth == 5
        plot_c_wall := 15.0
        plot_p_wall := 15.0
        plot_flip   := na
        cur_strikes := array.from(15.0, 14.0, 16.0, 17.0, 13.0, 12.0)
        cur_lengths := array.from(40, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1, -1, -1)
        cur_labels  := array.from('$-348K', '$-9K', '$-7K', '$-1K', '$-92', '$-0')
    if year == 2025 and month == 11 and dayofmonth == 6
        plot_c_wall := 13.0
        plot_p_wall := 12.0
        plot_flip   := na
        cur_strikes := array.from(12.0, 13.0, 11.0, 14.0, 10.0)
        cur_lengths := array.from(40, 13, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1, -1)
        cur_labels  := array.from('$-41K', '$-14K', '$-153', '$-9', '$-0')
    if year == 2025 and month == 11 and dayofmonth == 7
        plot_c_wall := 14.0
        plot_p_wall := 13.0
        plot_flip   := na
        cur_strikes := array.from(13.0, 14.0, 15.0, 12.0, 16.0)
        cur_lengths := array.from(40, 13, 10, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1, 1)
        cur_labels  := array.from('$-71K', '$-25K', '$-19K', '$-254', '$1')
    if year == 2025 and month == 11 and dayofmonth == 10
        plot_c_wall := 15.0
        plot_p_wall := 15.0
        plot_flip   := na
        cur_strikes := array.from(15.0, 14.0, 13.0, 16.0, 17.0, 12.0)
        cur_lengths := array.from(40, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, 1, -1, -1)
        cur_labels  := array.from('$-161K', '$-11K', '$-810', '$106', '$-0', '$-0')
    if year == 2025 and month == 11 and dayofmonth == 11
        plot_c_wall := 14.0
        plot_p_wall := 13.0
        plot_flip   := na
        cur_strikes := array.from(13.0, 12.0, 14.0, 15.0, 11.0)
        cur_lengths := array.from(40, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1, -1)
        cur_labels  := array.from('$-273K', '$-2K', '$-1K', '$-62', '$-0')
    if year == 2025 and month == 11 and dayofmonth == 12
        plot_c_wall := 14.0
        plot_p_wall := 14.0
        plot_flip   := na
        cur_strikes := array.from(14.0, 13.0, 15.0, 16.0, 12.0)
        cur_lengths := array.from(40, 37, 20, 2, 2)
        cur_signs   := array.from(-1, -1, -1, 1, -1)
        cur_labels  := array.from('$-15K', '$-14K', '$-8K', '$0', '$-0')
    if year == 2025 and month == 11 and dayofmonth == 13
        plot_c_wall := 11.0
        plot_p_wall := 11.0
        plot_flip   := na
        cur_strikes := array.from(11.0, 12.0, 10.0, 13.0, 9.0)
        cur_lengths := array.from(40, 13, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1, -1)
        cur_labels  := array.from('$-23K', '$-8K', '$-20', '$-0', '$-0')
    if year == 2025 and month == 11 and dayofmonth == 14
        plot_c_wall := 10.0
        plot_p_wall := 10.0
        plot_flip   := na
        cur_strikes := array.from(10.0, 9.0, 11.0, 8.0)
        cur_lengths := array.from(40, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1)
        cur_labels  := array.from('$-239K', '$-172', '$-2', '$-0')
    if year == 2025 and month == 11 and dayofmonth == 17
        plot_c_wall := 9.0
        plot_p_wall := 8.0
        plot_flip   := 7.5
        cur_strikes := array.from(8.0, 9.0, 7.0)
        cur_lengths := array.from(40, 2, 2)
        cur_signs   := array.from(-1, -1, 1)
        cur_labels  := array.from('$-87K', '$-0', '$0')
    if year == 2025 and month == 11 and dayofmonth == 18
        plot_c_wall := 8.0
        plot_p_wall := 8.0
        plot_flip   := na
        cur_strikes := array.from(8.0, 9.0, 10.0, 7.0)
        cur_lengths := array.from(40, 7, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1)
        cur_labels  := array.from('$-1K', '$-207', '$-0', '$-0')
    if year == 2025 and month == 11 and dayofmonth == 19
        plot_c_wall := 7.0
        plot_p_wall := 7.0
        plot_flip   := na
        cur_strikes := array.from(7.0, 8.0, 6.0)
        cur_lengths := array.from(40, 2, 2)
        cur_signs   := array.from(-1, -1, -1)
        cur_labels  := array.from('$-76K', '$-0', '$-0')
    if year == 2025 and month == 11 and dayofmonth == 20
        plot_c_wall := 6.0
        plot_p_wall := 5.0
        plot_flip   := na
        cur_strikes := array.from(5.0, 6.0)
        cur_lengths := array.from(40, 2)
        cur_signs   := array.from(-1, -1)
        cur_labels  := array.from('$-0', '$-0')
    if year == 2025 and month == 11 and dayofmonth == 24
        plot_c_wall := 8.0
        plot_p_wall := 7.0
        plot_flip   := 6.5
        cur_strikes := array.from(7.0, 8.0, 6.0)
        cur_lengths := array.from(40, 26, 2)
        cur_signs   := array.from(-1, 1, 1)
        cur_labels  := array.from('$-31K', '$21K', '$1')
    if year == 2025 and month == 11 and dayofmonth == 25
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(6.0, 7.0)
        cur_lengths := array.from(40, 21)
        cur_signs   := array.from(-1, 1)
        cur_labels  := array.from('$-7K', '$4K')
    if year == 2025 and month == 11 and dayofmonth == 26
        plot_c_wall := 8.0
        plot_p_wall := 8.0
        plot_flip   := 7.5
        cur_strikes := array.from(8.0, 7.0, 9.0)
        cur_lengths := array.from(40, 2, 2)
        cur_signs   := array.from(1, -1, 1)
        cur_labels  := array.from('$1.62M', '$-5K', '$216')
    if year == 2025 and month == 11 and dayofmonth == 28
        plot_c_wall := 8.0
        plot_p_wall := 8.0
        plot_flip   := na
        cur_strikes := array.from(8.0, 9.0, 7.0)
        cur_lengths := array.from(40, 2, 2)
        cur_signs   := array.from(1, 1, 1)
        cur_labels  := array.from('$4.09M', '$50K', '$38')
    if year == 2025 and month == 12 and dayofmonth == 1
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(6.0, 7.0, 5.0)
        cur_lengths := array.from(40, 2, 2)
        cur_signs   := array.from(-1, -1, -1)
        cur_labels  := array.from('$-46K', '$-283', '$-0')
    if year == 2025 and month == 12 and dayofmonth == 2
        plot_c_wall := 8.0
        plot_p_wall := 7.0
        plot_flip   := 7.5
        cur_strikes := array.from(8.0, 7.0, 6.0)
        cur_lengths := array.from(40, 2, 2)
        cur_signs   := array.from(1, -1, -1)
        cur_labels  := array.from('$580K', '$-24K', '$-1')
    if year == 2025 and month == 12 and dayofmonth == 3
        plot_c_wall := 8.0
        plot_p_wall := 8.0
        plot_flip   := 7.5
        cur_strikes := array.from(8.0, 9.0, 7.0)
        cur_lengths := array.from(40, 2, 2)
        cur_signs   := array.from(1, 1, -1)
        cur_labels  := array.from('$7.28M', '$12K', '$-29')
    if year == 2025 and month == 12 and dayofmonth == 4
        plot_c_wall := 9.0
        plot_p_wall := 9.0
        plot_flip   := na
        cur_strikes := array.from(9.0, 10.0, 8.0, 11.0)
        cur_lengths := array.from(40, 22, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1)
        cur_labels  := array.from('$480K', '$269K', '$926', '$23')
    if year == 2025 and month == 12 and dayofmonth == 5
        plot_c_wall := 8.0
        plot_p_wall := 8.0
        plot_flip   := 7.5
        cur_strikes := array.from(8.0, 9.0, 7.0)
        cur_lengths := array.from(40, 2, 2)
        cur_signs   := array.from(1, 1, -1)
        cur_labels  := array.from('$5.44M', '$36K', '$-15')
    if year == 2025 and month == 12 and dayofmonth == 8
        plot_c_wall := 9.0
        plot_p_wall := 9.0
        plot_flip   := na
        cur_strikes := array.from(9.0, 10.0, 8.0)
        cur_lengths := array.from(40, 2, 2)
        cur_signs   := array.from(1, 1, 1)
        cur_labels  := array.from('$865K', '$11K', '$6K')
    if year == 2025 and month == 12 and dayofmonth == 9
        plot_c_wall := 11.0
        plot_p_wall := 11.0
        plot_flip   := na
        cur_strikes := array.from(11.0, 10.0, 12.0, 9.0)
        cur_lengths := array.from(40, 6, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1)
        cur_labels  := array.from('$1.19M', '$204K', '$3K', '$0')
    if year == 2025 and month == 12 and dayofmonth == 10
        plot_c_wall := 11.0
        plot_p_wall := 11.0
        plot_flip   := na
        cur_strikes := array.from(12.0, 11.0, 10.0, 13.0)
        cur_lengths := array.from(40, 39, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1)
        cur_labels  := array.from('$820K', '$803K', '$146', '$23')
    if year == 2025 and month == 12 and dayofmonth == 11
        plot_c_wall := 10.0
        plot_p_wall := 10.0
        plot_flip   := na
        cur_strikes := array.from(10.0, 11.0, 9.0, 12.0)
        cur_lengths := array.from(40, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1)
        cur_labels  := array.from('$3.36M', '$28K', '$6', '$0')
    if year == 2025 and month == 12 and dayofmonth == 12
        plot_c_wall := 8.0
        plot_p_wall := 8.0
        plot_flip   := 7.5
        cur_strikes := array.from(8.0, 9.0, 7.0)
        cur_lengths := array.from(40, 2, 2)
        cur_signs   := array.from(1, 1, -1)
        cur_labels  := array.from('$1.79M', '$3K', '$-0')
    if year == 2025 and month == 12 and dayofmonth == 15
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(6.0, 7.0)
        cur_lengths := array.from(40, 2)
        cur_signs   := array.from(-1, -1)
        cur_labels  := array.from('$-2K', '$-73')
    if year == 2025 and month == 12 and dayofmonth == 16
        plot_c_wall := 7.0
        plot_p_wall := 7.0
        plot_flip   := 6.5
        cur_strikes := array.from(7.0, 6.0)
        cur_lengths := array.from(40, 2)
        cur_signs   := array.from(1, -1)
        cur_labels  := array.from('$4K', '$-0')
    if year == 2025 and month == 12 and dayofmonth == 17
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(6.0, 5.0)
        cur_lengths := array.from(40, 2)
        cur_signs   := array.from(-1, -1)
        cur_labels  := array.from('$-8K', '$-0')
    if year == 2025 and month == 12 and dayofmonth == 18
        plot_c_wall := 5.0
        plot_p_wall := 5.0
        plot_flip   := na
        cur_strikes := array.from(5.0, 6.0)
        cur_lengths := array.from(40, 2)
        cur_signs   := array.from(-1, -1)
        cur_labels  := array.from('$-0', '$-0')
    if year == 2025 and month == 12 and dayofmonth == 22
        plot_c_wall := 7.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(6.0, 7.0)
        cur_lengths := array.from(40, 17)
        cur_signs   := array.from(-1, 1)
        cur_labels  := array.from('$-277K', '$125K')
    if year == 2025 and month == 12 and dayofmonth == 23
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(6.0, 5.0)
        cur_lengths := array.from(40, 2)
        cur_signs   := array.from(-1, -1)
        cur_labels  := array.from('$-1.13M', '$-1K')
    if year == 2025 and month == 12 and dayofmonth == 24
        plot_c_wall := 5.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(6.0, 5.0)
        cur_lengths := array.from(40, 2)
        cur_signs   := array.from(-1, -1)
        cur_labels  := array.from('$-38K', '$-2K')
    if year == 2025 and month == 12 and dayofmonth == 26
        plot_c_wall := 5.0
        plot_p_wall := 5.0
        plot_flip   := na
        cur_strikes := array.from(5.0, 6.0)
        cur_lengths := array.from(40, 2)
        cur_signs   := array.from(-1, -1)
        cur_labels  := array.from('$-1.02M', '$-5K')
    if year == 2025 and month == 12 and dayofmonth == 27
        plot_c_wall := 5.0
        plot_p_wall := 5.0
        plot_flip   := na
        cur_strikes := array.from(5.0)
        cur_lengths := array.from(40)
        cur_signs   := array.from(-1)
        cur_labels  := array.from('$-107K')
    if year == 2025 and month == 12 and dayofmonth == 28
        plot_c_wall := 5.0
        plot_p_wall := 5.0
        plot_flip   := na
        cur_strikes := array.from(5.0)
        cur_lengths := array.from(40)
        cur_signs   := array.from(-1)
        cur_labels  := array.from('$-107K')
    if year == 2025 and month == 12 and dayofmonth == 29
        plot_c_wall := 5.0
        plot_p_wall := 5.0
        plot_flip   := na
        cur_strikes := array.from(5.0)
        cur_lengths := array.from(40)
        cur_signs   := array.from(-1)
        cur_labels  := array.from('$-107K')
    if year == 2025 and month == 12 and dayofmonth == 30
        plot_c_wall := 5.0
        plot_p_wall := 5.0
        plot_flip   := na
        cur_strikes := array.from(5.0, 6.0)
        cur_lengths := array.from(40, 38)
        cur_signs   := array.from(-1, -1)
        cur_labels  := array.from('$-139K', '$-132K')
    if year == 2025 and month == 12 and dayofmonth == 31
        plot_c_wall := 5.0
        plot_p_wall := 5.0
        plot_flip   := na
        cur_strikes := array.from(5.0)
        cur_lengths := array.from(40)
        cur_signs   := array.from(-1)
        cur_labels  := array.from('$-137K')
    if year == 2026 and month == 1 and dayofmonth == 1
        plot_c_wall := 5.0
        plot_p_wall := 5.0
        plot_flip   := na
        cur_strikes := array.from(5.0)
        cur_lengths := array.from(40)
        cur_signs   := array.from(-1)
        cur_labels  := array.from('$-170K')
    if year == 2026 and month == 1 and dayofmonth == 2
        plot_c_wall := 5.0
        plot_p_wall := 5.0
        plot_flip   := na
        cur_strikes := array.from(5.0)
        cur_lengths := array.from(40)
        cur_signs   := array.from(-1)
        cur_labels  := array.from('$-185K')
    if year == 2026 and month == 1 and dayofmonth == 3
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(6.0)
        cur_lengths := array.from(40)
        cur_signs   := array.from(1)
        cur_labels  := array.from('$232K')
    if year == 2026 and month == 1 and dayofmonth == 4
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(6.0)
        cur_lengths := array.from(40)
        cur_signs   := array.from(1)
        cur_labels  := array.from('$235K')
    if year == 2026 and month == 1 and dayofmonth == 5
        plot_c_wall := 7.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(7.0, 6.0)
        cur_lengths := array.from(40, 30)
        cur_signs   := array.from(1, 1)
        cur_labels  := array.from('$314K', '$239K')
    if year == 2026 and month == 1 and dayofmonth == 6
        plot_c_wall := 7.0
        plot_p_wall := 8.0
        plot_flip   := na
        cur_strikes := array.from(7.0, 6.0, 8.0)
        cur_lengths := array.from(40, 31, 2)
        cur_signs   := array.from(1, 1, 1)
        cur_labels  := array.from('$360K', '$282K', '$24K')
    if year == 2026 and month == 1 and dayofmonth == 7
        plot_c_wall := 7.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(7.0, 6.0)
        cur_lengths := array.from(40, 23)
        cur_signs   := array.from(1, 1)
        cur_labels  := array.from('$356K', '$209K')
    if year == 2026 and month == 1 and dayofmonth == 8
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := 5.5
        cur_strikes := array.from(6.0, 5.0)
        cur_lengths := array.from(40, 24)
        cur_signs   := array.from(1, -1)
        cur_labels  := array.from('$239K', '$-144K')
    if year == 2026 and month == 1 and dayofmonth == 9
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(6.0)
        cur_lengths := array.from(40)
        cur_signs   := array.from(1)
        cur_labels  := array.from('$270K')
    if year == 2026 and month == 1 and dayofmonth == 10
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := 5.5
        cur_strikes := array.from(6.0, 5.0)
        cur_lengths := array.from(40, 21)
        cur_signs   := array.from(1, -1)
        cur_labels  := array.from('$406K', '$-216K')
    if year == 2026 and month == 1 and dayofmonth == 11
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := 5.5
        cur_strikes := array.from(6.0, 5.0)
        cur_lengths := array.from(40, 38)
        cur_signs   := array.from(1, -1)
        cur_labels  := array.from('$374K', '$-359K')
    [plot_c_wall, plot_p_wall, plot_flip, cur_strikes, cur_lengths, cur_signs, cur_labels]

// ===== CLF FUNCTION =====
f_symbol_CLF() =>
    var float plot_c_wall = na
    var float plot_p_wall = na
    var float plot_flip   = na
    var float[] cur_strikes = array.new_float()
    var int[]   cur_lengths = array.new_int()
    var int[]   cur_signs   = array.new_int()
    var string[] cur_labels = array.new_string()
    if year == 2025 and month == 12 and dayofmonth == 25
        plot_c_wall := 14.0
        plot_p_wall := 12.0
        plot_flip   := na
        cur_strikes := array.from(14.0, 13.5, 14.5, 13.0, 12.5, 15.0, 12.0, 15.5)
        cur_lengths := array.from(40, 28, 8, 8, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1, 1, 1, 1)
        cur_labels  := array.from('$6.94M', '$4.93M', '$1.55M', '$1.41M', '$176K', '$149K', '$89K', '$46K')
    if year == 2025 and month == 12 and dayofmonth == 26
        plot_c_wall := 14.0
        plot_p_wall := 12.0
        plot_flip   := na
        cur_strikes := array.from(14.0, 13.5, 14.5, 13.0, 12.5, 15.0, 12.0, 15.5)
        cur_lengths := array.from(40, 28, 8, 8, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1, 1, 1, 1)
        cur_labels  := array.from('$6.94M', '$4.93M', '$1.55M', '$1.41M', '$176K', '$149K', '$89K', '$46K')
    if year == 2025 and month == 12 and dayofmonth == 27
        plot_c_wall := 15.0
        plot_p_wall := 12.0
        plot_flip   := na
        cur_strikes := array.from(15.0, 12.0, 14.0, 13.0, 14.5, 13.5, 15.5, 12.5)
        cur_lengths := array.from(40, 19, 17, 11, 7, 6, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1, 1, 1, 1)
        cur_labels  := array.from('$10.43M', '$5.07M', '$4.53M', '$3.07M', '$2.04M', '$1.80M', '$558K', '$514K')
    [plot_c_wall, plot_p_wall, plot_flip, cur_strikes, cur_lengths, cur_signs, cur_labels]

// ===== MSTU FUNCTION =====
f_symbol_MSTU() =>
    var float plot_c_wall = na
    var float plot_p_wall = na
    var float plot_flip   = na
    var float[] cur_strikes = array.new_float()
    var int[]   cur_lengths = array.new_int()
    var int[]   cur_signs   = array.new_int()
    var string[] cur_labels = array.new_string()
    if year == 2025 and month == 12 and dayofmonth == 24
        plot_c_wall := 10.0
        plot_p_wall := 8.5
        plot_flip   := na
        cur_strikes := array.from(8.5, 9.5, 9.0, 10.0, 8.0)
        cur_lengths := array.from(40, 36, 8, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1, -1)
        cur_labels  := array.from('$-382K', '$-352K', '$-84K', '$-26K', '$-15K')
    if year == 2025 and month == 12 and dayofmonth == 25
        plot_c_wall := 10.0
        plot_p_wall := 8.5
        plot_flip   := na
        cur_strikes := array.from(8.5, 10.0, 9.5, 9.0, 10.5, 8.0)
        cur_lengths := array.from(40, 26, 22, 9, 4, 2)
        cur_signs   := array.from(-1, 1, -1, -1, 1, -1)
        cur_labels  := array.from('$-842K', '$565K', '$-471K', '$-209K', '$92K', '$-43K')
    if year == 2025 and month == 12 and dayofmonth == 26
        plot_c_wall := 10.0
        plot_p_wall := 8.5
        plot_flip   := na
        cur_strikes := array.from(8.5, 10.0, 9.5, 9.0, 10.5, 8.0)
        cur_lengths := array.from(40, 26, 22, 9, 4, 2)
        cur_signs   := array.from(-1, 1, -1, -1, 1, -1)
        cur_labels  := array.from('$-842K', '$565K', '$-471K', '$-209K', '$92K', '$-43K')
    if year == 2025 and month == 12 and dayofmonth == 27
        plot_c_wall := 9.0
        plot_p_wall := 9.0
        plot_flip   := na
        cur_strikes := array.from(10.0, 9.0, 9.5, 8.5, 8.0)
        cur_lengths := array.from(40, 39, 8, 2, 2)
        cur_signs   := array.from(1, 1, -1, 1, 1)
        cur_labels  := array.from('$125K', '$123K', '$-27K', '$5K', '$2K')
    if year == 2025 and month == 12 and dayofmonth == 28
        plot_c_wall := 9.0
        plot_p_wall := 9.0
        plot_flip   := na
        cur_strikes := array.from(10.0, 9.0, 9.5, 8.5, 8.0)
        cur_lengths := array.from(40, 39, 8, 2, 2)
        cur_signs   := array.from(1, 1, -1, 1, 1)
        cur_labels  := array.from('$125K', '$123K', '$-27K', '$5K', '$2K')
    if year == 2025 and month == 12 and dayofmonth == 29
        plot_c_wall := 9.0
        plot_p_wall := 9.0
        plot_flip   := na
        cur_strikes := array.from(10.0, 9.0, 9.5, 8.5, 8.0)
        cur_lengths := array.from(40, 39, 8, 2, 2)
        cur_signs   := array.from(1, 1, -1, 1, 1)
        cur_labels  := array.from('$125K', '$123K', '$-27K', '$5K', '$2K')
    if year == 2025 and month == 12 and dayofmonth == 30
        plot_c_wall := 10.0
        plot_p_wall := 9.0
        plot_flip   := 8.75
        cur_strikes := array.from(10.0, 9.0, 8.5, 9.5, 8.0)
        cur_lengths := array.from(40, 21, 5, 2, 2)
        cur_signs   := array.from(1, -1, 1, 1, 1)
        cur_labels  := array.from('$90K', '$-47K', '$12K', '$6K', '$5K')
    if year == 2025 and month == 12 and dayofmonth == 31
        plot_c_wall := 10.0
        plot_p_wall := 9.0
        plot_flip   := 7.75
        cur_strikes := array.from(10.0, 9.0, 8.0, 8.5, 9.5, 7.5)
        cur_lengths := array.from(40, 17, 11, 11, 4, 2)
        cur_signs   := array.from(1, 1, -1, -1, 1, 1)
        cur_labels  := array.from('$278K', '$122K', '$-82K', '$-81K', '$29K', '$0')
    if year == 2026 and month == 1 and dayofmonth == 1
        plot_c_wall := 10.0
        plot_p_wall := 8.5
        plot_flip   := 2.5
        cur_strikes := array.from(8.5, 8.0, 9.0, 10.0, 9.5, 11.0, 13.0, 10.5, 11.5, 12.0, 7.0, 15.5, 14.0, 6.0, 12.5, 14.5, 13.5, 16.0, 20.0, 15.0, 17.0, 4.0, 5.0, 3.0, 16.5, 17.5, 18.0, 1.0, 2.0, 19.0)
        cur_lengths := array.from(40, 24, 21, 12, 9, 7, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, -1, 1, -1, 1, 1, 1, 1, 1, 1)
        cur_labels  := array.from('$-286K', '$-176K', '$-152K', '$92K', '$65K', '$55K', '$26K', '$22K', '$20K', '$19K', '$-4K', '$2K', '$1K', '$-999', '$991', '$783', '$720', '$569', '$402', '$373', '$354', '$-196', '$71', '$-42', '$36', '$29', '$26', '$0', '$0', '$0')
    if year == 2026 and month == 1 and dayofmonth == 2
        plot_c_wall := 9.0
        plot_p_wall := 8.5
        plot_flip   := na
        cur_strikes := array.from(8.5, 8.0, 9.0, 9.5, 7.5)
        cur_lengths := array.from(40, 34, 18, 11, 2)
        cur_signs   := array.from(-1, -1, 1, 1, -1)
        cur_labels  := array.from('$-617K', '$-527K', '$283K', '$177K', '$-703')
    if year == 2026 and month == 1 and dayofmonth == 3
        plot_c_wall := 9.0
        plot_p_wall := 9.0
        plot_flip   := 8.75
        cur_strikes := array.from(10.0, 9.0, 8.0, 8.5, 9.5)
        cur_lengths := array.from(40, 33, 7, 3, 2)
        cur_signs   := array.from(1, 1, -1, -1, 1)
        cur_labels  := array.from('$254K', '$210K', '$-51K', '$-22K', '$12K')
    if year == 2026 and month == 1 and dayofmonth == 4
        plot_c_wall := 10.0
        plot_p_wall := 8.0
        plot_flip   := na
        cur_strikes := array.from(10.0, 8.0, 8.5, 9.5, 9.0)
        cur_lengths := array.from(40, 32, 12, 6, 3)
        cur_signs   := array.from(1, -1, -1, -1, -1)
        cur_labels  := array.from('$83K', '$-67K', '$-26K', '$-13K', '$-7K')
    if year == 2026 and month == 1 and dayofmonth == 5
        plot_c_wall := 10.0
        plot_p_wall := 8.0
        plot_flip   := na
        cur_strikes := array.from(10.0, 8.0, 8.5, 9.5, 9.0)
        cur_lengths := array.from(40, 32, 12, 6, 3)
        cur_signs   := array.from(1, -1, -1, -1, -1)
        cur_labels  := array.from('$83K', '$-67K', '$-26K', '$-13K', '$-7K')
    if year == 2026 and month == 1 and dayofmonth == 6
        plot_c_wall := 10.0
        plot_p_wall := 9.0
        plot_flip   := 9.75
        cur_strikes := array.from(10.0, 8.5, 10.5, 11.0, 9.5, 9.0)
        cur_lengths := array.from(40, 12, 10, 7, 6, 3)
        cur_signs   := array.from(1, -1, 1, 1, -1, -1)
        cur_labels  := array.from('$91K', '$-29K', '$25K', '$17K', '$-14K', '$-7K')
    if year == 2026 and month == 1 and dayofmonth == 7
        plot_c_wall := 10.0
        plot_p_wall := 9.0
        plot_flip   := 8.75
        cur_strikes := array.from(10.0, 9.0, 8.0, 8.5, 9.5)
        cur_lengths := array.from(40, 24, 6, 2, 2)
        cur_signs   := array.from(1, 1, -1, -1, -1)
        cur_labels  := array.from('$409K', '$249K', '$-65K', '$-17K', '$-6K')
    if year == 2026 and month == 1 and dayofmonth == 8
        plot_c_wall := 10.0
        plot_p_wall := 8.5
        plot_flip   := na
        cur_strikes := array.from(8.5, 10.0, 10.5, 9.0, 8.0, 9.5)
        cur_lengths := array.from(40, 38, 18, 13, 5, 4)
        cur_signs   := array.from(-1, 1, 1, -1, -1, -1)
        cur_labels  := array.from('$-388K', '$378K', '$182K', '$-129K', '$-57K', '$-44K')
    if year == 2026 and month == 1 and dayofmonth == 9
        plot_c_wall := 10.0
        plot_p_wall := 8.5
        plot_flip   := na
        cur_strikes := array.from(8.5, 10.0, 9.0, 10.5, 11.0, 9.5)
        cur_lengths := array.from(40, 14, 12, 7, 6, 2)
        cur_signs   := array.from(-1, 1, -1, 1, 1, -1)
        cur_labels  := array.from('$-706K', '$252K', '$-227K', '$128K', '$107K', '$-18K')
    [plot_c_wall, plot_p_wall, plot_flip, cur_strikes, cur_lengths, cur_signs, cur_labels]

// ===== NOK FUNCTION =====
f_symbol_NOK() =>
    var float plot_c_wall = na
    var float plot_p_wall = na
    var float plot_flip   = na
    var float[] cur_strikes = array.new_float()
    var int[]   cur_lengths = array.new_int()
    var int[]   cur_signs   = array.new_int()
    var string[] cur_labels = array.new_string()
    if year == 2025 and month == 12 and dayofmonth == 29
        plot_c_wall := 7.0
        plot_p_wall := 7.0
        plot_flip   := na
        cur_strikes := array.from(7.0, 6.5, 6.0, 7.5)
        cur_lengths := array.from(40, 15, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1)
        cur_labels  := array.from('$21.15M', '$8.09M', '$474K', '$130K')
    if year == 2025 and month == 12 and dayofmonth == 30
        plot_c_wall := 7.0
        plot_p_wall := 7.0
        plot_flip   := na
        cur_strikes := array.from(7.0, 6.5, 6.0, 7.5)
        cur_lengths := array.from(40, 11, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1)
        cur_labels  := array.from('$22.61M', '$6.56M', '$1.18M', '$154K')
    if year == 2025 and month == 12 and dayofmonth == 31
        plot_c_wall := 7.0
        plot_p_wall := 7.0
        plot_flip   := na
        cur_strikes := array.from(7.0, 6.5, 6.0)
        cur_lengths := array.from(40, 18, 2)
        cur_signs   := array.from(1, 1, 1)
        cur_labels  := array.from('$21.32M', '$9.63M', '$1.01M')
    if year == 2026 and month == 1 and dayofmonth == 1
        plot_c_wall := 7.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(7.0, 6.5, 6.0)
        cur_lengths := array.from(40, 18, 3)
        cur_signs   := array.from(1, 1, 1)
        cur_labels  := array.from('$18.57M', '$8.71M', '$1.70M')
    if year == 2026 and month == 1 and dayofmonth == 2
        plot_c_wall := 7.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(7.0, 6.5, 6.0, 5.5)
        cur_lengths := array.from(40, 21, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1)
        cur_labels  := array.from('$17.24M', '$9.23M', '$608K', '$315K')
    if year == 2026 and month == 1 and dayofmonth == 3
        plot_c_wall := 7.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(7.0, 6.5, 6.0)
        cur_lengths := array.from(40, 16, 2)
        cur_signs   := array.from(1, 1, 1)
        cur_labels  := array.from('$16.89M', '$7.12M', '$661K')
    if year == 2026 and month == 1 and dayofmonth == 4
        plot_c_wall := 7.0
        plot_p_wall := 7.0
        plot_flip   := 6.25
        cur_strikes := array.from(7.0, 6.5, 6.0)
        cur_lengths := array.from(40, 19, 3)
        cur_signs   := array.from(1, 1, -1)
        cur_labels  := array.from('$18.33M', '$9.14M', '$-1.63M')
    if year == 2026 and month == 1 and dayofmonth == 5
        plot_c_wall := 7.0
        plot_p_wall := 7.0
        plot_flip   := 6.25
        cur_strikes := array.from(7.0, 6.5, 6.0)
        cur_lengths := array.from(40, 19, 3)
        cur_signs   := array.from(1, 1, -1)
        cur_labels  := array.from('$18.34M', '$9.14M', '$-1.63M')
    if year == 2026 and month == 1 and dayofmonth == 6
        plot_c_wall := 7.0
        plot_p_wall := 6.0
        plot_flip   := 6.25
        cur_strikes := array.from(7.0, 6.5, 6.0)
        cur_lengths := array.from(40, 18, 4)
        cur_signs   := array.from(1, 1, -1)
        cur_labels  := array.from('$19.61M', '$9.13M', '$-2.11M')
    if year == 2026 and month == 1 and dayofmonth == 7
        plot_c_wall := 7.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(7.0, 6.5, 6.0, 5.5)
        cur_lengths := array.from(40, 18, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1)
        cur_labels  := array.from('$18.58M', '$8.68M', '$279K', '$138K')
    if year == 2026 and month == 1 and dayofmonth == 8
        plot_c_wall := 7.0
        plot_p_wall := 6.5
        plot_flip   := 6.25
        cur_strikes := array.from(7.0, 6.5, 7.5, 6.0)
        cur_lengths := array.from(40, 24, 2, 2)
        cur_signs   := array.from(1, 1, 1, -1)
        cur_labels  := array.from('$20.17M', '$12.30M', '$268K', '$-41K')
    if year == 2026 and month == 1 and dayofmonth == 9
        plot_c_wall := 7.0
        plot_p_wall := 6.5
        plot_flip   := na
        cur_strikes := array.from(7.0, 6.5, 6.0)
        cur_lengths := array.from(40, 3, 2)
        cur_signs   := array.from(1, 1, 1)
        cur_labels  := array.from('$21.31M', '$1.89M', '$323K')
    if year == 2026 and month == 1 and dayofmonth == 10
        plot_c_wall := 7.0
        plot_p_wall := 6.5
        plot_flip   := 6.75
        cur_strikes := array.from(7.0, 6.5, 6.0)
        cur_lengths := array.from(40, 4, 4)
        cur_signs   := array.from(1, -1, -1)
        cur_labels  := array.from('$19.45M', '$-2.17M', '$-2.05M')
    [plot_c_wall, plot_p_wall, plot_flip, cur_strikes, cur_lengths, cur_signs, cur_labels]

// ===== OPEN FUNCTION =====
f_symbol_OPEN() =>
    var float plot_c_wall = na
    var float plot_p_wall = na
    var float plot_flip   = na
    var float[] cur_strikes = array.new_float()
    var int[]   cur_lengths = array.new_int()
    var int[]   cur_signs   = array.new_int()
    var string[] cur_labels = array.new_string()
    if year == 2025 and month == 12 and dayofmonth == 23
        plot_c_wall := 0.5
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(6.0, 7.0, 5.0, 4.5, 5.5, 8.0, 3.5, 2.5, 4.0, 1.5, 9.0, 10.0, 16.0, 3.0, 0.5, 14.0, 12.0, 11.0, 2.0, 1.0, 6.5, 13.0, 8.5, 15.0, 17.0, 18.0, 19.0, 20.0, 21.0)
        cur_lengths := array.from(40, 34, 24, 22, 16, 4, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1)
        cur_labels  := array.from('$-868K', '$-745K', '$-531K', '$-488K', '$-348K', '$-106K', '$-67K', '$-58K', '$-51K', '$-33K', '$-25K', '$-15K', '$-7K', '$-7K', '$-5K', '$-3K', '$-1K', '$-629', '$-70', '$-46', '$0', '$0', '$0', '$0', '$0', '$0', '$0', '$0', '$0')
    if year == 2025 and month == 12 and dayofmonth == 23
        plot_c_wall := 7.0
        plot_p_wall := 6.0
        plot_flip   := 1.25
        cur_strikes := array.from(9.0, 7.0, 21.0, 8.0, 5.5, 6.0, 10.0, 5.0, 20.0, 11.0, 4.5, 18.0, 12.0, 2.5, 4.0, 1.5, 3.5, 15.0, 17.0, 19.0, 14.0, 3.0, 13.0, 0.5, 16.0, 2.0, 1.0, 6.5, 8.5)
        cur_lengths := array.from(40, 34, 32, 26, 18, 17, 16, 13, 8, 8, 8, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1, -1, 1, -1, 1, 1, -1, 1, 1, -1, -1, 1, -1, 1, 1, 1, 1, -1, 1, -1, -1, -1, -1, 1, 1)
        cur_labels  := array.from('$1.55M', '$1.33M', '$1.26M', '$1.05M', '$716K', '$-675K', '$628K', '$-531K', '$349K', '$330K', '$-313K', '$134K', '$79K', '$-58K', '$-48K', '$44K', '$-40K', '$33K', '$29K', '$15K', '$12K', '$-7K', '$6K', '$-3K', '$-781', '$-70', '$-39', '$0', '$0')
    if year == 2025 and month == 12 and dayofmonth == 24
        plot_c_wall := 7.0
        plot_p_wall := 6.0
        plot_flip   := 1.25
        cur_strikes := array.from(9.0, 7.0, 21.0, 8.0, 5.5, 6.0, 10.0, 5.0, 20.0, 11.0, 4.5, 18.0, 12.0, 2.5, 4.0, 1.5, 3.5, 15.0, 17.0, 19.0, 14.0, 3.0, 13.0, 0.5, 16.0, 2.0, 1.0, 6.5, 8.5)
        cur_lengths := array.from(40, 34, 32, 26, 18, 17, 16, 13, 8, 8, 8, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1, -1, 1, -1, 1, 1, -1, 1, 1, -1, -1, 1, -1, 1, 1, 1, 1, -1, 1, -1, -1, -1, -1, 1, 1)
        cur_labels  := array.from('$1.55M', '$1.33M', '$1.26M', '$1.05M', '$716K', '$-675K', '$628K', '$-531K', '$349K', '$330K', '$-313K', '$134K', '$79K', '$-58K', '$-48K', '$44K', '$-40K', '$33K', '$29K', '$15K', '$12K', '$-7K', '$6K', '$-3K', '$-781', '$-70', '$-39', '$0', '$0')
    if year == 2025 and month == 12 and dayofmonth == 24
        plot_c_wall := 7.0
        plot_p_wall := 6.0
        plot_flip   := 5.75
        cur_strikes := array.from(7.0, 6.5, 6.0, 5.5)
        cur_lengths := array.from(40, 28, 10, 2)
        cur_signs   := array.from(1, 1, -1, 1)
        cur_labels  := array.from('$9.84M', '$6.98M', '$-2.62M', '$137K')
    if year == 2025 and month == 12 and dayofmonth == 25
        plot_c_wall := 6.5
        plot_p_wall := 6.0
        plot_flip   := 6.25
        cur_strikes := array.from(6.5, 7.0, 6.0, 5.5)
        cur_lengths := array.from(40, 33, 17, 2)
        cur_signs   := array.from(1, 1, -1, -1)
        cur_labels  := array.from('$6.82M', '$5.79M', '$-2.95M', '$-317K')
    if year == 2025 and month == 12 and dayofmonth == 26
        plot_c_wall := 6.5
        plot_p_wall := 6.0
        plot_flip   := 6.25
        cur_strikes := array.from(6.5, 7.0, 6.0, 5.5)
        cur_lengths := array.from(40, 33, 17, 2)
        cur_signs   := array.from(1, 1, -1, -1)
        cur_labels  := array.from('$6.82M', '$5.79M', '$-2.95M', '$-317K')
    if year == 2025 and month == 12 and dayofmonth == 27
        plot_c_wall := 6.5
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(6.0, 6.5, 5.5)
        cur_lengths := array.from(40, 14, 12)
        cur_signs   := array.from(-1, 1, -1)
        cur_labels  := array.from('$-1.57M', '$554K', '$-496K')
    [plot_c_wall, plot_p_wall, plot_flip, cur_strikes, cur_lengths, cur_signs, cur_labels]

// ===== QQQ FUNCTION =====
f_symbol_QQQ() =>
    var float plot_c_wall = na
    var float plot_p_wall = na
    var float plot_flip   = na
    var float[] cur_strikes = array.new_float()
    var int[]   cur_lengths = array.new_int()
    var int[]   cur_signs   = array.new_int()
    var string[] cur_labels = array.new_string()
    if year == 2025 and month == 12 and dayofmonth == 23
        plot_c_wall := 630.0
        plot_p_wall := 600.0
        plot_flip   := 467.28
        cur_strikes := array.from(600.0, 640.0, 630.0, 650.0, 620.0, 590.0, 580.0, 635.0, 625.0, 610.0, 570.0, 655.0, 560.0, 550.0, 645.0, 615.0, 584.78, 574.78, 604.78, 670.0, 660.0, 594.78, 665.0, 675.0, 510.0, 609.78, 589.78, 544.78, 680.0, 540.0, 569.78, 530.0, 579.78, 690.0, 514.78, 520.0, 549.78, 564.78, 480.0, 554.78)
        cur_lengths := array.from(40, 39, 36, 34, 29, 28, 23, 23, 20, 16, 14, 13, 11, 8, 7, 7, 6, 4, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, 1, 1, 1, 1, -1, -1, 1, 1, -1, -1, 1, -1, -1, 1, -1, -1, -1, -1, 1, 1, -1, 1, 1, -1, -1, -1, -1, 1, -1, -1, -1, -1, 1, -1, -1, -1, -1, 1, -1)
        cur_labels  := array.from('$-21.81M', '$21.54M', '$19.92M', '$18.81M', '$15.90M', '$-15.44M', '$-13.03M', '$12.89M', '$11.13M', '$-9.22M', '$-7.74M', '$7.27M', '$-6.18M', '$-4.68M', '$4.28M', '$-3.96M', '$-3.69M', '$-2.52M', '$-2.17M', '$1.99M', '$1.97M', '$-1.85M', '$1.80M', '$1.52M', '$-1.18M', '$-1.11M', '$-1.08M', '$-1.01M', '$907K', '$-868K', '$-647K', '$-638K', '$-585K', '$502K', '$-474K', '$-469K', '$-440K', '$-401K', '$390K', '$-382K')
    if year == 2025 and month == 12 and dayofmonth == 23
        plot_c_wall := 630.0
        plot_p_wall := 600.0
        plot_flip   := 467.28
        cur_strikes := array.from(600.0, 640.0, 630.0, 650.0, 620.0, 590.0, 580.0, 635.0, 625.0, 610.0, 570.0, 655.0, 560.0, 550.0, 645.0, 615.0, 584.78, 574.78, 604.78, 670.0, 660.0, 594.78, 665.0, 675.0, 510.0, 609.78, 589.78, 544.78, 680.0, 540.0, 569.78, 530.0, 579.78, 690.0, 514.78, 520.0, 549.78, 564.78, 480.0, 554.78)
        cur_lengths := array.from(40, 39, 36, 34, 29, 28, 23, 23, 20, 16, 14, 13, 11, 8, 7, 7, 6, 4, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, 1, 1, 1, 1, -1, -1, 1, 1, -1, -1, 1, -1, -1, 1, -1, -1, -1, -1, 1, 1, -1, 1, 1, -1, -1, -1, -1, 1, -1, -1, -1, -1, 1, -1, -1, -1, -1, 1, -1)
        cur_labels  := array.from('$-21.81M', '$21.54M', '$19.92M', '$18.81M', '$15.90M', '$-15.44M', '$-13.03M', '$12.89M', '$11.13M', '$-9.22M', '$-7.74M', '$7.27M', '$-6.18M', '$-4.68M', '$4.28M', '$-3.96M', '$-3.69M', '$-2.52M', '$-2.17M', '$1.99M', '$1.97M', '$-1.85M', '$1.80M', '$1.52M', '$-1.18M', '$-1.11M', '$-1.08M', '$-1.01M', '$907K', '$-868K', '$-647K', '$-638K', '$-585K', '$502K', '$-474K', '$-469K', '$-440K', '$-401K', '$390K', '$-382K')
    if year == 2025 and month == 12 and dayofmonth == 24
        plot_c_wall := 630.0
        plot_p_wall := 600.0
        plot_flip   := 467.28
        cur_strikes := array.from(600.0, 640.0, 630.0, 650.0, 620.0, 590.0, 580.0, 635.0, 625.0, 610.0, 570.0, 655.0, 560.0, 550.0, 645.0, 615.0, 584.78, 574.78, 604.78, 670.0, 660.0, 594.78, 665.0, 675.0, 510.0, 609.78, 589.78, 544.78, 680.0, 540.0, 569.78, 530.0, 579.78, 690.0, 514.78, 520.0, 549.78, 564.78, 480.0, 554.78)
        cur_lengths := array.from(40, 39, 36, 34, 29, 28, 23, 23, 20, 16, 14, 13, 11, 8, 7, 7, 6, 4, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, 1, 1, 1, 1, -1, -1, 1, 1, -1, -1, 1, -1, -1, 1, -1, -1, -1, -1, 1, 1, -1, 1, 1, -1, -1, -1, -1, 1, -1, -1, -1, -1, 1, -1, -1, -1, -1, 1, -1)
        cur_labels  := array.from('$-21.81M', '$21.54M', '$19.92M', '$18.81M', '$15.90M', '$-15.44M', '$-13.03M', '$12.89M', '$11.13M', '$-9.22M', '$-7.74M', '$7.27M', '$-6.18M', '$-4.68M', '$4.28M', '$-3.96M', '$-3.69M', '$-2.52M', '$-2.17M', '$1.99M', '$1.97M', '$-1.85M', '$1.80M', '$1.52M', '$-1.18M', '$-1.11M', '$-1.08M', '$-1.01M', '$907K', '$-868K', '$-647K', '$-638K', '$-585K', '$502K', '$-474K', '$-469K', '$-440K', '$-401K', '$390K', '$-382K')
    if year == 2025 and month == 12 and dayofmonth == 24
        plot_c_wall := 625.0
        plot_p_wall := 620.0
        plot_flip   := 562.5
        cur_strikes := array.from(625.0, 620.0, 623.0, 617.0, 630.0, 622.0, 618.0, 624.0, 615.0, 613.0, 600.0, 621.0, 628.0, 627.0, 619.0, 616.0, 607.0, 626.0, 611.0, 635.0, 605.0, 606.0, 609.0, 610.0, 595.0, 603.0, 632.0, 608.0, 590.0, 631.0, 629.0, 602.0, 612.0, 633.0, 637.0, 575.0, 604.0, 599.0, 601.0, 640.0)
        cur_lengths := array.from(40, 15, 13, 11, 8, 8, 6, 6, 6, 6, 6, 6, 5, 5, 4, 4, 4, 4, 4, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, 1, 1, 1, 1, 1, -1, 1, -1, 1, -1, -1, -1, -1, -1, 1, 1, 1, -1, 1, 1, -1, 1, 1, 1, -1, -1, -1, -1, 1)
        cur_labels  := array.from('$42.76M', '$16.90M', '$14.54M', '$12.14M', '$8.84M', '$8.78M', '$7.34M', '$7.07M', '$7.05M', '$-6.99M', '$-6.85M', '$6.80M', '$6.32M', '$5.87M', '$5.00M', '$4.95M', '$-4.76M', '$4.50M', '$-4.44M', '$4.21M', '$-3.42M', '$-3.15M', '$-3.04M', '$-2.82M', '$-2.72M', '$2.56M', '$2.47M', '$2.45M', '$-2.20M', '$2.05M', '$1.47M', '$-1.29M', '$1.14M', '$1.05M', '$910K', '$-847K', '$-800K', '$-739K', '$-735K', '$624K')
    [plot_c_wall, plot_p_wall, plot_flip, cur_strikes, cur_lengths, cur_signs, cur_labels]

// ===== RR FUNCTION =====
f_symbol_RR() =>
    var float plot_c_wall = na
    var float plot_p_wall = na
    var float plot_flip   = na
    var float[] cur_strikes = array.new_float()
    var int[]   cur_lengths = array.new_int()
    var int[]   cur_signs   = array.new_int()
    var string[] cur_labels = array.new_string()
    if year == 2025 and month == 10 and dayofmonth == 13
        plot_c_wall := 6.5
        plot_p_wall := 6.5
        plot_flip   := 5.75
        cur_strikes := array.from(6.5, 6.0, 7.0, 7.5, 5.5)
        cur_lengths := array.from(40, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, -1)
        cur_labels  := array.from('$3.42M', '$8K', '$1K', '$0', '$-0')
    if year == 2025 and month == 10 and dayofmonth == 14
        plot_c_wall := 7.0
        plot_p_wall := 6.5
        plot_flip   := 5.75
        cur_strikes := array.from(7.0, 6.5, 7.5, 6.0, 8.0, 5.5)
        cur_lengths := array.from(40, 16, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1, -1)
        cur_labels  := array.from('$1.41M', '$586K', '$0', '$0', '$0', '$-0')
    if year == 2025 and month == 10 and dayofmonth == 15
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := 5.25
        cur_strikes := array.from(6.0, 6.5, 5.5, 7.0, 5.0)
        cur_lengths := array.from(40, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, -1, 1, 1)
        cur_labels  := array.from('$2.37M', '$2K', '$-0', '$0', '$0')
    if year == 2025 and month == 10 and dayofmonth == 16
        plot_c_wall := 5.5
        plot_p_wall := 5.5
        plot_flip   := 5.25
        cur_strikes := array.from(5.5, 6.0, 5.0, 6.5)
        cur_lengths := array.from(40, 2, 2, 2)
        cur_signs   := array.from(-1, 1, 1, 1)
        cur_labels  := array.from('$-6K', '$0', '$0', '$0')
    if year == 2025 and month == 10 and dayofmonth == 20
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(6.0, 5.0)
        cur_lengths := array.from(40, 6)
        cur_signs   := array.from(1, 1)
        cur_labels  := array.from('$1.22M', '$207K')
    if year == 2025 and month == 10 and dayofmonth == 21
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(6.0, 5.5, 5.0, 6.5)
        cur_lengths := array.from(40, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1)
        cur_labels  := array.from('$1.69M', '$125K', '$116K', '$1K')
    if year == 2025 and month == 10 and dayofmonth == 22
        plot_c_wall := 5.0
        plot_p_wall := 5.0
        plot_flip   := 4.75
        cur_strikes := array.from(5.0, 5.5, 6.0, 4.5)
        cur_lengths := array.from(40, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, -1)
        cur_labels  := array.from('$1.81M', '$44K', '$23K', '$-2K')
    if year == 2025 and month == 10 and dayofmonth == 23
        plot_c_wall := 5.0
        plot_p_wall := 5.0
        plot_flip   := 4.75
        cur_strikes := array.from(6.0, 5.0, 5.5, 6.5, 4.5)
        cur_lengths := array.from(40, 24, 11, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, -1)
        cur_labels  := array.from('$723K', '$448K', '$203K', '$742', '$-39')
    if year == 2025 and month == 10 and dayofmonth == 24
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(6.0, 7.0, 6.5, 5.5, 5.0)
        cur_lengths := array.from(40, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1)
        cur_labels  := array.from('$3.96M', '$189K', '$105K', '$38K', '$620')
    if year == 2025 and month == 10 and dayofmonth == 27
        plot_c_wall := 6.0
        plot_p_wall := 6.0
        plot_flip   := na
        cur_strikes := array.from(6.0, 5.5, 6.5, 7.0, 5.0)
        cur_lengths := array.from(40, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1)
        cur_labels  := array.from('$3.56M', '$71K', '$54K', '$11K', '$5K')
    if year == 2025 and month == 10 and dayofmonth == 28
        plot_c_wall := 5.0
        plot_p_wall := 5.0
        plot_flip   := 4.75
        cur_strikes := array.from(5.0, 5.5, 6.0, 4.5)
        cur_lengths := array.from(40, 4, 3, 2)
        cur_signs   := array.from(1, 1, 1, -1)
        cur_labels  := array.from('$958K', '$119K', '$83K', '$-691')
    if year == 2025 and month == 10 and dayofmonth == 29
        plot_c_wall := 5.0
        plot_p_wall := 5.0
        plot_flip   := 4.75
        cur_strikes := array.from(5.0, 5.5, 4.5, 6.0)
        cur_lengths := array.from(40, 2, 2, 2)
        cur_signs   := array.from(1, 1, -1, 1)
        cur_labels  := array.from('$1.78M', '$39K', '$-8K', '$6K')
    if year == 2025 and month == 10 and dayofmonth == 30
        plot_c_wall := 5.0
        plot_p_wall := 5.0
        plot_flip   := 4.75
        cur_strikes := array.from(5.0, 4.5, 5.5, 4.0)
        cur_lengths := array.from(40, 2, 2, 2)
        cur_signs   := array.from(1, -1, 1, -1)
        cur_labels  := array.from('$2.12M', '$-41K', '$13K', '$-1')
    if year == 2025 and month == 10 and dayofmonth == 31
        plot_c_wall := 5.0
        plot_p_wall := 5.0
        plot_flip   := 4.75
        cur_strikes := array.from(5.0, 4.5, 5.5, 4.0)
        cur_lengths := array.from(40, 2, 2, 2)
        cur_signs   := array.from(1, -1, 1, -1)
        cur_labels  := array.from('$1.84M', '$-112K', '$4K', '$-15')
    if year == 2025 and month == 11 and dayofmonth == 3
        plot_c_wall := 4.5
        plot_p_wall := 4.5
        plot_flip   := na
        cur_strikes := array.from(4.5, 5.0, 4.0)
        cur_lengths := array.from(40, 2, 2)
        cur_signs   := array.from(-1, 1, -1)
        cur_labels  := array.from('$-542K', '$32K', '$-11K')
    if year == 2025 and month == 11 and dayofmonth == 4
        plot_c_wall := 4.0
        plot_p_wall := 4.0
        plot_flip   := na
        cur_strikes := array.from(4.0, 4.5, 3.5)
        cur_lengths := array.from(40, 2, 2)
        cur_signs   := array.from(-1, -1, -1)
        cur_labels  := array.from('$-531K', '$-17K', '$-53')
    if year == 2025 and month == 11 and dayofmonth == 5
        plot_c_wall := 4.0
        plot_p_wall := 4.0
        plot_flip   := na
        cur_strikes := array.from(4.0, 4.5, 3.5)
        cur_lengths := array.from(40, 2, 2)
        cur_signs   := array.from(-1, -1, -1)
        cur_labels  := array.from('$-315K', '$-6K', '$-78')
    if year == 2025 and month == 11 and dayofmonth == 6
        plot_c_wall := 4.0
        plot_p_wall := 4.0
        plot_flip   := na
        cur_strikes := array.from(4.0, 3.5, 3.0)
        cur_lengths := array.from(40, 19, 2)
        cur_signs   := array.from(-1, -1, -1)
        cur_labels  := array.from('$-52K', '$-26K', '$-0')
    if year == 2025 and month == 11 and dayofmonth == 7
        plot_c_wall := 4.0
        plot_p_wall := 4.0
        plot_flip   := na
        cur_strikes := array.from(3.5, 4.0, 3.0)
        cur_lengths := array.from(40, 36, 2)
        cur_signs   := array.from(-1, -1, -1)
        cur_labels  := array.from('$-22K', '$-20K', '$-0')
    if year == 2025 and month == 11 and dayofmonth == 10
        plot_c_wall := 4.0
        plot_p_wall := 4.0
        plot_flip   := na
        cur_strikes := array.from(4.0, 3.5, 4.5)
        cur_lengths := array.from(40, 2, 2)
        cur_signs   := array.from(-1, -1, -1)
        cur_labels  := array.from('$-207K', '$-6K', '$-0')
    if year == 2025 and month == 11 and dayofmonth == 11
        plot_c_wall := 3.5
        plot_p_wall := 3.5
        plot_flip   := na
        cur_strikes := array.from(3.5, 4.0, 3.0)
        cur_lengths := array.from(40, 2, 2)
        cur_signs   := array.from(-1, -1, -1)
        cur_labels  := array.from('$-225K', '$-2K', '$-0')
    if year == 2025 and month == 11 and dayofmonth == 12
        plot_c_wall := 3.5
        plot_p_wall := 3.5
        plot_flip   := na
        cur_strikes := array.from(3.5, 4.0, 3.0)
        cur_lengths := array.from(40, 2, 2)
        cur_signs   := array.from(-1, -1, -1)
        cur_labels  := array.from('$-570K', '$-10', '$-0')
    if year == 2025 and month == 11 and dayofmonth == 13
        plot_c_wall := 3.5
        plot_p_wall := 3.5
        plot_flip   := na
        cur_strikes := array.from(3.0, 3.5)
        cur_lengths := array.from(40, 32)
        cur_signs   := array.from(-1, -1)
        cur_labels  := array.from('$-22K', '$-18K')
    if year == 2025 and month == 11 and dayofmonth == 14
        plot_c_wall := 3.5
        plot_p_wall := 3.5
        plot_flip   := na
        cur_strikes := array.from(3.5, 3.0, 4.0)
        cur_lengths := array.from(40, 2, 2)
        cur_signs   := array.from(-1, -1, 1)
        cur_labels  := array.from('$-91K', '$-159', '$0')
    if year == 2025 and month == 11 and dayofmonth == 17
        plot_c_wall := 3.0
        plot_p_wall := 3.0
        plot_flip   := na
        cur_strikes := array.from(3.0, 3.5, 2.5)
        cur_lengths := array.from(40, 2, 2)
        cur_signs   := array.from(-1, 1, -1)
        cur_labels  := array.from('$-257K', '$0', '$-0')
    if year == 2025 and month == 11 and dayofmonth == 18
        plot_c_wall := 3.5
        plot_p_wall := 3.0
        plot_flip   := 3.25
        cur_strikes := array.from(3.5, 3.0)
        cur_lengths := array.from(40, 14)
        cur_signs   := array.from(1, -1)
        cur_labels  := array.from('$90', '$-32')
    if year == 2025 and month == 11 and dayofmonth == 19
        plot_c_wall := 3.0
        plot_p_wall := 3.0
        plot_flip   := na
        cur_strikes := array.from(3.0, 3.5)
        cur_lengths := array.from(40, 2)
        cur_signs   := array.from(-1, 1)
        cur_labels  := array.from('$-9', '$0')
    if year == 2025 and month == 11 and dayofmonth == 20
        plot_c_wall := 3.0
        plot_p_wall := 3.0
        plot_flip   := na
        cur_strikes := array.from(3.0, 3.5, 2.5)
        cur_lengths := array.from(40, 2, 2)
        cur_signs   := array.from(-1, 1, -1)
        cur_labels  := array.from('$-1.65M', '$0', '$-0')
    if year == 2025 and month == 11 and dayofmonth == 24
        plot_c_wall := 3.0
        plot_p_wall := 3.0
        plot_flip   := na
        cur_strikes := array.from(3.0)
        cur_lengths := array.from(40)
        cur_signs   := array.from(-1)
        cur_labels  := array.from('$-282K')
    if year == 2025 and month == 11 and dayofmonth == 25
        plot_c_wall := 4.0
        plot_p_wall := 4.0
        plot_flip   := 3.25
        cur_strikes := array.from(4.0, 3.5, 3.0)
        cur_lengths := array.from(40, 5, 2)
        cur_signs   := array.from(1, 1, -1)
        cur_labels  := array.from('$129K', '$16K', '$-873')
    if year == 2025 and month == 11 and dayofmonth == 26
        plot_c_wall := 3.5
        plot_p_wall := 3.5
        plot_flip   := 3.25
        cur_strikes := array.from(3.5, 4.0, 3.0)
        cur_lengths := array.from(40, 4, 2)
        cur_signs   := array.from(1, 1, -1)
        cur_labels  := array.from('$148K', '$17K', '$-9K')
    if year == 2025 and month == 11 and dayofmonth == 28
        plot_c_wall := 3.5
        plot_p_wall := 3.5
        plot_flip   := 3.25
        cur_strikes := array.from(3.5, 4.0, 3.0)
        cur_lengths := array.from(40, 20, 2)
        cur_signs   := array.from(1, 1, -1)
        cur_labels  := array.from('$138K', '$71K', '$-623')
    if year == 2025 and month == 12 and dayofmonth == 1
        plot_c_wall := 3.5
        plot_p_wall := 3.0
        plot_flip   := 3.25
        cur_strikes := array.from(3.5, 3.0, 4.0)
        cur_lengths := array.from(40, 12, 2)
        cur_signs   := array.from(1, -1, 1)
        cur_labels  := array.from('$104K', '$-33K', '$253')
    if year == 2025 and month == 12 and dayofmonth == 2
        plot_c_wall := 3.5
        plot_p_wall := 3.5
        plot_flip   := 3.25
        cur_strikes := array.from(3.5, 4.0, 3.0)
        cur_lengths := array.from(40, 15, 2)
        cur_signs   := array.from(1, 1, -1)
        cur_labels  := array.from('$123K', '$49K', '$-83')
    if year == 2025 and month == 12 and dayofmonth == 3
        plot_c_wall := 4.0
        plot_p_wall := 4.0
        plot_flip   := na
        cur_strikes := array.from(4.0, 4.5, 5.0, 3.5)
        cur_lengths := array.from(40, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1)
        cur_labels  := array.from('$1.31M', '$67K', '$409', '$0')
    if year == 2025 and month == 12 and dayofmonth == 4
        plot_c_wall := 5.0
        plot_p_wall := 5.0
        plot_flip   := na
        cur_strikes := array.from(5.0, 4.5, 4.0, 5.5)
        cur_lengths := array.from(40, 37, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1)
        cur_labels  := array.from('$604K', '$568K', '$3K', '$3')
    if year == 2025 and month == 12 and dayofmonth == 5
        plot_c_wall := 4.5
        plot_p_wall := 4.5
        plot_flip   := na
        cur_strikes := array.from(4.5, 5.0, 4.0)
        cur_lengths := array.from(40, 3, 2)
        cur_signs   := array.from(1, 1, 1)
        cur_labels  := array.from('$720K', '$60K', '$26K')
    if year == 2025 and month == 12 and dayofmonth == 8
        plot_c_wall := 4.5
        plot_p_wall := 4.5
        plot_flip   := na
        cur_strikes := array.from(4.5, 4.0, 5.0)
        cur_lengths := array.from(40, 3, 2)
        cur_signs   := array.from(1, 1, 1)
        cur_labels  := array.from('$644K', '$52K', '$3K')
    if year == 2025 and month == 12 and dayofmonth == 9
        plot_c_wall := 4.5
        plot_p_wall := 4.5
        plot_flip   := na
        cur_strikes := array.from(4.5, 4.0, 5.0, 3.5)
        cur_lengths := array.from(40, 6, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1)
        cur_labels  := array.from('$506K', '$79K', '$327', '$0')
    if year == 2025 and month == 12 and dayofmonth == 10
        plot_c_wall := 4.0
        plot_p_wall := 4.0
        plot_flip   := na
        cur_strikes := array.from(4.0, 4.5, 3.5)
        cur_lengths := array.from(40, 2, 2)
        cur_signs   := array.from(1, 1, 1)
        cur_labels  := array.from('$1.32M', '$26K', '$0')
    if year == 2025 and month == 12 and dayofmonth == 11
        plot_c_wall := 5.0
        plot_p_wall := 4.5
        plot_flip   := na
        cur_strikes := array.from(5.0, 4.5, 4.0, 5.5)
        cur_lengths := array.from(40, 19, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1)
        cur_labels  := array.from('$1.06M', '$502K', '$0', '$0')
    if year == 2025 and month == 12 and dayofmonth == 12
        plot_c_wall := 4.0
        plot_p_wall := 4.0
        plot_flip   := na
        cur_strikes := array.from(4.0, 4.5, 3.5)
        cur_lengths := array.from(40, 2, 2)
        cur_signs   := array.from(1, 1, 1)
        cur_labels  := array.from('$1.45M', '$4K', '$0')
    if year == 2025 and month == 12 and dayofmonth == 15
        plot_c_wall := 3.5
        plot_p_wall := 3.5
        plot_flip   := 3.25
        cur_strikes := array.from(3.5, 4.0, 3.0)
        cur_lengths := array.from(40, 2, 2)
        cur_signs   := array.from(1, 1, -1)
        cur_labels  := array.from('$320K', '$0', '$-0')
    if year == 2025 and month == 12 and dayofmonth == 16
        plot_c_wall := 3.5
        plot_p_wall := 3.5
        plot_flip   := 3.25
        cur_strikes := array.from(3.5, 4.0, 3.0)
        cur_lengths := array.from(40, 2, 2)
        cur_signs   := array.from(1, 1, -1)
        cur_labels  := array.from('$48K', '$0', '$-0')
    if year == 2025 and month == 12 and dayofmonth == 17
        plot_c_wall := 3.5
        plot_p_wall := 3.5
        plot_flip   := 3.25
        cur_strikes := array.from(3.5, 3.0, 4.0)
        cur_lengths := array.from(40, 2, 2)
        cur_signs   := array.from(1, -1, 1)
        cur_labels  := array.from('$603K', '$-0', '$0')
    if year == 2025 and month == 12 and dayofmonth == 18
        plot_c_wall := 3.5
        plot_p_wall := 3.5
        plot_flip   := 3.25
        cur_strikes := array.from(3.5, 3.0, 4.0)
        cur_lengths := array.from(40, 2, 2)
        cur_signs   := array.from(1, -1, 1)
        cur_labels  := array.from('$128K', '$-0', '$0')
    if year == 2025 and month == 12 and dayofmonth == 22
        plot_c_wall := 4.0
        plot_p_wall := 4.0
        plot_flip   := 3.5
        cur_strikes := array.from(4.0, 3.0)
        cur_lengths := array.from(40, 3)
        cur_signs   := array.from(1, -1)
        cur_labels  := array.from('$42K', '$-3K')
    if year == 2025 and month == 12 and dayofmonth == 23
        plot_c_wall := 3.0
        plot_p_wall := 3.0
        plot_flip   := na
        cur_strikes := array.from(3.0, 3.5, 4.0)
        cur_lengths := array.from(40, 31, 2)
        cur_signs   := array.from(-1, -1, 1)
        cur_labels  := array.from('$-79K', '$-61K', '$4K')
    if year == 2025 and month == 12 and dayofmonth == 24
        plot_c_wall := 3.5
        plot_p_wall := 3.5
        plot_flip   := 3.25
        cur_strikes := array.from(3.5, 3.0)
        cur_lengths := array.from(40, 17)
        cur_signs   := array.from(1, -1)
        cur_labels  := array.from('$40K', '$-18K')
    if year == 2025 and month == 12 and dayofmonth == 25
        plot_c_wall := 4.0
        plot_p_wall := 3.5
        plot_flip   := 3.75
        cur_strikes := array.from(4.0, 3.5)
        cur_lengths := array.from(40, 2)
        cur_signs   := array.from(1, -1)
        cur_labels  := array.from('$756K', '$-45K')
    if year == 2025 and month == 12 and dayofmonth == 26
        plot_c_wall := 4.0
        plot_p_wall := 3.5
        plot_flip   := 3.75
        cur_strikes := array.from(4.0, 3.5)
        cur_lengths := array.from(40, 2)
        cur_signs   := array.from(1, -1)
        cur_labels  := array.from('$756K', '$-45K')
    if year == 2025 and month == 12 and dayofmonth == 27
        plot_c_wall := 3.5
        plot_p_wall := 3.5
        plot_flip   := na
        cur_strikes := array.from(3.5, 3.0)
        cur_lengths := array.from(40, 22)
        cur_signs   := array.from(-1, -1)
        cur_labels  := array.from('$-864K', '$-487K')
    if year == 2025 and month == 12 and dayofmonth == 28
        plot_c_wall := 3.5
        plot_p_wall := 3.5
        plot_flip   := na
        cur_strikes := array.from(3.5, 3.0)
        cur_lengths := array.from(40, 22)
        cur_signs   := array.from(-1, -1)
        cur_labels  := array.from('$-864K', '$-487K')
    if year == 2025 and month == 12 and dayofmonth == 29
        plot_c_wall := 3.5
        plot_p_wall := 3.5
        plot_flip   := na
        cur_strikes := array.from(3.5, 3.0)
        cur_lengths := array.from(40, 22)
        cur_signs   := array.from(-1, -1)
        cur_labels  := array.from('$-864K', '$-487K')
    if year == 2025 and month == 12 and dayofmonth == 30
        plot_c_wall := 3.5
        plot_p_wall := 3.5
        plot_flip   := na
        cur_strikes := array.from(3.5, 3.0)
        cur_lengths := array.from(40, 23)
        cur_signs   := array.from(-1, -1)
        cur_labels  := array.from('$-1.22M', '$-716K')
    if year == 2025 and month == 12 and dayofmonth == 31
        plot_c_wall := 3.5
        plot_p_wall := 3.5
        plot_flip   := na
        cur_strikes := array.from(3.0, 3.5)
        cur_lengths := array.from(40, 37)
        cur_signs   := array.from(-1, -1)
        cur_labels  := array.from('$-1.14M', '$-1.08M')
    if year == 2026 and month == 1 and dayofmonth == 1
        plot_c_wall := 3.5
        plot_p_wall := 3.0
        plot_flip   := na
        cur_strikes := array.from(3.0, 3.5)
        cur_lengths := array.from(40, 2)
        cur_signs   := array.from(-1, -1)
        cur_labels  := array.from('$-3.53M', '$-38K')
    if year == 2026 and month == 1 and dayofmonth == 2
        plot_c_wall := 3.5
        plot_p_wall := 3.0
        plot_flip   := na
        cur_strikes := array.from(3.0, 3.5)
        cur_lengths := array.from(40, 33)
        cur_signs   := array.from(-1, 1)
        cur_labels  := array.from('$-1.84M', '$1.52M')
    if year == 2026 and month == 1 and dayofmonth == 3
        plot_c_wall := 3.5
        plot_p_wall := 3.0
        plot_flip   := na
        cur_strikes := array.from(3.0, 3.5)
        cur_lengths := array.from(40, 5)
        cur_signs   := array.from(-1, 1)
        cur_labels  := array.from('$-726K', '$106K')
    if year == 2026 and month == 1 and dayofmonth == 4
        plot_c_wall := 3.5
        plot_p_wall := 3.0
        plot_flip   := 3.25
        cur_strikes := array.from(3.5, 3.0)
        cur_lengths := array.from(40, 6)
        cur_signs   := array.from(1, -1)
        cur_labels  := array.from('$2.50M', '$-411K')
    if year == 2026 and month == 1 and dayofmonth == 5
        plot_c_wall := 4.0
        plot_p_wall := 3.0
        plot_flip   := 3.25
        cur_strikes := array.from(4.0, 3.5, 3.0)
        cur_lengths := array.from(40, 25, 4)
        cur_signs   := array.from(1, 1, -1)
        cur_labels  := array.from('$4.00M', '$2.52M', '$-415K')
    if year == 2026 and month == 1 and dayofmonth == 6
        plot_c_wall := 4.0
        plot_p_wall := 3.5
        plot_flip   := na
        cur_strikes := array.from(4.0, 3.5)
        cur_lengths := array.from(40, 22)
        cur_signs   := array.from(1, 1)
        cur_labels  := array.from('$4.83M', '$2.75M')
    if year == 2026 and month == 1 and dayofmonth == 7
        plot_c_wall := 4.0
        plot_p_wall := 3.5
        plot_flip   := na
        cur_strikes := array.from(4.0, 3.5)
        cur_lengths := array.from(40, 18)
        cur_signs   := array.from(1, 1)
        cur_labels  := array.from('$5.75M', '$2.65M')
    if year == 2026 and month == 1 and dayofmonth == 8
        plot_c_wall := 3.5
        plot_p_wall := 3.0
        plot_flip   := 3.25
        cur_strikes := array.from(3.5, 3.0)
        cur_lengths := array.from(40, 10)
        cur_signs   := array.from(1, -1)
        cur_labels  := array.from('$2.51M', '$-670K')
    if year == 2026 and month == 1 and dayofmonth == 9
        plot_c_wall := 4.0
        plot_p_wall := 3.5
        plot_flip   := na
        cur_strikes := array.from(4.0, 3.5, 4.5)
        cur_lengths := array.from(40, 14, 7)
        cur_signs   := array.from(1, 1, 1)
        cur_labels  := array.from('$7.66M', '$2.80M', '$1.50M')
    if year == 2026 and month == 1 and dayofmonth == 11
        plot_c_wall := 4.0
        plot_p_wall := 3.5
        plot_flip   := na
        cur_strikes := array.from(4.0, 3.5)
        cur_lengths := array.from(40, 14)
        cur_signs   := array.from(1, 1)
        cur_labels  := array.from('$2.84M', '$1.04M')
    [plot_c_wall, plot_p_wall, plot_flip, cur_strikes, cur_lengths, cur_signs, cur_labels]

// ===== SOFI FUNCTION =====
f_symbol_SOFI() =>
    var float plot_c_wall = na
    var float plot_p_wall = na
    var float plot_flip   = na
    var float[] cur_strikes = array.new_float()
    var int[]   cur_lengths = array.new_int()
    var int[]   cur_signs   = array.new_int()
    var string[] cur_labels = array.new_string()
    if year == 2025 and month == 12 and dayofmonth == 22
        plot_c_wall := 27.0
        plot_p_wall := 27.0
        plot_flip   := 23.5
        cur_strikes := array.from(30.0, 28.0, 29.0, 26.0, 27.0, 25.0, 31.0, 24.0, 32.0, 23.0, 22.0)
        cur_lengths := array.from(40, 39, 14, 7, 5, 3, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, -1, -1, 1, 1, -1, 1, 1, 1)
        cur_labels  := array.from('$7.73M', '$7.66M', '$2.83M', '$-1.37M', '$-1.11M', '$716K', '$405K', '$-163K', '$118K', '$4K', '$4')
    if year == 2025 and month == 12 and dayofmonth == 23
        plot_c_wall := 27.0
        plot_p_wall := 27.0
        plot_flip   := 23.75
        cur_strikes := array.from(28.0, 30.0, 29.0, 26.0, 27.0, 25.0, 26.5, 25.5, 28.5, 31.0, 24.0, 27.5, 29.5, 32.0, 30.5, 24.5, 23.0, 31.5, 23.5, 22.0)
        cur_lengths := array.from(40, 29, 13, 9, 6, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, -1, -1, 1, -1, -1, 1, 1, -1, 1, 1, 1, 1, -1, 1, 1, -1, 1)
        cur_labels  := array.from('$7.69M', '$5.69M', '$2.56M', '$-1.88M', '$-1.34M', '$545K', '$-367K', '$-327K', '$276K', '$256K', '$-206K', '$114K', '$65K', '$63K', '$34K', '$-12K', '$5K', '$1K', '$-306', '$7')
    if year == 2025 and month == 12 and dayofmonth == 24
        plot_c_wall := 27.0
        plot_p_wall := 27.0
        plot_flip   := 23.75
        cur_strikes := array.from(28.0, 30.0, 29.0, 26.0, 27.0, 31.0, 28.5, 26.5, 25.5, 25.0, 27.5, 29.5, 32.0, 24.0, 30.5, 24.5, 31.5, 23.0, 23.5, 22.0)
        cur_lengths := array.from(40, 37, 18, 9, 6, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, -1, -1, 1, 1, -1, -1, 1, 1, 1, 1, -1, 1, -1, 1, 1, -1, 1)
        cur_labels  := array.from('$8.68M', '$8.23M', '$4.11M', '$-2.03M', '$-1.38M', '$417K', '$389K', '$-368K', '$-256K', '$206K', '$192K', '$191K', '$108K', '$-89K', '$70K', '$-12K', '$3K', '$1K', '$-129', '$1')
    if year == 2025 and month == 12 and dayofmonth == 26
        plot_c_wall := 27.0
        plot_p_wall := 27.0
        plot_flip   := 23.75
        cur_strikes := array.from(28.0, 30.0, 26.0, 29.0, 27.0, 26.5, 25.5, 25.0, 27.5, 28.5, 24.0, 31.0, 29.5, 30.5, 24.5, 32.0, 23.0, 31.5, 23.5, 22.0)
        cur_lengths := array.from(40, 17, 14, 13, 8, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, -1, 1, -1, -1, -1, 1, 1, 1, -1, 1, 1, 1, -1, 1, 1, 1, -1, 1)
        cur_labels  := array.from('$7.67M', '$3.43M', '$-2.78M', '$2.52M', '$-1.57M', '$-592K', '$-439K', '$402K', '$399K', '$336K', '$-174K', '$115K', '$103K', '$26K', '$-26K', '$19K', '$3K', '$561', '$-284', '$3')
    if year == 2025 and month == 12 and dayofmonth == 29
        plot_c_wall := 30.0
        plot_p_wall := 27.0
        plot_flip   := 29.75
        cur_strikes := array.from(30.0, 28.0, 29.0, 26.0, 27.0, 25.0, 31.0, 24.0, 28.5, 25.5, 26.5, 29.5, 27.5, 30.5, 24.5, 23.5)
        cur_lengths := array.from(40, 19, 16, 15, 14, 10, 8, 8, 7, 3, 3, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, -1, -1, -1, 1, -1, 1, -1, -1, 1, 1, 1, -1, -1)
        cur_labels  := array.from('$20.01M', '$9.76M', '$8.46M', '$-7.54M', '$-7.38M', '$-5.38M', '$4.37M', '$-4.08M', '$3.67M', '$-1.93M', '$-1.89M', '$1.48M', '$1.48M', '$552K', '$-298K', '$-56K')
    if year == 2025 and month == 12 and dayofmonth == 30
        plot_c_wall := 30.0
        plot_p_wall := 27.0
        plot_flip   := 29.75
        cur_strikes := array.from(30.0, 28.0, 26.0, 27.0, 29.0, 25.0, 24.0, 28.5, 26.5, 25.5, 27.5, 23.0, 29.5, 30.5, 24.5, 23.5)
        cur_lengths := array.from(40, 23, 22, 19, 18, 13, 10, 8, 7, 5, 3, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, -1, -1, 1, -1, -1, 1, -1, -1, 1, -1, 1, 1, -1, -1)
        cur_labels  := array.from('$17.82M', '$10.32M', '$-9.84M', '$-8.78M', '$8.03M', '$-6.15M', '$-4.51M', '$3.93M', '$-3.29M', '$-2.44M', '$1.59M', '$-1.27M', '$1.27M', '$540K', '$-355K', '$-83K')
    if year == 2025 and month == 12 and dayofmonth == 31
        plot_c_wall := 27.0
        plot_p_wall := 27.0
        plot_flip   := na
        cur_strikes := array.from(30.0, 26.0, 28.0, 27.0, 25.0, 29.0, 26.5, 24.0, 28.5, 25.5, 27.5, 29.5, 23.0, 24.5, 30.5, 23.5)
        cur_lengths := array.from(40, 37, 29, 28, 21, 19, 16, 12, 10, 10, 6, 3, 2, 2, 2, 2)
        cur_signs   := array.from(1, -1, 1, -1, -1, 1, -1, -1, 1, -1, 1, 1, -1, -1, 1, -1)
        cur_labels  := array.from('$16.04M', '$-14.86M', '$11.80M', '$-11.33M', '$-8.67M', '$7.72M', '$-6.72M', '$-5.00M', '$4.37M', '$-4.36M', '$2.47M', '$1.35M', '$-1.11M', '$-438K', '$437K', '$-235K')
    if year == 2026 and month == 1 and dayofmonth == 1
        plot_c_wall := 27.0
        plot_p_wall := 27.0
        plot_flip   := na
        cur_strikes := array.from(26.0, 30.0, 26.5, 28.0, 27.0, 25.0, 29.0, 27.5, 25.5, 24.0, 28.5, 23.0, 29.5, 24.5, 23.5)
        cur_lengths := array.from(40, 25, 25, 24, 22, 20, 12, 10, 10, 9, 8, 2, 2, 2, 2)
        cur_signs   := array.from(-1, 1, -1, 1, -1, -1, 1, 1, -1, -1, 1, -1, 1, -1, -1)
        cur_labels  := array.from('$-22.53M', '$14.64M', '$-14.63M', '$13.72M', '$-12.46M', '$-11.47M', '$7.23M', '$5.83M', '$-5.66M', '$-5.53M', '$4.95M', '$-1.45M', '$1.28M', '$-779K', '$-253K')
    if year == 2026 and month == 1 and dayofmonth == 2
        plot_c_wall := 27.0
        plot_p_wall := 26.0
        plot_flip   := na
        cur_strikes := array.from(26.0, 26.5, 25.0, 30.0, 28.0, 25.5, 27.5, 29.0, 24.0, 27.0, 28.5, 23.0, 29.5, 24.5, 23.5)
        cur_lengths := array.from(40, 22, 17, 17, 15, 10, 9, 8, 8, 7, 6, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, 1, 1, -1, 1, 1, -1, -1, 1, -1, 1, -1, -1)
        cur_labels  := array.from('$-30.02M', '$-16.53M', '$-13.37M', '$12.83M', '$11.88M', '$-7.99M', '$7.41M', '$6.55M', '$-6.43M', '$-5.54M', '$5.09M', '$-1.56M', '$1.27M', '$-1.23M', '$-217K')
    if year == 2026 and month == 1 and dayofmonth == 3
        plot_c_wall := 25.0
        plot_p_wall := 25.0
        plot_flip   := na
        cur_strikes := array.from(30.0, 25.0, 26.0, 24.0, 28.0, 29.0, 25.5, 26.5, 31.0, 28.5, 27.0, 24.5, 29.5, 27.5, 30.5, 23.5)
        cur_lengths := array.from(40, 37, 35, 19, 19, 16, 11, 9, 9, 6, 3, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, -1, -1, -1, 1, 1, -1, -1, 1, 1, -1, -1, 1, 1, 1, -1)
        cur_labels  := array.from('$12.51M', '$-11.60M', '$-11.00M', '$-6.24M', '$6.03M', '$5.14M', '$-3.56M', '$-2.93M', '$2.82M', '$2.08M', '$-1.02M', '$-886K', '$742K', '$603K', '$301K', '$-5K')
    if year == 2026 and month == 1 and dayofmonth == 4
        plot_c_wall := 30.0
        plot_p_wall := 25.0
        plot_flip   := 29.75
        cur_strikes := array.from(30.0, 26.0, 28.0, 29.0, 25.0, 24.0, 31.0, 28.5, 26.5, 25.5, 27.0, 29.5, 27.5, 24.5, 30.5, 23.5)
        cur_lengths := array.from(40, 20, 19, 18, 18, 8, 8, 7, 6, 5, 4, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, -1, 1, 1, -1, -1, 1, 1, -1, -1, -1, 1, 1, -1, 1, -1)
        cur_labels  := array.from('$18.44M', '$-9.60M', '$8.98M', '$8.41M', '$-8.38M', '$-4.12M', '$3.99M', '$3.66M', '$-3.17M', '$-2.66M', '$-1.87M', '$1.27M', '$1.10M', '$-654K', '$494K', '$-55K')
    if year == 2026 and month == 1 and dayofmonth == 5
        plot_c_wall := 30.0
        plot_p_wall := 25.0
        plot_flip   := 29.75
        cur_strikes := array.from(30.0, 26.0, 28.0, 29.0, 25.0, 24.0, 31.0, 28.5, 26.5, 25.5, 27.0, 29.5, 27.5, 24.5, 30.5, 31.5, 23.5)
        cur_lengths := array.from(40, 20, 19, 18, 18, 8, 8, 7, 6, 5, 4, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, -1, 1, 1, -1, -1, 1, 1, -1, -1, -1, 1, 1, -1, 1, 1, -1)
        cur_labels  := array.from('$18.52M', '$-9.64M', '$9.02M', '$8.45M', '$-8.42M', '$-4.13M', '$4.00M', '$3.68M', '$-3.18M', '$-2.68M', '$-1.87M', '$1.28M', '$1.10M', '$-657K', '$496K', '$144K', '$-55K')
    if year == 2026 and month == 1 and dayofmonth == 6
        plot_c_wall := 30.0
        plot_p_wall := 25.0
        plot_flip   := 29.75
        cur_strikes := array.from(30.0, 25.0, 26.0, 28.0, 29.0, 32.0, 31.0, 28.5, 26.5, 25.5, 33.0, 27.0, 29.5, 27.5, 30.5, 31.5)
        cur_lengths := array.from(40, 17, 16, 15, 14, 12, 9, 5, 5, 4, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, -1, -1, 1, 1, 1, 1, 1, -1, -1, 1, -1, 1, 1, 1, 1)
        cur_labels  := array.from('$26.59M', '$-11.31M', '$-10.76M', '$10.46M', '$9.61M', '$8.11M', '$6.38M', '$3.92M', '$-3.40M', '$-2.85M', '$1.90M', '$-1.85M', '$1.36M', '$1.18M', '$529K', '$154K')
    if year == 2026 and month == 1 and dayofmonth == 7
        plot_c_wall := 30.0
        plot_p_wall := 25.0
        plot_flip   := 28.75
        cur_strikes := array.from(30.0, 29.0, 31.0, 28.0, 25.0, 26.0, 28.5, 24.0, 23.0, 29.5, 26.5, 25.5, 30.5, 27.0, 27.5, 24.5, 23.5)
        cur_lengths := array.from(40, 12, 10, 9, 8, 6, 4, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, -1, -1, 1, -1, -1, 1, -1, -1, 1, -1, 1, -1, -1)
        cur_labels  := array.from('$32.24M', '$10.35M', '$8.48M', '$7.54M', '$-6.49M', '$-5.61M', '$3.59M', '$-2.84M', '$-2.49M', '$2.01M', '$-1.53M', '$-1.17M', '$1.02M', '$-943K', '$613K', '$-292K', '$-27K')
    if year == 2026 and month == 1 and dayofmonth == 8
        plot_c_wall := 30.0
        plot_p_wall := 25.0
        plot_flip   := 29.75
        cur_strikes := array.from(30.0, 26.0, 28.0, 25.0, 29.0, 31.0, 24.0, 26.5, 29.5, 23.0, 28.5, 25.5, 27.0, 30.5, 24.5, 23.5, 27.5)
        cur_lengths := array.from(40, 24, 19, 18, 16, 12, 9, 7, 6, 6, 5, 5, 5, 3, 2, 2, 2)
        cur_signs   := array.from(1, -1, 1, -1, 1, 1, -1, -1, 1, -1, 1, -1, -1, 1, -1, -1, 1)
        cur_labels  := array.from('$25.13M', '$-15.61M', '$12.12M', '$-11.80M', '$10.49M', '$8.01M', '$-5.66M', '$-4.58M', '$4.26M', '$-4.17M', '$3.76M', '$-3.61M', '$-3.39M', '$1.97M', '$-977K', '$-140K', '$67K')
    if year == 2026 and month == 1 and dayofmonth == 9
        plot_c_wall := 27.0
        plot_p_wall := 25.0
        plot_flip   := 29.75
        cur_strikes := array.from(30.0, 26.0, 25.0, 28.0, 29.0, 24.0, 26.5, 31.0, 25.5, 27.5, 28.5, 29.5, 27.0, 24.5, 30.5, 31.5)
        cur_lengths := array.from(40, 33, 27, 26, 17, 12, 12, 11, 10, 7, 7, 5, 4, 2, 2, 2)
        cur_signs   := array.from(1, -1, -1, 1, 1, -1, -1, 1, -1, 1, 1, 1, 1, -1, 1, 1)
        cur_labels  := array.from('$25.40M', '$-21.28M', '$-17.56M', '$16.77M', '$11.12M', '$-8.11M', '$-7.83M', '$7.57M', '$-6.76M', '$5.06M', '$5.00M', '$3.79M', '$2.91M', '$-1.83M', '$1.66M', '$573K')
    if year == 2026 and month == 1 and dayofmonth == 10
        plot_c_wall := 30.0
        plot_p_wall := 25.0
        plot_flip   := 29.75
        cur_strikes := array.from(30.0, 25.0, 26.0, 28.0, 29.0, 31.0, 24.0, 25.5, 28.5, 29.5, 26.5, 24.5, 30.5, 27.5, 23.5, 27.0)
        cur_lengths := array.from(40, 18, 18, 14, 12, 11, 9, 3, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, -1, -1, 1, 1, 1, -1, -1, 1, 1, -1, -1, 1, 1, -1, -1)
        cur_labels  := array.from('$26.86M', '$-12.41M', '$-12.15M', '$9.78M', '$8.71M', '$7.39M', '$-6.47M', '$-2.33M', '$1.57M', '$1.43M', '$-1.15M', '$-1.13M', '$854K', '$838K', '$-308K', '$-290K')
    [plot_c_wall, plot_p_wall, plot_flip, cur_strikes, cur_lengths, cur_signs, cur_labels]

// ===== SOXL FUNCTION =====
f_symbol_SOXL() =>
    var float plot_c_wall = na
    var float plot_p_wall = na
    var float plot_flip   = na
    var float[] cur_strikes = array.new_float()
    var int[]   cur_lengths = array.new_int()
    var int[]   cur_signs   = array.new_int()
    var string[] cur_labels = array.new_string()
    if year == 2026 and month == 1 and dayofmonth == 2
        plot_c_wall := 40.0
        plot_p_wall := 42.0
        plot_flip   := 37.75
        cur_strikes := array.from(42.0, 45.0, 42.5, 44.0, 46.0, 44.5, 41.0, 38.0, 47.0, 40.5, 41.5, 40.0, 39.0, 43.5, 43.0, 48.0, 39.5, 45.5, 46.5, 36.5, 36.0, 47.5, 37.5, 38.5, 37.0)
        cur_lengths := array.from(40, 34, 19, 18, 16, 14, 11, 11, 10, 10, 10, 8, 8, 7, 6, 5, 4, 3, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, 1, -1, 1, 1, 1, -1, 1, 1, -1, -1, -1, -1, 1, -1, 1, -1, 1, 1, -1, -1, 1, -1, -1, -1)
        cur_labels  := array.from('$-5.06M', '$4.35M', '$-2.50M', '$2.28M', '$2.06M', '$1.85M', '$-1.48M', '$1.47M', '$1.36M', '$-1.30M', '$-1.30M', '$-1.10M', '$-1.05M', '$958K', '$-801K', '$683K', '$-630K', '$505K', '$343K', '$-284K', '$-241K', '$177K', '$-162K', '$-157K', '$-103K')
    if year == 2026 and month == 1 and dayofmonth == 3
        plot_c_wall := 45.0
        plot_p_wall := 42.0
        plot_flip   := 44.75
        cur_strikes := array.from(50.0, 45.0, 49.0, 46.0, 47.0, 44.0, 42.5, 48.0, 42.0, 52.0, 51.0, 40.5, 54.0, 53.0, 44.5, 41.0, 45.5, 43.0, 46.5, 47.5, 51.5, 49.5, 52.5, 50.5, 48.5, 43.5, 41.5)
        cur_lengths := array.from(40, 37, 16, 13, 10, 9, 6, 6, 5, 5, 4, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1, 1, -1, 1, -1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1)
        cur_labels  := array.from('$2.73M', '$2.57M', '$1.10M', '$940K', '$716K', '$650K', '$-425K', '$422K', '$-391K', '$377K', '$277K', '$-228K', '$196K', '$176K', '$149K', '$103K', '$103K', '$96K', '$93K', '$81K', '$32K', '$-31K', '$19K', '$9K', '$9K', '$654', '$588')
    if year == 2026 and month == 1 and dayofmonth == 4
        plot_c_wall := 50.0
        plot_p_wall := 42.0
        plot_flip   := 43.75
        cur_strikes := array.from(50.0, 45.0, 49.0, 47.0, 52.0, 48.0, 46.0, 44.0, 51.0, 54.0, 53.0, 44.5, 47.5, 42.5, 45.5, 46.5, 40.5, 51.5, 43.5, 42.0, 41.5, 52.5, 49.5, 41.0, 50.5, 48.5, 43.0)
        cur_lengths := array.from(40, 20, 12, 11, 10, 8, 8, 7, 4, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, -1, 1, 1, -1, -1, 1, -1, 1, 1, 1, -1)
        cur_labels  := array.from('$4.42M', '$2.23M', '$1.42M', '$1.25M', '$1.18M', '$936K', '$898K', '$801K', '$457K', '$334K', '$293K', '$230K', '$203K', '$-179K', '$112K', '$99K', '$-91K', '$62K', '$56K', '$-41K', '$-35K', '$29K', '$-20K', '$19K', '$10K', '$9K', '$-3K')
    if year == 2026 and month == 1 and dayofmonth == 5
        plot_c_wall := 50.0
        plot_p_wall := 42.0
        plot_flip   := 43.75
        cur_strikes := array.from(50.0, 45.0, 49.0, 47.0, 52.0, 48.0, 46.0, 44.0, 51.0, 54.0, 53.0, 44.5, 47.5, 42.5, 45.5, 46.5, 40.5, 51.5, 43.5, 42.0, 41.5, 52.5, 49.5, 41.0, 50.5, 48.5, 43.0)
        cur_lengths := array.from(40, 20, 12, 11, 10, 8, 8, 7, 4, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, -1, 1, 1, -1, -1, 1, -1, 1, 1, 1, -1)
        cur_labels  := array.from('$4.40M', '$2.22M', '$1.42M', '$1.24M', '$1.18M', '$933K', '$895K', '$798K', '$456K', '$333K', '$292K', '$229K', '$203K', '$-179K', '$111K', '$99K', '$-90K', '$61K', '$56K', '$-41K', '$-35K', '$29K', '$-20K', '$19K', '$10K', '$9K', '$-3K')
    if year == 2026 and month == 1 and dayofmonth == 6
        plot_c_wall := 50.0
        plot_p_wall := 42.0
        plot_flip   := 42.25
        cur_strikes := array.from(50.0, 45.0, 49.0, 47.0, 55.0, 52.0, 46.0, 48.0, 44.0, 51.0, 54.0, 53.0, 56.0, 44.5, 47.5, 42.5, 43.0, 45.5, 46.5, 51.5, 43.5, 42.0, 52.5, 49.5, 50.5, 48.5)
        cur_lengths := array.from(40, 24, 11, 11, 10, 9, 9, 8, 6, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1)
        cur_labels  := array.from('$5.22M', '$3.23M', '$1.54M', '$1.46M', '$1.31M', '$1.29M', '$1.22M', '$1.15M', '$900K', '$541K', '$357K', '$334K', '$240K', '$239K', '$211K', '$-186K', '$134K', '$116K', '$103K', '$64K', '$59K', '$43K', '$30K', '$-21K', '$11K', '$9K')
    if year == 2026 and month == 1 and dayofmonth == 7
        plot_c_wall := 50.0
        plot_p_wall := 48.0
        plot_flip   := na
        cur_strikes := array.from(50.0, 60.0, 49.0, 52.0, 55.0, 46.0, 58.0, 47.0, 48.0, 51.0, 54.0, 53.0, 56.0, 61.0, 57.0, 47.5, 46.5, 62.0, 51.5, 52.5, 59.0, 49.5, 50.5, 48.5)
        cur_lengths := array.from(40, 13, 11, 11, 11, 9, 8, 7, 6, 4, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1)
        cur_labels  := array.from('$5.91M', '$2.07M', '$1.69M', '$1.65M', '$1.65M', '$1.35M', '$1.33M', '$1.15M', '$907K', '$614K', '$445K', '$414K', '$310K', '$292K', '$184K', '$184K', '$114K', '$82K', '$81K', '$41K', '$39K', '$-26K', '$12K', '$10K')
    if year == 2026 and month == 1 and dayofmonth == 8
        plot_c_wall := 50.0
        plot_p_wall := 50.0
        plot_flip   := 44.75
        cur_strikes := array.from(50.0, 55.0, 60.0, 58.0, 56.0, 52.0, 45.0, 53.0, 54.0, 51.0, 49.0, 49.5, 57.0, 51.5, 48.0, 47.0, 52.5, 48.5, 46.0, 59.0, 47.5, 50.5, 46.5, 44.5, 45.5)
        cur_lengths := array.from(40, 31, 27, 17, 15, 14, 9, 9, 8, 8, 7, 6, 5, 4, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, -1)
        cur_labels  := array.from('$5.05M', '$3.99M', '$3.41M', '$2.17M', '$1.95M', '$1.82M', '$1.20M', '$1.16M', '$1.12M', '$1.07M', '$990K', '$760K', '$708K', '$601K', '$455K', '$430K', '$400K', '$202K', '$200K', '$159K', '$131K', '$59K', '$-53K', '$-46K', '$-2K')
    if year == 2026 and month == 1 and dayofmonth == 9
        plot_c_wall := 50.0
        plot_p_wall := 50.0
        plot_flip   := 44.75
        cur_strikes := array.from(55.0, 50.0, 56.0, 52.0, 53.0, 54.0, 45.0, 57.0, 51.0, 49.5, 49.0, 47.0, 52.5, 48.0, 51.5, 42.5, 46.0, 43.0, 47.5, 50.5, 46.5, 43.5, 44.0, 45.5, 48.5, 44.5, 54.5, 53.5, 55.5, 56.5)
        cur_lengths := array.from(40, 35, 23, 16, 16, 13, 10, 7, 6, 6, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, 1, -1, 1, 1, 1, 1, -1, -1, 1, -1, -1, 1, 1, 1, 1, 1)
        cur_labels  := array.from('$5.10M', '$4.47M', '$2.97M', '$2.11M', '$2.10M', '$1.71M', '$1.30M', '$947K', '$870K', '$866K', '$618K', '$322K', '$-316K', '$-191K', '$143K', '$-137K', '$121K', '$88K', '$88K', '$88K', '$-43K', '$-28K', '$13K', '$-11K', '$-7K', '$3K', '$0', '$0', '$0', '$0')
    if year == 2026 and month == 1 and dayofmonth == 10
        plot_c_wall := 50.0
        plot_p_wall := 48.0
        plot_flip   := na
        cur_strikes := array.from(50.0, 60.0, 55.0, 53.0, 49.0, 56.0, 58.0, 52.0, 54.0, 51.0, 57.0, 51.5, 61.0, 47.5, 47.0, 50.5, 49.5, 62.0, 52.5, 59.0, 48.5, 48.0, 46.5, 53.5, 57.5, 54.5, 59.5, 55.5, 58.5, 61.5, 60.5, 56.5)
        cur_lengths := array.from(40, 25, 22, 15, 14, 13, 13, 9, 6, 6, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1)
        cur_labels  := array.from('$4.27M', '$2.76M', '$2.44M', '$1.64M', '$1.49M', '$1.49M', '$1.45M', '$982K', '$725K', '$684K', '$459K', '$269K', '$269K', '$264K', '$261K', '$137K', '$118K', '$117K', '$114K', '$105K', '$91K', '$31K', '$27K', '$9K', '$7K', '$7K', '$-5K', '$3K', '$2K', '$1K', '$553', '$433')
    [plot_c_wall, plot_p_wall, plot_flip, cur_strikes, cur_lengths, cur_signs, cur_labels]

// ===== SPY FUNCTION =====
f_symbol_SPY() =>
    var float plot_c_wall = na
    var float plot_p_wall = na
    var float plot_flip   = na
    var float[] cur_strikes = array.new_float()
    var int[]   cur_lengths = array.new_int()
    var int[]   cur_signs   = array.new_int()
    var string[] cur_labels = array.new_string()
    if year == 2025 and month == 12 and dayofmonth == 23
        plot_c_wall := 210.0
        plot_p_wall := 660.0
        plot_flip   := 572.5
        cur_strikes := array.from(660.0, 650.0, 670.0, 675.0, 647.0, 665.0, 655.0, 640.0, 645.0, 635.0, 653.0, 654.0, 595.0, 630.0, 644.0, 585.0, 646.0, 673.0, 651.0, 625.0, 643.0, 610.0, 620.0, 649.0, 600.0, 642.0, 678.0, 674.0, 679.0, 615.0, 575.0, 677.0, 590.0, 580.0, 676.0, 657.0, 605.0, 672.0, 666.0, 659.0)
        cur_lengths := array.from(40, 39, 37, 30, 21, 21, 17, 16, 10, 10, 9, 8, 8, 8, 7, 7, 7, 5, 5, 5, 5, 5, 4, 4, 4, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1)
        cur_labels  := array.from('$-31.84M', '$-31.13M', '$-29.69M', '$-24.54M', '$-16.96M', '$-16.76M', '$-14.22M', '$-13.19M', '$-8.62M', '$-8.40M', '$-7.65M', '$-7.02M', '$-6.64M', '$-6.49M', '$-6.00M', '$-5.84M', '$-5.81M', '$-4.67M', '$-4.40M', '$-4.22M', '$-4.00M', '$-4.00M', '$-3.40M', '$-3.25M', '$-3.24M', '$-3.14M', '$-3.07M', '$-2.66M', '$-2.45M', '$-2.42M', '$-2.06M', '$-1.92M', '$-1.72M', '$-1.62M', '$-1.46M', '$-1.29M', '$-1.24M', '$-1.14M', '$-962K', '$-949K')
    if year == 2025 and month == 12 and dayofmonth == 23
        plot_c_wall := 700.0
        plot_p_wall := 660.0
        plot_flip   := 547.5
        cur_strikes := array.from(700.0, 690.0, 695.0, 660.0, 705.0, 650.0, 670.0, 685.0, 647.0, 710.0, 655.0, 640.0, 665.0, 653.0, 635.0, 654.0, 715.0, 595.0, 646.0, 645.0, 644.0, 630.0, 585.0, 720.0, 693.0, 675.0, 673.0, 651.0, 643.0, 725.0, 688.0, 610.0, 625.0, 689.0, 701.0, 649.0, 696.0, 642.0, 702.0, 687.0)
        cur_lengths := array.from(40, 24, 19, 19, 15, 14, 13, 12, 12, 11, 7, 6, 6, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, -1, 1, -1, -1, 1, -1, 1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, 1, 1, -1, -1, -1, -1, 1, -1, -1, -1, 1, 1, -1, 1, -1, 1, 1)
        cur_labels  := array.from('$53.65M', '$32.51M', '$26.61M', '$-25.77M', '$20.66M', '$-19.17M', '$-18.16M', '$17.28M', '$-16.96M', '$16.01M', '$-10.40M', '$-8.50M', '$-8.06M', '$-7.64M', '$-7.13M', '$-7.01M', '$6.72M', '$-6.37M', '$-5.81M', '$-5.77M', '$-5.76M', '$-5.71M', '$-5.62M', '$5.02M', '$4.95M', '$-4.88M', '$-4.47M', '$-4.40M', '$-4.00M', '$3.97M', '$-3.81M', '$-3.70M', '$-3.59M', '$3.28M', '$3.27M', '$-3.24M', '$3.19M', '$-3.12M', '$3.07M', '$3.05M')
    if year == 2025 and month == 12 and dayofmonth == 24
        plot_c_wall := 700.0
        plot_p_wall := 660.0
        plot_flip   := 547.5
        cur_strikes := array.from(700.0, 690.0, 695.0, 660.0, 705.0, 650.0, 670.0, 685.0, 647.0, 710.0, 655.0, 640.0, 665.0, 653.0, 635.0, 654.0, 715.0, 595.0, 646.0, 645.0, 644.0, 630.0, 585.0, 720.0, 693.0, 675.0, 673.0, 651.0, 643.0, 725.0, 688.0, 610.0, 625.0, 689.0, 701.0, 649.0, 696.0, 642.0, 702.0, 687.0)
        cur_lengths := array.from(40, 24, 19, 19, 15, 14, 13, 12, 12, 11, 7, 6, 6, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, -1, 1, -1, -1, 1, -1, 1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, 1, 1, -1, -1, -1, -1, 1, -1, -1, -1, 1, 1, -1, 1, -1, 1, 1)
        cur_labels  := array.from('$53.65M', '$32.51M', '$26.61M', '$-25.77M', '$20.66M', '$-19.17M', '$-18.16M', '$17.28M', '$-16.96M', '$16.01M', '$-10.40M', '$-8.50M', '$-8.06M', '$-7.64M', '$-7.13M', '$-7.01M', '$6.72M', '$-6.37M', '$-5.81M', '$-5.77M', '$-5.76M', '$-5.71M', '$-5.62M', '$5.02M', '$4.95M', '$-4.88M', '$-4.47M', '$-4.40M', '$-4.00M', '$3.97M', '$-3.81M', '$-3.70M', '$-3.59M', '$3.28M', '$3.27M', '$-3.24M', '$3.19M', '$-3.12M', '$3.07M', '$3.05M')
    if year == 2025 and month == 12 and dayofmonth == 24
        plot_c_wall := 690.0
        plot_p_wall := 680.0
        plot_flip   := 587.5
        cur_strikes := array.from(690.0, 685.0, 684.0, 687.0, 689.0, 688.0, 681.0, 686.0, 682.0, 691.0, 680.0, 692.0, 695.0, 675.0, 693.0, 670.0, 694.0, 674.0, 683.0, 678.0, 700.0, 677.0, 659.0, 673.0, 665.0, 697.0, 660.0, 671.0, 679.0, 652.0, 669.0, 664.0, 668.0, 662.0, 699.0, 655.0, 696.0, 667.0, 658.0, 650.0)
        cur_lengths := array.from(40, 18, 14, 11, 10, 10, 9, 8, 7, 7, 6, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, 1, -1, -1, -1)
        cur_labels  := array.from('$109.45M', '$50.01M', '$39.17M', '$32.24M', '$28.18M', '$27.73M', '$26.32M', '$23.46M', '$21.55M', '$21.29M', '$17.08M', '$14.75M', '$7.58M', '$-7.27M', '$7.06M', '$-6.56M', '$6.30M', '$-5.40M', '$5.15M', '$-4.98M', '$4.77M', '$-4.52M', '$-4.39M', '$-3.18M', '$-3.10M', '$3.08M', '$-2.77M', '$-2.08M', '$-2.05M', '$-1.83M', '$-1.79M', '$-1.72M', '$-1.67M', '$-1.67M', '$1.47M', '$-1.46M', '$1.40M', '$-1.27M', '$-1.20M', '$-1.15M')
    [plot_c_wall, plot_p_wall, plot_flip, cur_strikes, cur_lengths, cur_signs, cur_labels]

// ===== TEMT FUNCTION =====
f_symbol_TEMT() =>
    var float plot_c_wall = na
    var float plot_p_wall = na
    var float plot_flip   = na
    var float[] cur_strikes = array.new_float()
    var int[]   cur_lengths = array.new_int()
    var int[]   cur_signs   = array.new_int()
    var string[] cur_labels = array.new_string()
    if year == 2025 and month == 10 and dayofmonth == 13
        plot_c_wall := 42.0
        plot_p_wall := 41.0
        plot_flip   := 34.5
        cur_strikes := array.from(42.0, 41.0, 43.0, 40.0, 39.0, 45.0, 38.0, 37.0, 47.0, 36.0, 48.0, 35.0, 34.0, 44.0, 46.0, 49.0)
        cur_lengths := array.from(40, 13, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, -1, 1, 1, 1, -1, 1, 1, -1, 1, 1, 1, -1, 1, 1, 1)
        cur_labels  := array.from('$104K', '$-34K', '$13K', '$1K', '$28', '$-0', '$0', '$0', '$-0', '$0', '$0', '$0', '$-0', '$0', '$0', '$0')
    if year == 2025 and month == 10 and dayofmonth == 14
        plot_c_wall := 37.0
        plot_p_wall := 37.0
        plot_flip   := 34.5
        cur_strikes := array.from(37.0, 38.0, 36.0, 39.0, 35.0, 40.0, 41.0, 34.0, 42.0, 33.0, 43.0, 32.0, 31.0, 30.0, 44.0)
        cur_lengths := array.from(40, 9, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1, 1, -1, -1, 1, -1, 1, -1, -1, -1, 1)
        cur_labels  := array.from('$21K', '$5K', '$3K', '$319', '$24', '$3', '$-0', '$-0', '$0', '$-0', '$0', '$-0', '$-0', '$-0', '$0')
    if year == 2025 and month == 10 and dayofmonth == 15
        plot_c_wall := 40.0
        plot_p_wall := 39.0
        plot_flip   := 34.5
        cur_strikes := array.from(39.0, 40.0, 38.0, 41.0, 37.0, 42.0, 36.0, 43.0, 35.0, 34.0, 33.0, 47.0, 32.0, 44.0, 45.0, 46.0)
        cur_lengths := array.from(40, 17, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, 1, 1, -1, 1, 1, 1, 1, 1, -1, -1, -1, -1, 1, 1, 1)
        cur_labels  := array.from('$-19K', '$9K', '$388', '$-178', '$3', '$0', '$0', '$0', '$0', '$-0', '$-0', '$-0', '$-0', '$0', '$0', '$0')
    if year == 2025 and month == 10 and dayofmonth == 16
        plot_c_wall := 38.0
        plot_p_wall := 39.0
        plot_flip   := 34.5
        cur_strikes := array.from(39.0, 38.0, 37.0, 40.0, 41.0, 36.0, 42.0, 35.0, 43.0, 34.0, 33.0, 32.0, 31.0, 44.0, 45.0, 46.0)
        cur_lengths := array.from(40, 9, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, 1, 1, 1, -1, 1, 1, 1, 1, -1, -1, -1, -1, 1, 1, 1)
        cur_labels  := array.from('$-16K', '$4K', '$11', '$5', '$-0', '$0', '$0', '$0', '$0', '$-0', '$-0', '$-0', '$-0', '$0', '$0', '$0')
    if year == 2025 and month == 10 and dayofmonth == 20
        plot_c_wall := 40.0
        plot_p_wall := 41.0
        plot_flip   := na
        cur_strikes := array.from(38.0, 40.0, 41.0, 42.0, 43.0, 39.0, 44.0, 37.0, 36.0, 34.0, 35.0, 45.0, 46.0, 33.0, 32.0, 47.0)
        cur_lengths := array.from(40, 29, 27, 22, 8, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, 1, -1, 1, 1, -1, 1, -1, 1, -1, -1, 1, -1, -1, -1, 1)
        cur_labels  := array.from('$-8K', '$6K', '$-6K', '$5K', '$2K', '$-712', '$562', '$-320', '$287', '$-195', '$-191', '$136', '$-94', '$-41', '$-0', '$0')
    if year == 2025 and month == 10 and dayofmonth == 21
        plot_c_wall := 36.0
        plot_p_wall := 38.0
        plot_flip   := na
        cur_strikes := array.from(38.0, 34.0, 37.0, 33.0, 35.0, 36.0, 39.0, 40.0, 41.0, 42.0, 31.0, 43.0, 30.0, 32.0)
        cur_lengths := array.from(40, 25, 14, 12, 8, 7, 3, 3, 3, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1, -1, 1, -1, 1, -1, 1, -1, 1, -1, -1)
        cur_labels  := array.from('$-8K', '$-5K', '$-3K', '$-2K', '$-2K', '$1K', '$-694', '$675', '$-667', '$261', '$-87', '$48', '$-38', '$-32')
    if year == 2025 and month == 10 and dayofmonth == 22
        plot_c_wall := 34.0
        plot_p_wall := 34.0
        plot_flip   := na
        cur_strikes := array.from(34.0, 33.0, 30.0, 31.0, 32.0, 35.0, 37.0, 38.0, 36.0, 29.0, 28.0, 39.0, 40.0, 27.0)
        cur_lengths := array.from(40, 37, 9, 8, 4, 3, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, -1)
        cur_labels  := array.from('$-17K', '$-16K', '$-4K', '$-4K', '$-2K', '$-2K', '$-894', '$-587', '$-304', '$-72', '$-37', '$-22', '$9', '$-0')
    if year == 2025 and month == 10 and dayofmonth == 23
        plot_c_wall := 36.0
        plot_p_wall := 34.0
        plot_flip   := na
        cur_strikes := array.from(34.0, 33.0, 36.0, 37.0, 38.0, 35.0, 31.0, 32.0, 30.0, 39.0, 40.0, 41.0, 29.0, 28.0)
        cur_lengths := array.from(40, 27, 16, 8, 7, 6, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, 1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1)
        cur_labels  := array.from('$-15K', '$-10K', '$6K', '$-3K', '$-3K', '$-2K', '$-675', '$-661', '$-506', '$-162', '$148', '$-55', '$-4', '$-1')
    if year == 2025 and month == 10 and dayofmonth == 24
        plot_c_wall := 36.0
        plot_p_wall := 38.0
        plot_flip   := na
        cur_strikes := array.from(38.0, 34.0, 37.0, 36.0, 33.0, 35.0, 40.0, 41.0, 39.0, 42.0, 32.0, 31.0, 43.0, 30.0)
        cur_lengths := array.from(40, 33, 28, 24, 13, 8, 7, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, 1, -1, -1, 1, -1, 1, 1, -1, -1, 1, -1)
        cur_labels  := array.from('$-8K', '$-6K', '$-5K', '$5K', '$-3K', '$-2K', '$1K', '$-535', '$334', '$186', '$-73', '$-55', '$29', '$-23')
    if year == 2025 and month == 10 and dayofmonth == 27
        plot_c_wall := 40.0
        plot_p_wall := 38.0
        plot_flip   := 35.5
        cur_strikes := array.from(38.0, 40.0, 41.0, 42.0, 37.0, 36.0, 39.0, 34.0, 43.0, 35.0, 33.0, 44.0, 45.0, 32.0, 31.0)
        cur_lengths := array.from(40, 26, 18, 11, 9, 8, 4, 3, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, 1, -1, 1, -1, 1, 1, -1, 1, -1, -1, 1, 1, -1, -1)
        cur_labels  := array.from('$-7K', '$5K', '$-3K', '$2K', '$-2K', '$2K', '$813', '$-643', '$421', '$-335', '$-104', '$89', '$51', '$-1', '$-0')
    if year == 2025 and month == 10 and dayofmonth == 28
        plot_c_wall := 36.0
        plot_p_wall := 34.0
        plot_flip   := na
        cur_strikes := array.from(34.0, 33.0, 35.0, 36.0, 32.0, 31.0, 38.0, 30.0, 37.0, 40.0, 39.0, 29.0, 41.0, 28.0)
        cur_lengths := array.from(40, 30, 6, 5, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, 1, 1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1)
        cur_labels  := array.from('$-20K', '$-16K', '$3K', '$3K', '$-2K', '$-1K', '$-848', '$-796', '$-465', '$54', '$-19', '$-6', '$-5', '$-1')
    if year == 2025 and month == 10 and dayofmonth == 29
        plot_c_wall := 36.0
        plot_p_wall := 34.0
        plot_flip   := na
        cur_strikes := array.from(34.0, 38.0, 36.0, 33.0, 35.0, 37.0, 40.0, 32.0, 39.0, 41.0, 31.0, 42.0, 30.0, 29.0)
        cur_lengths := array.from(40, 18, 17, 14, 8, 8, 4, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, 1, -1, 1, -1, 1, -1, -1, -1, -1, 1, -1, -1)
        cur_labels  := array.from('$-10K', '$-5K', '$4K', '$-4K', '$2K', '$-2K', '$1K', '$-391', '$-172', '$-126', '$-71', '$39', '$-25', '$-0')
    if year == 2025 and month == 10 and dayofmonth == 30
        plot_c_wall := 35.0
        plot_p_wall := 34.0
        plot_flip   := na
        cur_strikes := array.from(34.0, 33.0, 32.0, 31.0, 35.0, 30.0, 36.0, 38.0, 37.0, 29.0, 40.0, 39.0, 28.0, 27.0)
        cur_lengths := array.from(40, 32, 9, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1, 1, -1, 1, -1, -1, -1, 1, -1, -1, -1)
        cur_labels  := array.from('$-22K', '$-17K', '$-5K', '$-2K', '$2K', '$-2K', '$2K', '$-332', '$-243', '$-57', '$16', '$-5', '$-2', '$-0')
    if year == 2025 and month == 10 and dayofmonth == 31
        plot_c_wall := 36.0
        plot_p_wall := 38.0
        plot_flip   := 35.5
        cur_strikes := array.from(38.0, 34.0, 36.0, 40.0, 37.0, 35.0, 33.0, 41.0, 39.0, 42.0, 32.0, 43.0, 31.0, 30.0)
        cur_lengths := array.from(40, 24, 23, 16, 10, 8, 5, 3, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, 1, 1, -1, 1, -1, -1, -1, 1, -1, 1, -1, -1)
        cur_labels  := array.from('$-7K', '$-4K', '$4K', '$3K', '$-2K', '$1K', '$-922', '$-575', '$-364', '$217', '$-73', '$16', '$-6', '$-1')
    if year == 2025 and month == 11 and dayofmonth == 3
        plot_c_wall := 36.0
        plot_p_wall := 34.0
        plot_flip   := na
        cur_strikes := array.from(34.0, 36.0, 33.0, 38.0, 35.0, 37.0, 40.0, 32.0, 39.0, 41.0, 31.0, 42.0, 30.0, 29.0)
        cur_lengths := array.from(40, 18, 13, 12, 9, 5, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, 1, -1, -1, 1, -1, 1, -1, -1, -1, -1, 1, -1, -1)
        cur_labels  := array.from('$-11K', '$5K', '$-4K', '$-3K', '$3K', '$-1K', '$427', '$-405', '$-97', '$-42', '$-27', '$9', '$-5', '$-0')
    if year == 2025 and month == 11 and dayofmonth == 4
        plot_c_wall := 35.0
        plot_p_wall := 33.0
        plot_flip   := na
        cur_strikes := array.from(33.0, 32.0, 34.0, 31.0, 30.0, 29.0, 35.0, 36.0, 37.0, 28.0, 38.0, 27.0, 26.0)
        cur_lengths := array.from(40, 31, 18, 17, 17, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1, -1, -1, 1, 1, 1, -1, -1, -1, -1)
        cur_labels  := array.from('$-26K', '$-20K', '$-12K', '$-11K', '$-11K', '$-477', '$305', '$142', '$37', '$-34', '$-3', '$-0', '$-0')
    if year == 2025 and month == 11 and dayofmonth == 5
        plot_c_wall := 30.0
        plot_p_wall := 30.0
        plot_flip   := na
        cur_strikes := array.from(30.0, 31.0, 29.0, 32.0, 33.0, 28.0, 34.0, 27.0, 35.0, 26.0, 36.0)
        cur_lengths := array.from(40, 10, 6, 5, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1, -1, -1, -1, -1, 1, -1, 1)
        cur_labels  := array.from('$-80K', '$-22K', '$-12K', '$-11K', '$-4K', '$-3K', '$-471', '$-37', '$18', '$-9', '$0')
    if year == 2025 and month == 11 and dayofmonth == 6
        plot_c_wall := 26.0
        plot_p_wall := 26.0
        plot_flip   := na
        cur_strikes := array.from(26.0, 27.0)
        cur_lengths := array.from(40, 2)
        cur_signs   := array.from(-1, -1)
        cur_labels  := array.from('$-355', '$-0')
    if year == 2025 and month == 11 and dayofmonth == 7
        plot_c_wall := 26.0
        plot_p_wall := 26.0
        plot_flip   := na
        cur_strikes := array.from(26.0, 27.0)
        cur_lengths := array.from(40, 2)
        cur_signs   := array.from(-1, -1)
        cur_labels  := array.from('$-43', '$-0')
    if year == 2025 and month == 11 and dayofmonth == 10
        plot_c_wall := 23.0
        plot_p_wall := 22.0
        plot_flip   := 22.5
        cur_strikes := array.from(23.0, 24.0, 26.0, 27.0, 22.0, 25.0)
        cur_lengths := array.from(40, 6, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, -1, -1, 1, 1)
        cur_labels  := array.from('$7K', '$1K', '$-16', '$-0', '$0', '$0')
    if year == 2025 and month == 11 and dayofmonth == 11
        plot_c_wall := 23.0
        plot_p_wall := 22.0
        plot_flip   := 20.5
        cur_strikes := array.from(23.0, 21.0, 24.0, 25.0, 26.0, 18.0, 22.0, 19.0, 20.0)
        cur_lengths := array.from(40, 5, 3, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, -1, 1, 1, -1, 1, 1, 1, 1)
        cur_labels  := array.from('$6K', '$-862', '$543', '$6', '$-1', '$0', '$0', '$0', '$0')
    if year == 2025 and month == 11 and dayofmonth == 12
        plot_c_wall := 23.0
        plot_p_wall := 23.0
        plot_flip   := 20.5
        cur_strikes := array.from(23.0, 21.0, 24.0, 25.0, 26.0, 18.0, 22.0, 19.0, 20.0)
        cur_lengths := array.from(40, 12, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, 1, 1, -1, 1, 1, 1, 1)
        cur_labels  := array.from('$-6K', '$-2K', '$159', '$1', '$-0', '$0', '$0', '$0', '$0')
    if year == 2025 and month == 11 and dayofmonth == 13
        plot_c_wall := 22.0
        plot_p_wall := 21.0
        plot_flip   := 18.5
        cur_strikes := array.from(21.0, 19.0, 22.0, 23.0, 24.0, 20.0, 18.0)
        cur_lengths := array.from(40, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, 1, -1, 1, 1, 1)
        cur_labels  := array.from('$-6K', '$-108', '$9', '$-0', '$0', '$0', '$0')
    if year == 2025 and month == 11 and dayofmonth == 14
        plot_c_wall := 20.0
        plot_p_wall := 21.0
        plot_flip   := 18.5
        cur_strikes := array.from(21.0, 20.0, 22.0, 19.0, 23.0, 24.0, 18.0)
        cur_lengths := array.from(40, 3, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, 1, 1, -1, -1, 1, 1)
        cur_labels  := array.from('$-12K', '$953', '$63', '$-14', '$-0', '$0', '$0')
    if year == 2025 and month == 11 and dayofmonth == 17
        plot_c_wall := 20.0
        plot_p_wall := 19.0
        plot_flip   := 18.5
        cur_strikes := array.from(19.0, 20.0, 21.0, 22.0, 23.0, 18.0, 17.0)
        cur_lengths := array.from(40, 33, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, 1, -1, 1, -1, 1, 1)
        cur_labels  := array.from('$-2K', '$1K', '$-1', '$0', '$-0', '$0', '$0')
    if year == 2025 and month == 11 and dayofmonth == 18
        plot_c_wall := 20.0
        plot_p_wall := 19.0
        plot_flip   := na
        cur_strikes := array.from(19.0, 20.0, 21.0, 18.0, 22.0, 17.0, 23.0)
        cur_lengths := array.from(40, 23, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, 1, -1, -1, 1, -1, -1)
        cur_labels  := array.from('$-3K', '$2K', '$-0', '$-0', '$0', '$-0', '$-0')
    if year == 2025 and month == 11 and dayofmonth == 19
        plot_c_wall := 21.0
        plot_p_wall := 21.0
        plot_flip   := 19.5
        cur_strikes := array.from(21.0, 20.0, 22.0, 19.0, 23.0, 18.0, 24.0, 17.0)
        cur_lengths := array.from(40, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, 1, 1, -1, -1, -1, 1, -1)
        cur_labels  := array.from('$-21K', '$285', '$1', '$-0', '$-0', '$-0', '$0', '$-0')
    if year == 2025 and month == 11 and dayofmonth == 20
        plot_c_wall := 18.0
        plot_p_wall := 19.0
        plot_flip   := 16.5
        cur_strikes := array.from(19.0, 20.0, 17.0, 21.0, 22.0, 18.0, 15.0, 16.0)
        cur_lengths := array.from(40, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, 1, -1, -1, 1, 1, 1, 1)
        cur_labels  := array.from('$-8K', '$0', '$-0', '$-0', '$0', '$0', '$0', '$0')
    if year == 2025 and month == 11 and dayofmonth == 24
        plot_c_wall := 25.0
        plot_p_wall := 25.0
        plot_flip   := 20.5
        cur_strikes := array.from(26.0, 24.0, 23.0, 22.0, 27.0, 28.0, 29.0, 21.0, 20.0, 25.0)
        cur_lengths := array.from(40, 32, 6, 5, 3, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, -1, 1, -1, 1, -1, 1, -1, 1, 1)
        cur_labels  := array.from('$5K', '$-4K', '$780', '$-619', '$406', '$-123', '$35', '$-4', '$0', '$0')
    if year == 2025 and month == 11 and dayofmonth == 25
        plot_c_wall := 25.0
        plot_p_wall := 25.0
        plot_flip   := 22.5
        cur_strikes := array.from(26.0, 28.0, 27.0, 24.0, 25.0, 23.0, 29.0, 22.0, 30.0, 21.0)
        cur_lengths := array.from(40, 31, 24, 14, 10, 3, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, -1, 1, 1, 1, -1, 1, -1)
        cur_labels  := array.from('$6K', '$5K', '$4K', '$-2K', '$2K', '$466', '$238', '$-142', '$23', '$-1')
    if year == 2025 and month == 11 and dayofmonth == 26
        plot_c_wall := 25.0
        plot_p_wall := 25.0
        plot_flip   := 22.5
        cur_strikes := array.from(27.0, 26.0, 28.0, 24.0, 25.0, 29.0, 23.0, 22.0, 30.0, 21.0)
        cur_lengths := array.from(40, 36, 34, 9, 8, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, -1, 1, 1, 1, -1, 1, -1)
        cur_labels  := array.from('$7K', '$7K', '$6K', '$-2K', '$2K', '$343', '$295', '$-68', '$38', '$-0')
    if year == 2025 and month == 11 and dayofmonth == 28
        plot_c_wall := 28.0
        plot_p_wall := 25.0
        plot_flip   := 22.5
        cur_strikes := array.from(28.0, 27.0, 26.0, 25.0, 29.0, 24.0, 30.0, 23.0, 31.0, 22.0, 21.0)
        cur_lengths := array.from(40, 33, 23, 12, 5, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, 1, 1, -1, 1, -1, 1, 1, -1, -1, -1)
        cur_labels  := array.from('$13K', '$10K', '$7K', '$-4K', '$2K', '$-781', '$155', '$68', '$-8', '$-8', '$-0')
    if year == 2025 and month == 12 and dayofmonth == 1
        plot_c_wall := 24.0
        plot_p_wall := 24.0
        plot_flip   := 19.5
        cur_strikes := array.from(22.0, 24.0, 23.0, 26.0, 25.0, 27.0, 21.0, 20.0, 28.0, 19.0)
        cur_lengths := array.from(40, 36, 35, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, 1, 1, -1, 1, -1, 1, 1, -1)
        cur_labels  := array.from('$-6K', '$-5K', '$5K', '$354', '$-317', '$40', '$-35', '$6', '$4', '$-0')
    if year == 2025 and month == 12 and dayofmonth == 2
        plot_c_wall := 24.0
        plot_p_wall := 24.0
        plot_flip   := 19.5
        cur_strikes := array.from(22.0, 23.0, 24.0, 26.0, 21.0, 27.0, 20.0, 19.0, 25.0)
        cur_lengths := array.from(40, 29, 24, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, 1, -1, 1, -1, 1, 1, -1, 1)
        cur_labels  := array.from('$-8K', '$6K', '$-5K', '$193', '$-77', '$13', '$10', '$-0', '$0')
    if year == 2025 and month == 12 and dayofmonth == 3
        plot_c_wall := 25.0
        plot_p_wall := 24.0
        plot_flip   := 20.5
        cur_strikes := array.from(24.0, 23.0, 22.0, 26.0, 25.0, 27.0, 28.0, 21.0, 20.0)
        cur_lengths := array.from(40, 20, 10, 7, 3, 2, 2, 2, 2)
        cur_signs   := array.from(-1, 1, -1, 1, 1, 1, 1, -1, 1)
        cur_labels  := array.from('$-6K', '$3K', '$-2K', '$1K', '$599', '$118', '$12', '$-9', '$0')
    if year == 2025 and month == 12 and dayofmonth == 4
        plot_c_wall := 25.0
        plot_p_wall := 25.0
        plot_flip   := 20.5
        cur_strikes := array.from(26.0, 24.0, 25.0, 27.0, 23.0, 28.0, 22.0, 29.0, 21.0, 20.0)
        cur_lengths := array.from(40, 24, 15, 9, 4, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, -1, -1, 1, 1, 1, -1, 1, -1, 1)
        cur_labels  := array.from('$5K', '$-3K', '$-2K', '$1K', '$612', '$288', '$-82', '$6', '$-0', '$0')
    if year == 2025 and month == 12 and dayofmonth == 5
        plot_c_wall := 25.0
        plot_p_wall := 25.0
        plot_flip   := 22.5
        cur_strikes := array.from(26.0, 24.0, 25.0, 27.0, 28.0, 23.0, 22.0, 29.0, 30.0, 21.0)
        cur_lengths := array.from(40, 13, 12, 11, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, -1, -1, 1, 1, 1, -1, 1, 1, -1)
        cur_labels  := array.from('$7K', '$-2K', '$-2K', '$2K', '$453', '$298', '$-23', '$9', '$0', '$-0')
    if year == 2025 and month == 12 and dayofmonth == 8
        plot_c_wall := 25.0
        plot_p_wall := 25.0
        plot_flip   := 22.5
        cur_strikes := array.from(26.0, 25.0, 27.0, 24.0, 28.0, 23.0, 29.0, 22.0, 30.0, 21.0)
        cur_lengths := array.from(40, 10, 9, 6, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, -1, 1, -1, 1, 1, 1, -1, 1, -1)
        cur_labels  := array.from('$9K', '$-2K', '$2K', '$-1K', '$352', '$63', '$4', '$-1', '$0', '$-0')
    if year == 2025 and month == 12 and dayofmonth == 9
        plot_c_wall := 25.0
        plot_p_wall := 25.0
        plot_flip   := 20.5
        cur_strikes := array.from(24.0, 25.0, 26.0, 23.0, 27.0, 22.0, 28.0, 21.0, 29.0, 20.0)
        cur_lengths := array.from(40, 15, 14, 6, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, 1, 1, 1, -1, 1, -1, 1, 1)
        cur_labels  := array.from('$-5K', '$-2K', '$2K', '$896', '$84', '$-52', '$2', '$-0', '$0', '$0')
    if year == 2025 and month == 12 and dayofmonth == 10
        plot_c_wall := 24.0
        plot_p_wall := 24.0
        plot_flip   := 20.5
        cur_strikes := array.from(24.0, 23.0, 25.0, 22.0, 26.0, 27.0, 21.0, 28.0, 20.0)
        cur_lengths := array.from(40, 12, 5, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, 1, -1, -1, 1, 1, -1, 1, 1)
        cur_labels  := array.from('$-7K', '$2K', '$-987', '$-314', '$277', '$3', '$-0', '$0', '$0')
    if year == 2025 and month == 12 and dayofmonth == 11
        plot_c_wall := 23.0
        plot_p_wall := 24.0
        plot_flip   := 19.5
        cur_strikes := array.from(23.0, 22.0, 24.0, 21.0, 26.0, 20.0, 27.0, 19.0, 25.0)
        cur_lengths := array.from(40, 29, 13, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, -1, -1, -1, 1, 1, 1, -1, 1)
        cur_labels  := array.from('$9K', '$-6K', '$-3K', '$-6', '$1', '$0', '$0', '$-0', '$0')
    if year == 2025 and month == 12 and dayofmonth == 12
        plot_c_wall := 20.0
        plot_p_wall := 22.0
        plot_flip   := 19.5
        cur_strikes := array.from(22.0, 21.0, 20.0, 23.0, 19.0, 24.0, 25.0, 17.0, 18.0)
        cur_lengths := array.from(40, 20, 17, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, 1, 1, -1, -1, 1, -1, 1)
        cur_labels  := array.from('$-9K', '$-5K', '$4K', '$22', '$-1', '$-0', '$0', '$-0', '$0')
    if year == 2025 and month == 12 and dayofmonth == 15
        plot_c_wall := 20.0
        plot_p_wall := 20.0
        plot_flip   := 19.5
        cur_strikes := array.from(20.0, 21.0, 19.0, 22.0, 23.0, 17.0, 16.0, 18.0)
        cur_lengths := array.from(40, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, -1, -1, -1, 1, -1, -1, 1)
        cur_labels  := array.from('$48K', '$-2K', '$-310', '$-0', '$0', '$-0', '$-0', '$0')
    if year == 2025 and month == 12 and dayofmonth == 16
        plot_c_wall := 20.0
        plot_p_wall := 20.0
        plot_flip   := 19.5
        cur_strikes := array.from(20.0, 19.0, 21.0, 18.0, 22.0, 17.0, 23.0, 16.0)
        cur_lengths := array.from(40, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(1, -1, -1, -1, -1, -1, 1, -1)
        cur_labels  := array.from('$29K', '$-1K', '$-24', '$-0', '$-0', '$-0', '$0', '$-0')
    if year == 2025 and month == 12 and dayofmonth == 17
        plot_c_wall := 18.0
        plot_p_wall := 18.0
        plot_flip   := na
        cur_strikes := array.from(18.0, 17.0, 19.0, 16.0, 20.0, 15.0, 21.0)
        cur_lengths := array.from(40, 30, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1, 1, -1, -1)
        cur_labels  := array.from('$-7K', '$-6K', '$-0', '$-0', '$0', '$-0', '$-0')
    if year == 2025 and month == 12 and dayofmonth == 18
        plot_c_wall := 17.0
        plot_p_wall := 16.0
        plot_flip   := na
        cur_strikes := array.from(16.0, 17.0, 15.0, 18.0, 14.0, 19.0)
        cur_lengths := array.from(40, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1, -1, -1)
        cur_labels  := array.from('$-5K', '$-14', '$-0', '$-0', '$-0', '$-0')
    if year == 2025 and month == 12 and dayofmonth == 22
        plot_c_wall := 18.0
        plot_p_wall := 17.0
        plot_flip   := na
        cur_strikes := array.from(17.0, 19.0, 20.0, 18.0, 16.0, 21.0, 15.0)
        cur_lengths := array.from(40, 22, 6, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, 1, -1, -1, -1, -1)
        cur_labels  := array.from('$-20K', '$-11K', '$3K', '$-773', '$-512', '$-45', '$-3')
    if year == 2025 and month == 12 and dayofmonth == 23
        plot_c_wall := 16.0
        plot_p_wall := 15.0
        plot_flip   := na
        cur_strikes := array.from(15.0, 14.0, 16.0)
        cur_lengths := array.from(40, 5, 2)
        cur_signs   := array.from(-1, -1, -1)
        cur_labels  := array.from('$-13K', '$-2K', '$-302')
    if year == 2025 and month == 12 and dayofmonth == 24
        plot_c_wall := 16.0
        plot_p_wall := 15.0
        plot_flip   := na
        cur_strikes := array.from(15.0, 14.0, 16.0)
        cur_lengths := array.from(40, 7, 2)
        cur_signs   := array.from(-1, -1, -1)
        cur_labels  := array.from('$-8K', '$-2K', '$-131')
    if year == 2025 and month == 12 and dayofmonth == 26
        plot_c_wall := 15.0
        plot_p_wall := 12.0
        plot_flip   := 11.5
        cur_strikes := array.from(12.0, 15.0, 11.0, 13.0, 14.0)
        cur_lengths := array.from(40, 2, 2, 2, 2)
        cur_signs   := array.from(-1, 1, 1, 1, 1)
        cur_labels  := array.from('$-786', '$46', '$0', '$0', '$0')
    if year == 2025 and month == 12 and dayofmonth == 27
        plot_c_wall := 11.0
        plot_p_wall := 14.0
        plot_flip   := 13.5
        cur_strikes := array.from(14.0, 11.0, 12.0, 13.0)
        cur_lengths := array.from(40, 2, 2, 2)
        cur_signs   := array.from(-1, 1, 1, 1)
        cur_labels  := array.from('$-116', '$0', '$0', '$0')
    if year == 2025 and month == 12 and dayofmonth == 28
        plot_c_wall := 11.0
        plot_p_wall := 14.0
        plot_flip   := 13.5
        cur_strikes := array.from(14.0, 11.0, 12.0, 13.0)
        cur_lengths := array.from(40, 2, 2, 2)
        cur_signs   := array.from(-1, 1, 1, 1)
        cur_labels  := array.from('$-116', '$0', '$0', '$0')
    if year == 2025 and month == 12 and dayofmonth == 29
        plot_c_wall := 11.0
        plot_p_wall := 14.0
        plot_flip   := 13.5
        cur_strikes := array.from(14.0, 11.0, 12.0, 13.0)
        cur_lengths := array.from(40, 2, 2, 2)
        cur_signs   := array.from(-1, 1, 1, 1)
        cur_labels  := array.from('$-116', '$0', '$0', '$0')
    if year == 2025 and month == 12 and dayofmonth == 30
        plot_c_wall := 11.0
        plot_p_wall := 12.0
        plot_flip   := 11.5
        cur_strikes := array.from(12.0, 11.0, 13.0, 14.0)
        cur_lengths := array.from(40, 2, 2, 2)
        cur_signs   := array.from(-1, 1, 1, 1)
        cur_labels  := array.from('$-554', '$0', '$0', '$0')
    if year == 2025 and month == 12 and dayofmonth == 31
        plot_c_wall := 11.0
        plot_p_wall := 13.0
        plot_flip   := 11.5
        cur_strikes := array.from(13.0, 12.0, 11.0)
        cur_lengths := array.from(40, 16, 2)
        cur_signs   := array.from(-1, -1, 1)
        cur_labels  := array.from('$-1K', '$-582', '$0')
    if year == 2026 and month == 1 and dayofmonth == 1
        plot_c_wall := 10.0
        plot_p_wall := 12.0
        plot_flip   := 11.5
        cur_strikes := array.from(12.0, 13.0, 11.0, 10.0)
        cur_lengths := array.from(40, 37, 2, 2)
        cur_signs   := array.from(-1, -1, 1, 1)
        cur_labels  := array.from('$-2K', '$-1K', '$0', '$0')
    if year == 2026 and month == 1 and dayofmonth == 2
        plot_c_wall := 13.0
        plot_p_wall := 12.0
        plot_flip   := 10.5
        cur_strikes := array.from(12.0, 13.0, 11.0, 10.0)
        cur_lengths := array.from(40, 20, 6, 2)
        cur_signs   := array.from(-1, -1, -1, 1)
        cur_labels  := array.from('$-3K', '$-1K', '$-471', '$0')
    if year == 2026 and month == 1 and dayofmonth == 3
        plot_c_wall := 14.0
        plot_p_wall := 12.0
        plot_flip   := na
        cur_strikes := array.from(12.0, 13.0, 14.0, 11.0)
        cur_lengths := array.from(40, 20, 8, 6)
        cur_signs   := array.from(-1, -1, 1, -1)
        cur_labels  := array.from('$-3K', '$-2K', '$662', '$-515')
    if year == 2026 and month == 1 and dayofmonth == 4
        plot_c_wall := 14.0
        plot_p_wall := 12.0
        plot_flip   := na
        cur_strikes := array.from(12.0, 13.0, 14.0, 11.0)
        cur_lengths := array.from(40, 18, 18, 8)
        cur_signs   := array.from(-1, -1, 1, -1)
        cur_labels  := array.from('$-2K', '$-1K', '$1K', '$-486')
    if year == 2026 and month == 1 and dayofmonth == 5
        plot_c_wall := 15.0
        plot_p_wall := 12.0
        plot_flip   := 10.5
        cur_strikes := array.from(12.0, 15.0, 13.0, 14.0, 11.0, 29.0, 26.0, 27.0, 30.0, 6.0, 7.0, 8.0, 9.0, 10.0, 5.0, 16.0, 17.0, 18.0, 22.0, 21.0, 20.0, 19.0, 25.0, 24.0, 23.0, 28.0)
        cur_lengths := array.from(40, 26, 18, 18, 8, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, 1, -1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)
        cur_labels  := array.from('$-2K', '$2K', '$-1K', '$1K', '$-494', '$172', '$87', '$41', '$34', '$0', '$0', '$0', '$0', '$0', '$0', '$0', '$0', '$0', '$0', '$0', '$0', '$0', '$0', '$0', '$0', '$0')
    if year == 2026 and month == 1 and dayofmonth == 6
        plot_c_wall := 15.0
        plot_p_wall := 12.0
        plot_flip   := na
        cur_strikes := array.from(12.0, 15.0, 13.0, 14.0)
        cur_lengths := array.from(40, 26, 25, 18)
        cur_signs   := array.from(-1, 1, -1, 1)
        cur_labels  := array.from('$-2K', '$2K', '$-2K', '$1K')
    if year == 2026 and month == 1 and dayofmonth == 7
        plot_c_wall := 15.0
        plot_p_wall := 14.0
        plot_flip   := na
        cur_strikes := array.from(15.0, 14.0, 16.0, 17.0, 18.0)
        cur_lengths := array.from(40, 18, 7, 2, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1)
        cur_labels  := array.from('$2K', '$1K', '$414', '$0', '$0')
    if year == 2026 and month == 1 and dayofmonth == 8
        plot_c_wall := 14.0
        plot_p_wall := 14.0
        plot_flip   := na
        cur_strikes := array.from(15.0, 14.0, 18.0, 16.0, 17.0)
        cur_lengths := array.from(40, 30, 11, 7, 2)
        cur_signs   := array.from(1, 1, 1, 1, 1)
        cur_labels  := array.from('$2K', '$2K', '$617', '$393', '$0')
    if year == 2026 and month == 1 and dayofmonth == 9
        plot_c_wall := 14.0
        plot_p_wall := 13.0
        plot_flip   := 13.5
        cur_strikes := array.from(15.0, 14.0, 16.0, 13.0, 17.0)
        cur_lengths := array.from(40, 38, 23, 22, 11)
        cur_signs   := array.from(1, 1, 1, -1, 1)
        cur_labels  := array.from('$2K', '$2K', '$1K', '$-1K', '$547')
    if year == 2026 and month == 1 and dayofmonth == 10
        plot_c_wall := 14.0
        plot_p_wall := 13.0
        plot_flip   := 13.5
        cur_strikes := array.from(14.0, 15.0, 16.0, 13.0)
        cur_lengths := array.from(40, 39, 17, 8)
        cur_signs   := array.from(1, 1, 1, -1)
        cur_labels  := array.from('$3K', '$3K', '$1K', '$-699')
    [plot_c_wall, plot_p_wall, plot_flip, cur_strikes, cur_lengths, cur_signs, cur_labels]

// ===== TSLL FUNCTION =====
f_symbol_TSLL() =>
    var float plot_c_wall = na
    var float plot_p_wall = na
    var float plot_flip   = na
    var float[] cur_strikes = array.new_float()
    var int[]   cur_lengths = array.new_int()
    var int[]   cur_signs   = array.new_int()
    var string[] cur_labels = array.new_string()
    if year == 2026 and month == 1 and dayofmonth == 2
        plot_c_wall := 20.5
        plot_p_wall := 19.0
        plot_flip   := na
        cur_strikes := array.from(19.0, 19.5, 20.0, 18.5, 18.0, 20.43, 21.5, 21.43, 17.0, 19.43, 21.0, 17.5, 18.43, 16.5, 20.5, 17.43, 16.43)
        cur_lengths := array.from(40, 35, 25, 17, 17, 5, 4, 4, 3, 3, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1, -1, 1, -1, 1, -1, 1, 1, -1, 1, -1, 1, -1, -1)
        cur_labels  := array.from('$-5.82M', '$-5.13M', '$-3.74M', '$-2.52M', '$-2.50M', '$749K', '$-709K', '$668K', '$-573K', '$565K', '$431K', '$-420K', '$281K', '$-134K', '$130K', '$-75K', '$-22K')
    if year == 2026 and month == 1 and dayofmonth == 3
        plot_c_wall := 20.43
        plot_p_wall := 20.0
        plot_flip   := na
        cur_strikes := array.from(18.0, 19.0, 20.0, 19.5, 20.43, 18.5, 19.43, 17.0, 21.0, 17.5, 18.43, 16.0, 20.5, 16.5, 17.43, 16.43)
        cur_lengths := array.from(40, 39, 32, 26, 23, 18, 17, 14, 13, 9, 8, 6, 3, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1, 1, -1, 1, -1, -1, -1, 1, -1, -1, -1, -1, -1)
        cur_labels  := array.from('$-1.22M', '$-1.21M', '$-999K', '$-815K', '$716K', '$-553K', '$540K', '$-457K', '$-407K', '$-276K', '$269K', '$-213K', '$-95K', '$-73K', '$-72K', '$-21K')
    if year == 2026 and month == 1 and dayofmonth == 4
        plot_c_wall := 21.0
        plot_p_wall := 19.5
        plot_flip   := na
        cur_strikes := array.from(19.5, 20.0, 18.0, 19.0, 18.5, 17.0, 17.5, 20.5, 21.0, 16.5, 16.0)
        cur_lengths := array.from(40, 30, 30, 27, 17, 12, 8, 7, 4, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1)
        cur_labels  := array.from('$-945K', '$-725K', '$-710K', '$-659K', '$-421K', '$-296K', '$-202K', '$-183K', '$105K', '$-65K', '$-46K')
    if year == 2026 and month == 1 and dayofmonth == 5
        plot_c_wall := 20.5
        plot_p_wall := 19.5
        plot_flip   := na
        cur_strikes := array.from(19.5, 20.0, 18.0, 19.0, 18.5, 17.0, 17.5, 20.5, 16.5, 16.0, 15.5)
        cur_lengths := array.from(40, 30, 30, 27, 17, 12, 8, 7, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1)
        cur_labels  := array.from('$-937K', '$-718K', '$-703K', '$-653K', '$-417K', '$-294K', '$-200K', '$-182K', '$-64K', '$-45K', '$-663')
    if year == 2026 and month == 1 and dayofmonth == 6
        plot_c_wall := 21.0
        plot_p_wall := 19.5
        plot_flip   := na
        cur_strikes := array.from(19.5, 20.0, 18.0, 19.0, 18.5, 17.0, 17.5, 20.5, 23.5, 22.5, 21.0, 21.5, 23.0, 16.5, 25.0, 22.0, 24.0, 16.0, 26.0, 13.0, 27.0, 30.0, 12.0, 14.0, 15.0, 28.0, 29.0, 35.0, 15.5, 14.5, 34.0, 11.0, 33.0, 10.0, 24.5)
        cur_lengths := array.from(40, 30, 30, 27, 17, 12, 8, 7, 5, 4, 4, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1, -1, -1, -1, -1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, -1, -1, -1, 1, 1, 1, -1, -1, 1, -1, 1, -1, 1)
        cur_labels  := array.from('$-994K', '$-762K', '$-746K', '$-692K', '$-442K', '$-311K', '$-212K', '$-193K', '$129K', '$124K', '$110K', '$-106K', '$103K', '$-68K', '$61K', '$-58K', '$55K', '$-48K', '$42K', '$-27K', '$9K', '$8K', '$-8K', '$-7K', '$-5K', '$4K', '$3K', '$888', '$-703', '$-700', '$657', '$-175', '$173', '$-8', '$0')
    if year == 2026 and month == 1 and dayofmonth == 7
        plot_c_wall := 20.0
        plot_p_wall := 19.5
        plot_flip   := na
        cur_strikes := array.from(19.5, 20.0, 19.0, 18.0, 18.5, 17.0, 17.5, 16.5, 16.0, 15.5)
        cur_lengths := array.from(40, 30, 24, 15, 12, 3, 3, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1, -1, -1, -1, -1, -1, -1)
        cur_labels  := array.from('$-1.88M', '$-1.41M', '$-1.14M', '$-728K', '$-586K', '$-182K', '$-165K', '$-33K', '$-18K', '$-275')
    if year == 2026 and month == 1 and dayofmonth == 8
        plot_c_wall := 20.0
        plot_p_wall := 19.0
        plot_flip   := na
        cur_strikes := array.from(18.0, 19.0, 17.0, 18.5, 17.5, 19.5, 16.5, 16.0, 23.0, 22.0, 21.0, 15.0, 24.0, 20.5, 20.0, 25.0, 14.0, 13.0, 22.5, 23.5, 26.0, 21.5, 12.0, 15.5, 28.0, 30.0, 27.0, 29.0, 32.0, 35.0, 14.5, 31.0, 10.0, 11.0, 24.5, 25.5, 33.0, 34.0, 5.0, 26.5)
        cur_lengths := array.from(40, 35, 28, 24, 19, 10, 10, 9, 9, 8, 8, 6, 4, 4, 4, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1, -1, -1, -1, -1, 1, 1, 1, -1, 1, 1, 1, 1, -1, -1, 1, 1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, -1, 1, -1, -1, 1, 1, 1, 1, -1, 1)
        cur_labels  := array.from('$-3.74M', '$-3.31M', '$-2.63M', '$-2.28M', '$-1.78M', '$-951K', '$-947K', '$-888K', '$844K', '$818K', '$789K', '$-562K', '$463K', '$438K', '$397K', '$338K', '$-192K', '$-190K', '$160K', '$160K', '$143K', '$125K', '$-115K', '$-108K', '$69K', '$68K', '$63K', '$32K', '$27K', '$21K', '$-19K', '$10K', '$-6K', '$-4K', '$3K', '$3K', '$2K', '$548', '$-310', '$0')
    if year == 2026 and month == 1 and dayofmonth == 9
        plot_c_wall := 20.0
        plot_p_wall := 18.0
        plot_flip   := 15.75
        cur_strikes := array.from(18.0, 17.0, 18.5, 16.5, 16.0, 17.5, 19.0, 20.0, 20.43, 17.43, 20.5, 15.43, 15.5, 19.43, 16.43, 19.5, 18.43)
        cur_lengths := array.from(40, 33, 17, 13, 10, 9, 6, 6, 5, 3, 2, 2, 2, 2, 2, 2, 2)
        cur_signs   := array.from(-1, -1, -1, -1, -1, -1, -1, 1, 1, -1, 1, 1, -1, 1, -1, -1, -1)
        cur_labels  := array.from('$-6.23M', '$-5.16M', '$-2.71M', '$-2.05M', '$-1.66M', '$-1.46M', '$-1.07M', '$950K', '$817K', '$-569K', '$352K', '$315K', '$-312K', '$267K', '$-220K', '$-211K', '$-38K')
    if year == 2026 and month == 1 and dayofmonth == 10
        plot_c_wall := 20.0
        plot_p_wall := 18.0
        plot_flip   := na
        cur_strikes := array.from(17.0, 18.5, 20.0, 16.0, 18.0, 16.5, 17.5, 19.0, 20.43, 21.0, 17.43, 19.43, 20.5, 19.5, 16.43, 18.43)
        cur_lengths := array.from(40, 39, 34, 27, 23, 19, 19, 16, 13, 11, 11, 8, 6, 6, 4, 2)
        cur_signs   := array.from(-1, -1, 1, -1, -1, -1, -1, -1, 1, 1, -1, 1, 1, 1, -1, 1)
        cur_labels  := array.from('$-1.53M', '$-1.51M', '$1.33M', '$-1.04M', '$-892K', '$-757K', '$-756K', '$-614K', '$507K', '$459K', '$-423K', '$341K', '$267K', '$263K', '$-164K', '$50K')
    [plot_c_wall, plot_p_wall, plot_flip, cur_strikes, cur_lengths, cur_signs, cur_labels]

// ===== MAIN CALLS =====
if current_ticker == "AMZU"
    [plot_c_wall, plot_p_wall, plot_flip, cur_strikes, cur_lengths, cur_signs, cur_labels] := f_symbol_AMZU()
if current_ticker == "BBAI"
    [plot_c_wall, plot_p_wall, plot_flip, cur_strikes, cur_lengths, cur_signs, cur_labels] := f_symbol_BBAI()
if current_ticker == "BITO"
    [plot_c_wall, plot_p_wall, plot_flip, cur_strikes, cur_lengths, cur_signs, cur_labels] := f_symbol_BITO()
if current_ticker == "BMNU"
    [plot_c_wall, plot_p_wall, plot_flip, cur_strikes, cur_lengths, cur_signs, cur_labels] := f_symbol_BMNU()
if current_ticker == "CLF"
    [plot_c_wall, plot_p_wall, plot_flip, cur_strikes, cur_lengths, cur_signs, cur_labels] := f_symbol_CLF()
if current_ticker == "MSTU"
    [plot_c_wall, plot_p_wall, plot_flip, cur_strikes, cur_lengths, cur_signs, cur_labels] := f_symbol_MSTU()
if current_ticker == "NOK"
    [plot_c_wall, plot_p_wall, plot_flip, cur_strikes, cur_lengths, cur_signs, cur_labels] := f_symbol_NOK()
if current_ticker == "OPEN"
    [plot_c_wall, plot_p_wall, plot_flip, cur_strikes, cur_lengths, cur_signs, cur_labels] := f_symbol_OPEN()
if current_ticker == "QQQ"
    [plot_c_wall, plot_p_wall, plot_flip, cur_strikes, cur_lengths, cur_signs, cur_labels] := f_symbol_QQQ()
if current_ticker == "RR"
    [plot_c_wall, plot_p_wall, plot_flip, cur_strikes, cur_lengths, cur_signs, cur_labels] := f_symbol_RR()
if current_ticker == "SOFI"
    [plot_c_wall, plot_p_wall, plot_flip, cur_strikes, cur_lengths, cur_signs, cur_labels] := f_symbol_SOFI()
if current_ticker == "SOXL"
    [plot_c_wall, plot_p_wall, plot_flip, cur_strikes, cur_lengths, cur_signs, cur_labels] := f_symbol_SOXL()
if current_ticker == "SPY"
    [plot_c_wall, plot_p_wall, plot_flip, cur_strikes, cur_lengths, cur_signs, cur_labels] := f_symbol_SPY()
if current_ticker == "TEMT"
    [plot_c_wall, plot_p_wall, plot_flip, cur_strikes, cur_lengths, cur_signs, cur_labels] := f_symbol_TEMT()
if current_ticker == "TSLL"
    [plot_c_wall, plot_p_wall, plot_flip, cur_strikes, cur_lengths, cur_signs, cur_labels] := f_symbol_TSLL()

plot(plot_c_wall, "Call Wall", color=color.new(color.green, 20), linewidth=2, style=plot.style_stepline)
plot(plot_p_wall, "Put Wall",  color=color.new(color.red, 20),   linewidth=2, style=plot.style_stepline)
plot(plot_flip,   "Flip Zone", color=color.blue, linewidth=1, style=plot.style_circles)

if array.size(cur_strikes) > 0
    for i = 0 to array.size(cur_strikes) - 1
        float s = array.get(cur_strikes, i)
        int l   = array.get(cur_lengths, i)
        int sg  = array.get(cur_signs, i)
        string txt = array.get(cur_labels, i)

        col = sg > 0 ? color.new(color.green, 40) : color.new(color.red, 40)
        txt_col = sg > 0 ? color.green : color.red

        line.new(bar_index, s, bar_index + l, s, color=col, width=2)
        label.new(bar_index + l, s, txt, style=label.style_label_left, textcolor=txt_col, color=color.new(color.white, 100), size=size.small)
